### ISSUE TITLE
客户端往服务端上传文件返回码500

### ISSUE THREAD

**Issue by mocc99** [yanzhenjie/AndServer#10]
服务端报错：org.apache.commons.fileupload.FileUploadException: the request was rejected because no multipart boundary was found

客户端请求代码：
 MediaType imageMediaType = MediaType.parse("multipart/form-data");
        File imageFile = new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS), "666.jpg");
        RequestBody requestBody = RequestBody.create(imageMediaType, imageFile);
        Request request = new Request.Builder().url("http://192.168.1.100:8080/upload").post(requestBody).build();
        Call call = client.newCall(request);
        call.enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                Message msg=mhandler.obtainMessage();
                msg.what = 0;
                msg.obj = "onFailure" + e.toString();
                mhandler.sendMessage(msg);
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                Message msg=mhandler.obtainMessage();
                msg.what = 0;
                msg.obj = "onResponse"+response.toString();
                mhandler.sendMessage(msg);
            }
        });

客户端用的是okhttp，问一下是不是客户端代码有问题？

**Comment by mocc99** [comment]
客户端代码写得有问题

**Comment by EthanCo** [comment]
@mocc99 可以复制下正确的代码吗? 我这边也出现了返回码500的问题

**Comment by yanzhenjie** [comment]
客户端推荐使用[NoHttp](https://github.com/yanzhenjie/NoHttp)，一行代码搞定上传:  
开源地址：[https://github.com/yanzhenjie/NoHttp](https://github.com/yanzhenjie/NoHttp)
