### ISSUE TITLE
无法通过 http://127.0.0.1:8080/ 访问服务器

### ISSUE THREAD

**Issue by Nelson-KK** [yanzhenjie/AndServer#100]
你好，我使用AndServer 无法在浏览器 输入 http://127.0.0.1:8080/  对服务器进行访问。 大神救命啊。。。我之前用的NanoHttp 踩了好久的坑，项目马上要交了，麻烦你帮帮我

**Comment by Nelson-KK** [comment]
但是输入  局域网内的 192.168.xx.xx 可以访问

**Comment by Nelson-KK** [comment]
在Android 本机浏览器 192.168.xx.xx 可以访问  我的需求是  我给系统图片浏览器 一个 url地址，然后可以看图片，或者给视频播放器一个 url 可以进行播放 ，但是给的局域网地址第三方App会直接蹦掉

**Comment by yanzhenjie** [comment]
如果还有有疑问，你可以在上一个问题继续追问。

该项目是在一个设备起一个server，并提供http访问的能力，至于设备的ip是什么，127.0.0.1是否被设备解析到自身都不是该项目能控制的。

一般127.0.0.1都会被系统保留，无法访问的原因可能是地址输错或者端口写错之类的。

----

第三方app接收到某url会蹦掉，说明第三方app有bug，与本项目甚至你自己的项目都是没有关系的。

**Comment by Gdailyer** [comment]
if (inetAddress.isLoopbackAddress() && isIPv4Address(inetAddress.getHostAddress())) {
                            return inetAddress;
                        }
