### ISSUE TITLE
无法下载commons-io & httpcore

### ISSUE THREAD

**Issue by Ihsan2017** [yanzhenjie/AndServer#102]
你好，我在本地引入andServer 1.1.4, 其中https://jcenter.bintray.com/commons-io/commons-io/2.6/commons-io-2.6.jar 和 https://jcenter.bintray.com/com/yanzhenjie/apache/httpcore/4.4.9/httpcore-4.4.9.jar 下载不下来。
请问是还需要什么配置吗？谢谢
@yanzhenjie

**Comment by yanzhenjie** [comment]
不需要，只要你根项目配置了jcenter或者mave库就可以，如果不可以一般是网络问题。

**Comment by Ihsan2017** [comment]
谢谢
