### ISSUE TITLE
关于放回Html页面的问题

### ISSUE THREAD

**Issue by Nelson-KK** [yanzhenjie/AndServer#104]
我的需求终于完成了，多谢大神写了这个框架，但是我有个疑问的是，我之前使用NanoHttpd 返回网页， 在网页中有个JS无法调用卡了很久，使用你写的这个框架为什么可以正常运行呢，我想问一下你在返回网页时做了什么特殊的处理吗，我看你也是返回的一个流文件

**Comment by yanzhenjie** [comment]
第一次听说Nanohttpd，没有学习过它是如何实现的，因此不知道有什么不同，可能是因为我长的比较帅吧。
