### ISSUE TITLE
关于文件上传

### ISSUE THREAD

**Issue by Nelson-KK** [yanzhenjie/AndServer#108]
FileItemFactory factory = new DiskFileItemFactory(1024 * 1024, mTmpFileDirectory);
HttpFileUpload fileUpload = new HttpFileUpload(factory);
HttpUploadContext context = new HttpUploadContext((HttpEntityEnclosingRequest) request);        List<FileItem> fileItems = fileUpload.parseRequest(context);
 
fileItem.write(uploadedFile);

你好，fileitem.write(uploadFile)这个语句是做了文件移动处理还是 copy之后再删除临时文件，我想知道这个具体是做了什么操作

**Comment by yanzhenjie** [comment]
我也不知道，你点进去看。
