### ISSUE TITLE
请问支持本机访问吗？

### ISSUE THREAD

**Issue by jiansheliuxing** [yanzhenjie/AndServer#110]
我在一台手机起了一个server，然后在本机使用127.0.0.1或者localhost可以访问到吗？我尝试了一下发现不行，是不是哪里设置错了？
 http://127.0.0.1:38657/media_proxy?
 http://localhost:38657/media_proxy?

**Comment by yanzhenjie** [comment]
支持，从你的描述具体原因未知，从你的描述**不行**不知道是什么问题。

猜测可能是注册的`path`不是`media_proxy`。
