### ISSUE TITLE
@DeleteMapping报错

### ISSUE THREAD

**Issue by gyt1001** [yanzhenjie/AndServer#115]
W/System.err: java.lang.ClassCastException: org.apache.httpcore.message.BasicHttpRequest cannot be cast to org.apache.httpcore.HttpEntityEnclosingRequest
W/System.err:     at com.yanzhenjie.andserver.http.StandardRequest.getBody(StandardRequest.java:412)
W/System.err:     at com.yanzhenjie.andserver.http.multipart.StandardMultipartResolver.isMultipart(StandardMultipartResolver.java:111)
W/System.err:     at com.yanzhenjie.andserver.DispatcherHandler.handle(DispatcherHandler.java:123)
W/System.err:     at com.yanzhenjie.andserver.DispatcherHandler.handle(DispatcherHandler.java:118)
W/System.err:     at org.apache.httpcore.protocol.HttpService.doService(HttpService.java:400)
W/System.err:     at org.apache.httpcore.protocol.HttpService.handleRequest(HttpService.java:313)
W/System.err:     at org.apache.httpcore.impl.bootstrap.Worker.run(Worker.java:65)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by nuoyan2** [comment]
你好，请问你解决了这个BUG了吗 可以添加519719668讨论下吗

**Comment by nuoyan2** [comment]
上面的是QQ和微信的号

**Comment by nuoyan2** [comment]
或者大佬留个联系方式 非常感谢

**Comment by nuoyan2** [comment]
@gyt1001 大佬有解决吗

**Comment by nuoyan2** [comment]
感谢严大佬的指点 修正方法 把app的build.gradle 的 dependencies方法中 implementation rootProject.ext.dependencies.andserverApi 注释掉 另加 implementation project(':api')

**Comment by Anotherdgf** [comment]
ok ！
