### ISSUE TITLE
是否有可能移植到纯java环境下运行？

### ISSUE THREAD

**Issue by wujushan** [yanzhenjie/AndServer#116]
如题

**Comment by yanzhenjie** [comment]
完全可以，本身是使用纯Java Api开发的，只是写完后针对Android特性用了一些针对Android的封装，这些封装里面使用了Android的一些Api。

只需要去掉这些针对Android的封装，然后写一个`Main`类并提供`main()`方法，这个方法里面写针对JavaJVM启动服务器的代码即可。
