### ISSUE TITLE
打开地址显示The resouce [/] is not found

### ISSUE THREAD

**Issue by rodger123456** [yanzhenjie/AndServer#119]
按照v2.0.1 的sample 内文件照搬测试，启动server成功，但打开页面显示The resouce [/] is not found

**Comment by yanzhenjie** [comment]
Demo是可以的，说明照搬还是存在一些问题，认真检查一下。

**Comment by VliceZ** [comment]
遇到同样的问题了，请问解决了吗 ？@rodger123456

**Comment by VliceZ** [comment]
原来是需要把simple里的assets文件也copy过来。

**Comment by qq542288564** [comment]
@VliceZ 我拷贝assets好像也没用
