### ISSUE TITLE
关于AssetsManager的引用

### ISSUE THREAD

**Issue by liujunhongz** [yanzhenjie/AndServer#12]
sample中CoreService在停止服务后关闭对AseetsManager的引用，重新开始服务后，会导致AssetsWebsite无法获取到assets中的文件。
如果不关闭，重新开始就正常了。
请问这个manager如何处理比较好？

**Comment by yanzhenjie** [comment]
根据`Service`生命周期，如果服务器被销毁，重新开启服务后会走`onCreate()`，`AssetsManager`会被重新初始化，建议你可以根据`Service`生命周期再排查下，如果是Demo有问题，麻烦你修复后提交一个PR，谢谢反馈。
