### ISSUE TITLE
2.0.1版本和Dev分支DeleteMapping报错

### ISSUE THREAD

**Issue by nuoyan2** [yanzhenjie/AndServer#127]
感谢严大佬的分享
使用Delete请求http数据
接收方法
    @DeleteMapping("/sk/user/{id}")
    String Delete(@PathVariable("id") int  id) throws IOException {
        Log.d(TAG, "RemovePersonnel: id ="+id);
        return "收到";
    }
2.0.1版本报异常：org.apache.httpcore.message.BasicHttpRequest cannot be cast to org.apache.httpcore.HttpEntityEnclosingRequest

我看到严大佬在2.0.2版本显示解决了此bug
于是我就下载Dev分支的代码进行测试
收到的异常也是：
{
    "errorCode": 500,
    "errorMsg": "org.apache.httpcore.message.BasicHttpRequest cannot be cast to org.apache.httpcore.HttpEntityEnclosingRequest",
    "isSuccess": false
}

是不是我使用的方法有问题 请严大佬指教

**Comment by yanzhenjie** [comment]
经测试，dev分支的没有问题。

**Comment by yanzhenjie** [comment]
我用dev分支的代码测试后未发现问题。

**Comment by nuoyan2** [comment]
严大佬 是否能提供下测试代码 delete方法 感谢@严振杰

**Comment by yanzhenjie** [comment]
就是用你提供的代码。

**Comment by nuoyan2** [comment]
@yanzhenjie 严大佬 我这边真的报类型转换异常   我这边可以提供截图和TeamView远程 您可以看下我给您邮箱发的截图

**Comment by yanzhenjie** [comment]
现在要发布新版了，我猜测是你本地代码可能有点问题，我和你邮件沟通。

**Comment by nuoyan2** [comment]
dev的代码是下载您的代码 只是在您的TestController类中增加了一个delete方法 post get都没有问题

**Comment by nuoyan2** [comment]
感谢严大佬的指点 修正方法 把app的build.gradle 的  dependencies方法中 implementation rootProject.ext.dependencies.andserverApi 注释掉 另加    implementation project(':api')
