### ISSUE TITLE
网络无线连接关闭再重启后无法访问

### ISSUE THREAD

**Issue by zhpengbj** [yanzhenjie/AndServer#128]
用的1.1.4版本
DEMO跑起来正常，但在测试网络不稳定时，出现了2个问题。
1.当安卓设备的无线关掉，在重开连接上原有wifi热点
2.当安卓设备连接的wifi热点关闭，在重开后，设备重新连接原有wifi热点后
则访问不了。

DEMO上可以用“停止服务器”后，再“启动服务器”来解决问题。我的app则可以定时重启服务来解决这样的问题。

但是想问一下，除了上面的方法，还有没有更好的解决办法。

**Comment by yanzhenjie** [comment]
必须在同一个网段内，要不是局域网，要不是外网，只要断网肯定再更换肯定要重启，因为中途的IP已经没了，监听就断开了，任何服务器都需要重启的。

**Comment by zjianflys** [comment]
我也遇到相同的问题,wifi断开需要重启服务才行,IP 没有发生变化

**Comment by always025** [comment]
我也遇到相同的问题,网络i断开需要重启服务才行,设置的静态ip，IP 没有发生变化

**Comment by HelloTodayWolrd** [comment]
我也遇到同样的问题

**Comment by yanzhenjie** [comment]
监听网络，网络发生变化时重启服务器。
