### ISSUE TITLE
support mutable storage dir deployment?

### ISSUE THREAD

**Issue by ddyos** [yanzhenjie/AndServer#130]
Hi,
For some reason, static website files(include html, js....) are download from remote server in run time. 
And there are maybe several different website. The root dir for website is not sure and not the same between coding time.
Is there a way to set/change the root dir for StorageWebsite in run time if use version 2.x.x?

**Comment by yanzhenjie** [comment]
The root directory must be known, you can create subdirectories in the root directory and download the files to a subdirectory.

**Comment by ddyos** [comment]
Thank you.
I try your answer, but meet some problem.
A sample include static website files(such as .js, .html, .json...), the files locate in ".../rootdir/sample1/".
If set the root directory to ".../rootdir/sample1/", and browse "http://x.x.x.x:8080/index.html", It work fine.

But, if set the root directory to ".../rootdir/", and browse “http://x.x.x.x:8080/sample1/index.html”. The "index.html" 
is loaded, but some javascript function run into error, may be because the javascript code use relative path to read a ".json" file. I can not edit the static website files, there supply by others.
How to fix that?

**Comment by yanzhenjie** [comment]
I put the file in the secondary directory in the assert and found no problem. You can debug the web page and find out the specific cause of the problem.
