### ISSUE TITLE
2.0.1 支持附件下载吗

### ISSUE THREAD

**Issue by Goofy911** [yanzhenjie/AndServer#131]
想实现附件下载，没有案例。下载文件内容为空。
 
 

        response.addHeader("Content-Disposition", "attachment;filename=" + DeviceUtils.getMac() + ".key");
        response.setHeader("content-Type", MediaType.APPLICATION_OCTET_STREAM_VALUE);

**Comment by yanzhenjie** [comment]
返回文件就可以。

**Comment by Goofy911** [comment]
按照你给的说明，返回文件类型，
   public File downLoadAuthorizeFile(HttpRequest request, HttpResponse response) 
但是跟踪发现最终都指向框架ViewResolver 的resolveRest 方法以下分支代码，被转为string类型，下载的文件无法正常打开。请问有什么特殊要求吗

   response.setBody(new StringBody(output.toString()));

**Comment by yanzhenjie** [comment]
FileBody，或者使用Converter.

**Comment by Goofy911** [comment]
非常感谢您的支持，目前用FileBody读取本地文件下载可以了，现在又一个问题，我从摄像头获取图片二进制流，每一次下载都要保持本地文件，然后读取返回FileBody才能下载，我看到您写的有一个StreamBody，我直接用InputStream inputStream=new ByteArrayInputStream(devCode.getBytes())； StreamBody streamBody=new StreamBody(inputStream);  return streamBody; 想实现直接下载数据，但是下载的文件为空，请问这个问题怎么解决。 因为我们业务用到需要输出二进制数据下载，比如poi导出excel也是二进制流数据
