### ISSUE TITLE
get参数解析错误

### ISSUE THREAD

**Issue by f111fei** [yanzhenjie/AndServer#134]
例如
get请求中有一个data参数值为{"a":"="}

请求
http://127.0.0.1/example?data=%7B"a"%3A"%3D"%7D

使用参数注解 @RequestParam("data") String data

调试得到这个请求的参数
key为 data={"a":"
value为 "}

这显然是不对的。

也就是如果请求参数的值中含有=这个字符串，解析会失败。

**Comment by f111fei** [comment]
关于参数解析的问题，这个是老问题了，之前1.x版本提供的HttpRequestParser这个类提供的方法获取含有特殊字符字段的参数也是错误的，这次升级到2.0本来以为解决了这个问题的。

**Comment by f111fei** [comment]
```
import android.net.Uri;

Uri uri = Uri.parse("http://127.0.0.1/example?data=%7B%22a%22%3A%22%3D%22%7D");
String data = uri.getQueryParameter("data");
```

参数解析为什么不使用安卓自带的Uri类？这个应该是可以的

**Comment by yanzhenjie** [comment]
这个框架不是专门给Android写的，只是目前针对Android写了初始化和Website，其他Api都是Java的。你反馈的问题我中午验证一下。

**Comment by yanzhenjie** [comment]
确实存在这个问题，我已经链接到 #145 了，请跟踪这个issue。
