### ISSUE TITLE
请问一下通过registerHandler注册的自定义handler，内核都是用一个独立的线程来处理的么？

### ISSUE THREAD

**Issue by tony8110** [yanzhenjie/AndServer#138]

**Comment by yanzhenjie** [comment]
无论在哪个项目，下次提问，应该在描述中提供当前你使用项目的详情，例如版本，相关代码，复现步骤。
根据你的描述，应该是1.x的版本，注册不是一个独立的线程，但是该handler被调用时，也就是当客户端请求该handler对应http api时，是启动一个独立线程来处理的。
