### ISSUE TITLE
AssetsWrapper类里面的getInputStream一直返回是null....

### ISSUE THREAD

**Issue by cool-delete** [yanzhenjie/AndServer#14]
![Uploading AFBN}C2@2{HTQXB[LR]3%SO.png…]()
关于asset层级就是这样的 debug的时候 发现AssetsWrapper里面的scanFile方法会不断循环 由于getInputStream一直返回null吧 debug的时候我修改了getInputStream的文件名参数 改成index.html后就不会无限循环了 读取了14个循环后结束 不过浏览器看也是不正常的
![Uploading Y81XZZ{GY5IONZ%MB(LAIET.png…]()

**Comment by yanzhenjie** [comment]
图片看不到。循环的时候只会循环文件夹，是循环查询里面的文件，你把图片贴出来再描述一下我再看看。
