### ISSUE TITLE
AndServer能用来http请求别的服务器？

### ISSUE THREAD

**Issue by QDreamcoding** [yanzhenjie/AndServer#141]
Android设备用AndServer达到服务器效果，能否用AndServer的api能用来请求别的服务器，是http请求的？

**Comment by yanzhenjie** [comment]
请求其他的Http Api和AndServer无关，但是你要是请求AndServer自身的Http Api则可以使用forward或者redirect进行转发。
请求其他Http Api只要使用Java的Api的都可以，例如URLConnection。除了Java自带的Http框架外，还可以使用基于Socket封装的三方框架，例如OkHttp、ApacheHttpClient等。
