### ISSUE TITLE
新版本2.0.2 StorageWebsite怎么配置？

### ISSUE THREAD

**Issue by gejian311** [yanzhenjie/AndServer#143]
旧版本采用.website配置
AndServer andServer = new AndServer.Build()
    ...
    .website(wesite);
    .build();
但是新版本中没有这个方法了，请问怎么配置呢？

**Comment by yanzhenjie** [comment]
看文档。

**Comment by gejian311** [comment]
知道了  新建个类继承StorageWebsite，放在里面，不用配置了
