### ISSUE TITLE
http to https redirect

### ISSUE THREAD

**Issue by AntonGG** [yanzhenjie/AndServer#146]
Hi. I'm using SSL sert and HTTPS connect.
When I write an ip:port without "https", it returns an error connect. 
How to make HTTP to HTTPS redirect?

**Comment by yanzhenjie** [comment]
You need to set `SSLContext` when creating the server, which is a necessary condition for the https handshake, like this:
```java
AndServer.serverBuilder()
   .sslContext(...)
    ...
```

**Comment by AntonGG** [comment]
https works fine.
but if i connect to http://, no forwarding to https://

**Comment by yanzhenjie** [comment]
Because many servers can support both http and https, AndServer does not currently have automatic redirects. You can use an interceptor to redirect all http requests to https. Like this:
```java
@Interceptor
public class RedirectInteceptor implements HandlerInterceptor {
   ...
}
```

**Comment by AntonGG** [comment]
I'm tried, but not connect with http
curl: (56) Recv failure: Connection reset by peer

**Comment by yanzhenjie** [comment]
Could you show the key code of the interceptor?

**Comment by AntonGG** [comment]
`package com.microimpuls.redbox_provisioning_client.api;

import android.support.annotation.NonNull;

import com.alibaba.fastjson.JSON;
import com.microimpuls.redbox_provisioning_client.App;
import com.microimpuls.redbox_provisioning_client.database.AppDatabase;
import com.microimpuls.redbox_provisioning_client.models.AuthKey;
import com.microimpuls.redbox_provisioning_client.models.ResponseError;
import com.yanzhenjie.andserver.annotation.Interceptor;
import com.yanzhenjie.andserver.error.BasicException;
import com.yanzhenjie.andserver.framework.HandlerInterceptor;
import com.yanzhenjie.andserver.framework.handler.MethodHandler;
import com.yanzhenjie.andserver.framework.handler.RequestHandler;
import com.yanzhenjie.andserver.http.HttpRequest;
import com.yanzhenjie.andserver.http.HttpResponse;
import com.yanzhenjie.andserver.mapping.Addition;

import java.util.List;

@Interceptor
public class AuthValidator implements HandlerInterceptor {

    @Override
    public boolean onIntercept(@NonNull HttpRequest request,
                               @NonNull HttpResponse response,
                               @NonNull RequestHandler handler) {
        response.addHeader("Access-Control-Allow-Origin", "*");

        if (handler instanceof MethodHandler) {
            MethodHandler methodHandler = (MethodHandler) handler;
            Addition addition = methodHandler.getAddition();
            if (addition.getStringType() != null &&
                    addition.getStringType()[0]
                            .equalsIgnoreCase("login")) {
                if (!isLogin(request)) {
                    throw new BasicException(403,
                            JSON.toJSONString(
                                    new ResponseError(403,
                                            "You are not logged in yet.")));
                }
            }
        }
        return false;
    }

    private boolean isLogin(HttpRequest request) {
        String token = request.getCookieValue("token");
        List<AuthKey> authKey =
                AppDatabase.getDatabase(App.getInstance()).authKeysDao().getAll();
        if (token != null && !authKey.isEmpty()) {
            return token.equals(authKey.get(0).getAuthKey());
        }
        return false;
    }

}
`

**Comment by AntonGG** [comment]
`
package com.microimpuls.redbox_provisioning_client.api;

import android.support.annotation.NonNull;

import com.alibaba.fastjson.JSON;
import com.microimpuls.redbox_provisioning_client.App;
import com.microimpuls.redbox_provisioning_client.database.AppDatabase;
import com.microimpuls.redbox_provisioning_client.models.AuthKey;
import com.microimpuls.redbox_provisioning_client.models.ResponseError;
import com.yanzhenjie.andserver.annotation.Interceptor;
import com.yanzhenjie.andserver.error.BasicException;
import com.yanzhenjie.andserver.framework.HandlerInterceptor;
import com.yanzhenjie.andserver.framework.handler.MethodHandler;
import com.yanzhenjie.andserver.framework.handler.RequestHandler;
import com.yanzhenjie.andserver.http.HttpRequest;
import com.yanzhenjie.andserver.http.HttpResponse;
import com.yanzhenjie.andserver.mapping.Addition;

import java.util.List;

@Interceptor
public class AuthValidator implements HandlerInterceptor {

    @Override
    public boolean onIntercept(@NonNull HttpRequest request,
                               @NonNull HttpResponse response,
                               @NonNull RequestHandler handler) {
        response.addHeader("Access-Control-Allow-Origin", "*");

        if (handler instanceof MethodHandler) {
            MethodHandler methodHandler = (MethodHandler) handler;
            Addition addition = methodHandler.getAddition();
            if (addition.getStringType() != null &&
                    addition.getStringType()[0]
                            .equalsIgnoreCase("login")) {
                if (!isLogin(request)) {
                    throw new BasicException(403,
                            JSON.toJSONString(
                                    new ResponseError(403,
                                            "You are not logged in yet.")));
                }
            }
        }
        return false;
    }

    private boolean isLogin(HttpRequest request) {
        String token = request.getCookieValue("token");
        List<AuthKey> authKey =
                AppDatabase.getDatabase(App.getInstance()).authKeysDao().getAll();
        if (token != null && !authKey.isEmpty()) {
            return token.equals(authKey.get(0).getAuthKey());
        }
        return false;
    }

}


`

**Comment by yanzhenjie** [comment]
Sorry, I have a little doubt.
Do you want to redirect http to https, or do you want to block the login status of the client?

The interceptor should be called, is there any error?

**Comment by AntonGG** [comment]
I want to redirect http to https. 
now HTTP doesnt work, only HTTPS work
i'm using sslContext, he block http protocol

**Comment by yanzhenjie** [comment]
This may be a problem with AndServer, I will test and try to make it stronger. But it will take a while, you should use https first, wait for my new news.

**Comment by AntonGG** [comment]
May be need to change settings "org.apache.httpcore" ?

**Comment by yanzhenjie** [comment]
Sorry, I got a wrong idea yesterday, http and https have to listen to different ports, so you have to start two servers, one to support http and one to support https.
