### ISSUE TITLE
control 没有编译相应的代码

### ISSUE THREAD

**Issue by 1321365765** [yanzhenjie/AndServer#147]
添加了注解没有生成使用的代码是为什么

**Comment by yanzhenjie** [comment]
According to the documentation, add dependencies to the project module, add annotations to the components, and run [Make project].

**Comment by 1321365765** [comment]
apply plugin: 'com.android.application'
apply plugin: 'org.greenrobot.greendao'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-android'
android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.iotimc.cafe"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        renderscriptTargetApi 19 //设置目标的版本
        renderscriptSupportModeEnabled true //启用兼容模式
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [moduleName: project.getName()]
            }
        }
    }
    signingConfigs {
        releaseConfig {
            keyAlias 'keystore'
            keyPassword 'keystore'
            storeFile file('D:/key/keystore.jks')
            storePassword 'keystore'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
            signingConfig signingConfigs.releaseConfig
        }

        debug {
            //   resValue("string", "PORT_NUMBER", "8081")
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
            signingConfig signingConfigs.releaseConfig
        }
    }
    dataBinding {
        enabled = true
    }
    kapt {
        generateStubs = true
//        arguments {
//            arg("AROUTER_MODULE_NAME", project.getName())
//        }
    }
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.yanzhenjie.andserver:api:2.0.3'
    annotationProcessor 'com.yanzhenjie.andserver:processor:2.0.3'
    implementation 'org.greenrobot:greendao:3.2.2'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.github.yuweiguocn:GreenDaoUpgradeHelper:v2.0.2'
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:recyclerview-v7:28.0.0'
    // Architecture Components
    api "android.arch.lifecycle:extensions:$archLifecycleVersion"
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.android.support:support-v4:28.0.0'
    annotationProcessor "android.arch.lifecycle:compiler:$archLifecycleVersion"
    compile project(':openCVLibrary320')
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    compile 'com.nineoldandroids:library:2.4.0'
    compile 'com.daimajia.slider:library:1.1.5@aar'
    implementation project(':fingeradapter')
    implementation project(':NetworkLibrary')
    implementation project(':serialport')

}

greendao {
    schemaVersion 1
    daoPackage 'com.iotimc.cafe.dao'
    targetGenDir 'src/main/java'
}


repositories {
    mavenCentral()
}

**Comment by 1321365765** [comment]
// Top-level build file where you can add configuration options common to all sub-projects/modules.
ext {
    compileSdkVersion = 27
    buildToolsVersion = '27.0.3'
    supportLibraryVersion = "27.1.1"
    rxAndroid = '2.0.1'
    rxJava = '2.1.9'
    // Architecture Components dependencies
    roomVersion = "1.0.0"
    archLifecycleVersion = "1.1.1"

}
buildscript {
    ext.kotlin_version = '1.2.71'
    repositories {
        jcenter {
            url "http://jcenter.bintray.com"
        }
        maven { url 'https://maven.google.com' }
        maven { url "https://jitpack.io" }
        maven {
            url  'http://dl.bintray.com/gigamole/maven/'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'org.greenrobot:greendao-gradle-plugin:3.2.2'
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.7.3'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:2.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter {
            url "http://jcenter.bintray.com"
        }
        maven { url 'https://maven.google.com' }
        maven { url "https://jitpack.io" }
        maven {
            url  'http://dl.bintray.com/gigamole/maven/'
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by 1321365765** [comment]
还是不行

**Comment by yanzhenjie** [comment]
You can check if any errors have occurred, or refer to the demo.

**Comment by 1321365765** [comment]
Is it incompatible with Kotlin  kotlin-kapt

**Comment by 1321365765** [comment]
can you try it?
apply plugin: 'kotlin-kapt'
org.jetbrains.kotlin:kotlin-gradle-plugin

**Comment by yanzhenjie** [comment]
Since the new version of Gradle has changed some behaviors internally, it caused this problem during compilation. At present, I have released a new version of v2.0.4 that is compatible with this problem.

**Comment by yanzhenjie** [comment]
Oh, I am sorry that I have not helped you. You can try the latest version: 2.0.4.
