### ISSUE TITLE
使用StorageWebsite的问题

### ISSUE THREAD

**Issue by zk0301** [yanzhenjie/AndServer#15]
使用storagewebsite映射目录 /mnt/sdcard/www之后，
访问http://127.0.0.1:8080/test.mp4 一直得不到文件，打断点才发现，应该是
http://127.0.0.1:8080/mnt/sdcard/www/test.mp4

不方便理解。既然已经映射了该目录，访问的时候就应该不用写完整路径。

**Comment by yanzhenjie** [comment]
方便把你的代码贴出来一下吗？

**Comment by zk0301** [comment]
也没什么大问题，就是觉得访问的时候需要写全路径，觉得不方便。
服务端：   .website(new StorageWebsite("/mnt/sdcard/www"))

客户端：  // String url = "http://127.0.0.1:8080/video/test0.mp4";                            //error
                String url = "http://127.0.0.1:8080/mnt/sdcard/www/video/test0.mp4";    //right
                videoView.setVideoURI(Uri.parse(url));
                videoView.setMediaController(new MediaController(MainActivity.this));
                videoView.start();

**Comment by yanzhenjie** [comment]
如果你描述的问题是确实存在的话，那的确是个问题，我将尽快优化，感谢反馈。

**Comment by yanzhenjie** [comment]
我刚才升级AndServer的时候发现，这个是没有问题的，默认提供的Website是`AssetsWebsite`和`StorageWebsite`，它们设计的初衷就是针对Assets或者Storeage，所以他们的根目录必须要跟上，如果你觉得这个暴露了安全性的话，你可以自己实现`Website`接口重写一个类然后注册网站即可，具体实现就一个方法，很简单的几行代码，可以参考`AssetsWebsite`和`StorageWebsite`，非常感谢你的反馈。

**Comment by ag2s20150909** [comment]
能给个例子吗。。。

**Comment by xwy55555** [comment]
我也碰到同样的问题，作者在为什么在StoreageWebsite中解决这个问题呢？明显指定root目录会更合理一些。@yanzhenjie

**Comment by ag2s20150909** [comment]
``

import android.text.TextUtils;

import com.yanzhenjie.andserver.RequestHandler;
import com.yanzhenjie.andserver.handler.StorageRequestHandler;
import com.yanzhenjie.andserver.util.StorageWrapper;

import java.io.File;
import java.util.List;
import java.util.Map;

/**
 * <p>The web site in storage.</p>
 * Created by Yan Zhenjie on 2017/3/15.
 */

public class NewStorageWebsite extends BasicWebsite {

    /**
     * StorageWrapper.
     */
    private StorageWrapper mStorageWrapper;

    /**
     * Site root directory.
     */
    private String mRootPath;

    /**
     * Storage Website.
     *
     * @param rootPath site root directory in assets, such as: {@code "/storage/sdcard/google/website"}.
     */
    public NewStorageWebsite(String rootPath) {
        super(rootPath);
        if (TextUtils.isEmpty(rootPath)) throw new NullPointerException("The RootPath can not be null.");
        this.mRootPath = trimSlash(rootPath);
        mStorageWrapper = new StorageWrapper();
    }

    @Override
    public void onRegister(Map<String, RequestHandler> handlerMap) {
        RequestHandler indexHandler = new StorageRequestHandler(INDEX_HTML);
        handlerMap.put("", indexHandler);
        handlerMap.put(mRootPath, indexHandler);
        handlerMap.put(mRootPath + File.separator, indexHandler);
        handlerMap.put(mRootPath + File.separator + INDEX_HTML, indexHandler);

        List<String> pathList = mStorageWrapper.scanFile(getHttpPath(mRootPath));
        for (String path : pathList) {
            RequestHandler requestHandler = new StorageRequestHandler(path);
			 path=path.substring(path.indexOf(mRootPath)+mRootPath.length(),path.length());
            handlerMap.put(path, requestHandler);
        }
    }

}

**Comment by xwy55555** [comment]
谢谢 @ag2s20150909 ，这样确实可行

**Comment by Sogrey** [comment]
我也遇到这问题，感谢 @ag2s20150909 ，严大，该更新 StorageWebsite 了

**Comment by OnlyYouMyLove** [comment]
使用StorageWebsite的时候，HTML是这样的http://172.12.123.23:8000/www/1/2/a/index.html，使用NewStorageWebsite之后，HTML是这样的http://172.12.123.23:8000/index.html，而且可以接收到SD下的存储路径下的视频文件的信息，但是使用StorageWebsite，视频可以正常下载，使用NewStorageWebsite无法正常下载。@yanzhenjie 
String path = SD卡的目录;
AndServer andServer = new AndServer.Build()
.port(8080)
.timeout(10 * 1000)
.registerHandler("login", new RequestLoginHandler(mData))
.website(new NewStorageWebsite(path))
.build();
mServer = andServer.createServer(); 

网站的信息，我在assets下有，而且copy到了sd卡，可以使用StorageWebsite，并且使用http://172.12.123.23:8000/www/1/2/a/index.html访问到SD卡里面的视频文件，下载也正常，但是访问index.html的地址太长了！想缩短，用了NewStorageWebsite，但是不能让sd下的视频正常下载，求解，非常感谢！

我的微信fkq339 随时可以联系我。 @ag2s20150909

**Comment by yanzhenjie** [comment]
大家可以看看新版本，新版内部修改了注册方式，不存在这个问题了。新版特性：网站热插拔、文件浏览器、支持Http缓存、拦截器、过滤器等等。而且文档相对也完善了一些：[http://yanzhenjie.github.io/AndServer](http://yanzhenjie.github.io/AndServer)
