### ISSUE TITLE
The resource is not found

### ISSUE THREAD

**Issue by Reginer** [yanzhenjie/AndServer#150]
运行demo提示这个，demo里的每个接口也都提示这个。

**Comment by yanzhenjie** [comment]
浏览器请求icon，看log。

**Comment by Reginer** [comment]
请求icon? 这框架在所有手机上都能用么？把demo生成的apk装到我两个华为手机都提示这个。一个7.0系统，一个9.0系统

**Comment by yanzhenjie** [comment]
Does the demo not work for you?

**Comment by Reginer** [comment]
I can make APK for demo .But the browser prompt is “The resource [/] is not found” .It's really sad.
as 3.5.

**Comment by yanzhenjie** [comment]
If you haven't modified any code, then this is a strange phenomenon, I can't reproduce it here, and no one has reported it.

**Comment by yanzhenjie** [comment]
I found the problem, please wait a moment.

**Comment by Reginer** [comment]
![image](https://user-images.githubusercontent.com/12568257/51649065-e56e4580-1fbd-11e9-88aa-da6116890b4e.png)

**Comment by yanzhenjie** [comment]
Since the new version of Gradle has changed some behaviors internally, it caused this problem during compilation. At present, I have released a new version of v2.0.4 that is compatible with this problem.

**Comment by Coding4Me** [comment]
@yanzhenjie  The browser prompt is “The resource [/] is not found” Once in a while

**Comment by wbr0603** [comment]
me too
