### ISSUE TITLE
如何给静态资源，如HTML、CSS等设置拦截器？

### ISSUE THREAD

**Issue by zhongshuiyuan** [yanzhenjie/AndServer#154]

**Comment by yanzhenjie** [comment]
在SpringMVC中是通过请求资源的后缀的认定是请求的静态资源，你可以添加一个拦截器，通过request的url来判断请求的资源是什么。

**Comment by zhongshuiyuan** [comment]
尝试了在 onIntercept里判断后缀，但静态资源进入拦截器不稳定，经常会跳过拦截器。
public boolean onIntercept(HttpRequest request, HttpResponse response, RequestHandler handler) {
        if(request.getURI().toLowerCase().endsWith(".html")){
            if(!isLogin(request)){
                Map info = new HashMap();
                info.put("success", false);
                info.put("msg", "您尚未登录。");
                throw new BasicException(401, JsonUtils.toJsonString(info));
            }
        }
        if (handler instanceof MethodHandler) {
            MethodHandler methodHandler = (MethodHandler)handler;
            Addition addition = methodHandler.getAddition();
            if (!isLogin(request, addition)) {
                Map info = new HashMap();
                info.put("success", false);
                info.put("msg", "您尚未登录。");
                throw new BasicException(401, JsonUtils.toJsonString(info));
            }
        }
        return false;
    }
