### ISSUE TITLE
多级包导致无法makeproject

### ISSUE THREAD

**Issue by watchmon** [yanzhenjie/AndServer#155]
在用到三级包的时候 类名和包名一样的时候 导致makeproject失败
![image](https://user-images.githubusercontent.com/1973283/53082936-df29a580-3538-11e9-81e2-b90b57c8b717.png)

**Comment by yanzhenjie** [comment]
你好，麻烦说具体点，三级包和错误分别是什么，能提供的信息尽量都提供。

**Comment by watchmon** [comment]
![image](https://user-images.githubusercontent.com/1973283/53091314-9aa80500-354c-11e9-9ec4-91146ec3e477.png)
如上图这种包命名的时候就无法makepoject，错误见下图
![image](https://user-images.githubusercontent.com/1973283/53091380-c4612c00-354c-11e9-89b9-ea66fe6dd829.png)
把包名改为小写后就可以makeproject了，如下图
![image](https://user-images.githubusercontent.com/1973283/53091443-e9559f00-354c-11e9-83e2-b9530925420c.png)

**Comment by yanzhenjie** [comment]
import com.xx.yy.ABC.ABC;
