### ISSUE TITLE
应用内发送广播

### ISSUE THREAD

**Issue by Reginer** [yanzhenjie/AndServer#157]
应用内发送的广播可否使用LocalBroadcast来操作 。
我的应用是system级别的，不能发送未在系统内定义的广播。所以AndServer内所有发送出去的广播全都报错了，也收不到。
这个问题是8.0之后增加的省电机制。

只需要用本地广播发送就可以了，同时可以提升性能 。

**Comment by yanzhenjie** [comment]
AndServer里面没有这个机制，广播只是sample为了实现`Activity`和`Service`的通信用的，你改成你自己的通信方式即可。
