### ISSUE TITLE
发送一次数据，接收端无限接收

### ISSUE THREAD

**Issue by Reginer** [yanzhenjie/AndServer#158]
![image](https://user-images.githubusercontent.com/12568257/53157089-c1714480-35fb-11e9-8602-a9a583b26533.png)

![image](https://user-images.githubusercontent.com/12568257/53157059-ac94b100-35fb-11e9-8470-21a46bcdadf8.png)

**Comment by yanzhenjie** [comment]
不会呀，你先拿sample做下测试。

**Comment by Reginer** [comment]
看起来问题就是  #128 和 #57 的合体。
网络断开之后调用关闭服务，又连上了，调用启动。网络状态切换几次看起来服务就启动了几次。

**Comment by yanzhenjie** [comment]
你可能没有关闭之前的服务器。

**Comment by Reginer** [comment]
已经调用了shutdown，然而服务器它不关 。。。
严大佬加油 ！我先测这么多吧  /小纠结

**Comment by yanzhenjie** [comment]
你先拿sample测试，sample我这边没有出现你们说的问题。

**Comment by Reginer** [comment]
sample你得增加切网络环境才好测，而且其实 #128 我觉得也不应该是切完网络ip没变就访问不了才对。
现实服务器把网线拔了再插上一样可以访问 。严大觉得呢

**Comment by yanzhenjie** [comment]
前几天我有个同学因为AndServer切网问题找过我，他那边是因为关闭服务器问题，后来修改了逻辑就好了。

你要是监听`127.0.0.1`也可以呀，另外57中提到的关闭服务器，他没有仔细看demo，关闭服务器是异步的，需要等待回调，才可以进行下一步，很多人都忽略了这个。所有服务器启动和关闭都是需要时间的，包括unix系统和windows系统中。

**Comment by Reginer** [comment]
做的是手机克隆功能。就是网上流传的那个闪电换机应用。用这个库实现真简单。不过有时候遇到一些问题，我是理解不了的。比如其实我不是很理解，为什么服务器启动服务还要把自己的ip传进去。不过我很看好这个库，希望严大以后可以一直维护。

**Comment by yanzhenjie** [comment]
因为一个服务器可能有几个ip呀，不然就默认监听127.0.0.1了。

**Comment by Reginer** [comment]
为什么不是设置端口呢？只要监听127.0.0.1就可以了吧。局域网内访问，就访问它的ip不就好了么

**Comment by yanzhenjie** [comment]
端口是必须要设置的呀，如果你的设备有外网ip，可以解析域名，所以可以设置要监听哪个ip。另外AndServer其实是个Java项目，只是现在启动时支持了Android，它的内部没有使用Android的Api，都是用JavaSE的Api来写的。

**Comment by Reginer** [comment]
看来我得看下大佬的代码

**Comment by Reginer** [comment]
根据大佬的建议试了一下127.0.0.1。
自己是可以访问，但是局域网下的其他设备输入服务器的ip就访问不了它了。

**Comment by yanzhenjie** [comment]
这个问题我单独跟个issue吧，还是 #128 ，后续的更新，我会记录在 #128 下。

**Comment by Reginer** [comment]
棒
