### ISSUE TITLE
WebsiteRegister之后报exception

### ISSUE THREAD

**Issue by anyfar** [yanzhenjie/AndServer#162]
WebsiteRegister之后报exception
![image](https://user-images.githubusercontent.com/16009101/54417080-1f490600-473c-11e9-9781-64e53682cb5b.png)
好像不影响使用，但还是希望能够找到问题，这个异常有可能是什么导致的呢？我把例子中的一部分代码拿过来，是丢失了文件吗？
用到的文件 ServerManager CoreService NetUtils InternalWebsite 其他未用。

**Comment by yanzhenjie** [comment]
I can't judge accurately. I preliminarily concluded that an exception occurred while loading the component. You can run the sample to see if this problem occurs.

**Comment by yanzhenjie** [comment]
This may be just a warning, probably due to the modification of the .dex file.
