### ISSUE TITLE
how to get the instance of the service in pageController

### ISSUE THREAD

**Issue by lh-ycx** [yanzhenjie/AndServer#163]
I want to broadcast an intent when I receive an HTTP request. Question is that when I'm trying to send the service instance to the pageController by the way of the parameter, it seems that the code automatically generated by AndServer doesn't allow this kind of things, like what is shown in the picture. So I want to ask how to get the service's instance? I'm an Android learner, so could you please tell me in a more detailed way? Thanks a lot!
![91552653086_ pic](https://user-images.githubusercontent.com/31273574/54431916-a3ae7f80-4762-11e9-9e05-7db20e49a0af.jpg)
![121552653152_ pic_hd](https://user-images.githubusercontent.com/31273574/54431918-a610d980-4762-11e9-97c0-56ec74154b68.jpg)

**Comment by yanzhenjie** [comment]
Cloud you tried this way?
```java
@RestController
public class PageController {
    private CoreService mService;

    public PageController() {
        mService = new CoreService();
    }
}
```

**Comment by tamashii** [comment]
Or could you make the CoreService a singleton class like this:
```class CoreService {
    private static CoreService INSTANCE;
    public static CoreService getInstance() {
        if (INSTANCE == null) {
            synchronized(CoreService.class) {
                if (INSTANCE == null)
                    INSTANCE = new CoreService();
                return INSTANCE;
            }
        }
        return INSTANCE;
    }
}```
