### ISSUE TITLE
使用ContentProvider获取context并不稳定

### ISSUE THREAD

**Issue by Reginer** [yanzhenjie/AndServer#165]
使用过程中，时常因为ContentProvider的context为null导致启动服务器异常，希望提供个初始化接口供外部调用。不再依赖ContentProvider
![image](https://user-images.githubusercontent.com/12568257/54733701-ff02c680-4bd5-11e9-9308-35bf74f804f9.png)

**Comment by yanzhenjie** [comment]
Trace #160. This is the same problem.
