### ISSUE TITLE
大佬，apk加固后用Postman访问，出现The resource [/sign] is not found，怎么办

### ISSUE THREAD

**Issue by BruceeTao** [yanzhenjie/AndServer#172]

**Comment by fengpeitian** [comment]
我也遇到这个问题了

**Comment by BruceeTao** [comment]
换专业的加固就好了，应该是加固工程有问题------------------ 原始邮件 ------------------
发件人: "冯裴添"<notifications@github.com>
发送时间: 2019年6月25日(星期二) 晚上7:33
收件人: "yanzhenjie/AndServer"<AndServer@noreply.github.com>;
抄送: "BruceeTao"<1539791115@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [yanzhenjie/AndServer] 大佬，apk加固后用Postman访问，出现The resource [/sign] is not found，怎么办 (#172)



我也遇到这个问题了
 
&mdash;
