### ISSUE TITLE
2.0.4版本出现编译错误enableSeparateAnnotationProcessing

### ISSUE THREAD

**Issue by xuyabin521** [yanzhenjie/AndServer#173]
> Task :app:compileDebugJavaWithJavac FAILED
Gradle may disable incremental compilation as the following annotation processors are not incremental: auto-service-1.0-rc4.jar (com.google.auto.service:auto-service:1.0-rc4).
Consider setting the experimental feature flag android.enableSeparateAnnotationProcessing=true in the gradle.properties file to run annotation processing in a separate task and make compilation incremental.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> javax/activation/MimeTypeParseException

**Comment by yanzhenjie** [comment]
This is just a warning, it does not affect the compilation, and the error is not caused by this project.
