### ISSUE TITLE
参数值有“=”时无法获取到参数值

### ISSUE THREAD

**Issue by zhongshuiyuan** [yanzhenjie/AndServer#175]
![1234561](https://user-images.githubusercontent.com/8955999/56027504-c2476c80-5d48-11e9-8b83-4cad947e5c1c.png)
![1234562](https://user-images.githubusercontent.com/8955999/56027512-c5daf380-5d48-11e9-8872-2d2cf33087dd.png)

**Comment by yanzhenjie** [comment]
The issue has been fixed in #145, which version are you using?

**Comment by zhongshuiyuan** [comment]
version 2.0.4

**Comment by LillteZheng** [comment]
这个问题在 2.1.3 版本同样存在，目前只能把代码copy 出来，自己改一下了
