### ISSUE TITLE
使用ajax异步提交表单数据时报Missing Param的错

### ISSUE THREAD

**Issue by Limbo141592** [yanzhenjie/AndServer#178]
```
 $.post({
                url:"/user/register",
                data:$("#form1").serialize(),
                success: function (result) {
                    if (result.code === 200) {
                        alert(result.msg);
                    }
                },
                error: function (result) {
                    alert(result.msg);
                }
            });
            return false; // 阻止表单提交
        });
```
然后
`W/System.err: com.yanzhenjie.andserver.error.ParamMissingException: Missing param [account] for method parameter.`

表单的各项都有name属性，控制器也是PostMapping，但是每次提交都会报这个错。如果单纯的用表单提交就不会报错。

### `_****_`

**Comment by yanzhenjie** [comment]
The controller requires parameters to be present, even if the value is empty.

Let this parameter be an optional parameter, just like doing this:  
```java
@RequestParam(name = "header", required = false)
```

**Comment by Limbo141592** [comment]
What I want are three parameters : account , password and checkPassword.  I want them to be present.But with the ajax.post, the controller can't get them,and the status code is 400. 

In Postman, with post method, this is can be true, I'm confused
`http://192.168.31.48:8080/user/register?account=123456&password=123456&checkPassword=123456`

If I set these parameters on headers, wrong again

**Comment by yanzhenjie** [comment]
Can't solve it by `required=false`?

**Comment by Limbo141592** [comment]
with this, I get this:
`I/System.out: 【account】：【password】：【checkPassword】：`
no result

**Comment by Limbo141592** [comment]
and, I used layui.form to build the page, is this posibility of the problem?

**Comment by yanzhenjie** [comment]
The cause of the problem should be the way the data is submitted, what is the result of `$("#form1").serialize()`?

**Comment by Limbo141592** [comment]
like this
`account=123456&password=123456&checkPassword=123456`

**Comment by yanzhenjie** [comment]
You can use Charles to intercept requests and check that the client submitted the data correctly.
