### ISSUE TITLE
使用StorageWebsite时HTML文件不能被加载

### ISSUE THREAD

**Issue by cn-huangzhou** [yanzhenjie/AndServer#18]
在使用StorageWebsite时，指定目录下的HTML文件并不能被加载出来需要
这样写http://ip:port/index.html不能被加载
必须这样：http://ip:port/mnt/sdcard/www/index.html

下面是代码：`WebSite wesite = new StorageWebsite("/mnt/sdcard/www");`

**Comment by ag2s20150909** [comment]
import android.text.TextUtils;

import com.yanzhenjie.andserver.RequestHandler;
import com.yanzhenjie.andserver.handler.StorageRequestHandler;
import com.yanzhenjie.andserver.util.StorageWrapper;

import java.io.File;
import java.util.List;
import java.util.Map;

/**
 * <p>The web site in storage.</p>
 * Created by Yan Zhenjie on 2017/3/15.
 */

public class NewStorageWebsite extends BasicWebsite {

    /**
     * StorageWrapper.
     */
    private StorageWrapper mStorageWrapper;

    /**
     * Site root directory.
     */
    private String mRootPath;

    /**
     * Storage Website.
     *
     * @param rootPath site root directory in assets, such as: {@code "/storage/sdcard/google/website"}.
     */
    public NewStorageWebsite(String rootPath) {
        super(rootPath);
        if (TextUtils.isEmpty(rootPath)) throw new NullPointerException("The RootPath can not be null.");
        this.mRootPath = trimSlash(rootPath);
        mStorageWrapper = new StorageWrapper();
    }

    @Override
    public void onRegister(Map<String, RequestHandler> handlerMap) {
        RequestHandler indexHandler = new StorageRequestHandler(INDEX_HTML);
        handlerMap.put("", indexHandler);
        handlerMap.put(mRootPath, indexHandler);
        handlerMap.put(mRootPath + File.separator, indexHandler);
        handlerMap.put(mRootPath + File.separator + INDEX_HTML, indexHandler);

        List<String> pathList = mStorageWrapper.scanFile(getHttpPath(mRootPath));
        for (String path : pathList) {
            RequestHandler requestHandler = new StorageRequestHandler(path);
			 path=path.substring(path.indexOf(mRootPath)+mRootPath.length(),path.length());
            handlerMap.put(path, requestHandler);
        }
    }

}

**Comment by yanzhenjie** [comment]
之前确实存在这个问题，使用 @ag2s20150909 的代码确实可以解决问题，再次特别感谢 @ag2s20150909 同学，在几个issue下帮助了别人。

现在发布了新版本，你可以试试新版本，新版特性：网站热插拔、文件浏览器、支持Http缓存、拦截器、过滤器等等。而且文档相对也完善了一些：[http://yanzhenjie.github.io/AndServer](http://yanzhenjie.github.io/AndServer)
