### ISSUE TITLE
android 4.1.2 无法使用.

### ISSUE THREAD

**Issue by ScannerSc** [yanzhenjie/AndServer#182]
同样的代码在8.0 5.0设备上没有问题，4.1.2启动不起来，startup之后没有任何反应，有关的输出如下：
I/AndServer: VM with version 1.6.0 does not have Multidex support.
I/AndServer: InstantRun support was not found.
I/AndServer: Loading com.yanzhenjie.andserver.register.AdapterRegister.
I/AndServer: Loading com.yanzhenjie.andserver.register.WebsiteRegister.

**Comment by yanzhenjie** [comment]
Add `Multidex` support and you're done. 

> Under this project, please try to communicate in English.
