### ISSUE TITLE
how to change or add response header

### ISSUE THREAD

**Issue by szsx12345** [yanzhenjie/AndServer#183]
In my project, I use annotation to build api, and it will auto generated a file. Now I want to use 
 -->  response.addHeader("Access-Control-Allow-Origin", "*")  to change the response header, but I don't know where should I insert this code, or there is another way to do this action?

**Comment by yanzhenjie** [comment]
ex.
```java
@PostMapping(path = "/login")
String login(..., HttpResponse response) {
    ...
    response.addHeader(...);
    response.setHeader(...);
}
```
