### ISSUE TITLE
收到请求直接弹出Toast，没有走写好的RestController

### ISSUE THREAD

**Issue by GodFan4** [yanzhenjie/AndServer#184]
有些请求是正常的，有一个请求直接弹出toast,    Y!{“code”:"1"}
前面都会多俩字符，怎么去手动处理这块

**Comment by yanzhenjie** [comment]
This should be your behavior, the framework only does things related to Http.

**Comment by GodFan4** [comment]
![1](https://user-images.githubusercontent.com/20738884/57978515-c6e6fb00-7a41-11e9-99dc-5999c8876c12.png)

请求没有走写好的方法，类似于直接抛出异常了

**Comment by yanzhenjie** [comment]
You should find out what went wrong.

> Please use English as much as possible.

**Comment by GodFan4** [comment]
The same method（getAndroid），other get requests is  normal，only  this one  is error

**Comment by yanzhenjie** [comment]
I still don't understand what the problem you are having.

**Comment by GodFan4** [comment]
I want to know before executing the RestController，Where will this toast appear about body?

**Comment by yanzhenjie** [comment]
This should be your behavior, the framework only does things related to Http. It has nothing to do with the Android platform, so it has nothing to do with View.
