### ISSUE TITLE
没调试日志开关吗

### ISSUE THREAD

**Issue by xiaobaiyey** [yanzhenjie/AndServer#186]
```java
    @GetMapping(value = "/encrypt", params = "str")
    public String encrypt(@RequestParam("str") String str) {
        Log.i(TAG, "encrypt: str" + str);
        String result = (String) ThirdDexHook.callMethod("encrypt", str);
        ResponseBody body = new StringBody(result);
        return body.toString();
    }
```
提示信息如下：
http://localhost:18126/encrypt?str=112312

> wrong number of arguments; expected 2, got 1

只给了提示信息，异常日志打印堆栈吗
找到原因了，代码错误，好像是没调试日志开关，我也不知道哪里错了，一行一样的找错误

**Comment by yanzhenjie** [comment]
When an exception occurs, the exception will not be printed, and ExceptionResolver will be called. If there is no ExceptionResolver, the exception message will be sent to the client.
