### ISSUE TITLE
The resource is not found !

### ISSUE THREAD

**Issue by Chensem** [yanzhenjie/AndServer#187]
## the code 
![image](https://user-images.githubusercontent.com/27469499/58319404-6ba37700-7e4c-11e9-8351-2fd5c45c3c71.png)
i want to get the String type return value , but it show me 
![image](https://user-images.githubusercontent.com/27469499/58319507-8675eb80-7e4c-11e9-9c47-36ab25c8cd66.png)
how can i solve it ?

**Comment by yanzhenjie** [comment]
`http://172.16.2.15:8080/user/info/123`
