### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by TBoyLi** [yanzhenjie/AndServer#188]
![image](https://user-images.githubusercontent.com/14815341/58688010-d78a6000-83b5-11e9-9212-56e3a263b09a.png)
如何解决跨域问题

**Comment by yanzhenjie** [comment]
1. Please check http api to support the request method
2. Add  response header `Access-Control-Allow-Origin`

**This is a question that has nothing to do with this project.**

> Please try to communicate in English as much as possible.

**Comment by TBoyLi** [comment]
@yanzhenjie like this?
![image](https://user-images.githubusercontent.com/14815341/58689116-bbd48900-83b8-11e9-94c4-b8bd4ca08e79.png)

**Comment by TBoyLi** [comment]
@yanzhenjie but it not work, same mistake

**Comment by monkey92** [comment]
use interceptor slove my problem 
![image](https://user-images.githubusercontent.com/9624576/144543502-f259b11d-1ec8-4b0a-a5cc-a993b0e85cc1.png)
