### ISSUE TITLE
请问使用Kotlin语言，使用kapt 'com.yanzhenjie.andserver:processor:2.0.4'无法自动生成注解的代码是怎么回事呢

### ISSUE THREAD

**Issue by zhanghengMX** [yanzhenjie/AndServer#189]

**Comment by yanzhenjie** [comment]
What is the specific performance? Did you view the code in the build directory?
> `./build/generated/source/apt/...`

----
> Please try to communicate in English as much as possible.

**Comment by zhanghengMX** [comment]
该目录下没有生成code

**Comment by zhoubianjing** [comment]
我也有同样的问题，用kapt加载不了整个processor module，导致所有注解类都失效了

**Comment by zhoubianjing** [comment]
已解决，clean+重启后 注解的代码又自动生成了。。。
