### ISSUE TITLE
如何把IP:Port改成一个网址呢。只在局域网使用

### ISSUE THREAD

**Issue by quan356270259** [yanzhenjie/AndServer#19]
比如IP地址是192.168.2.101，端口为8090. 怎样才能使用映射一个网址代替http://192.168.2.101:8090去访问。有没有解决方法？

**Comment by yanzhenjie** [comment]
和这个库无关了，一般我们给客户端机器配置host：
```
test.google.com   192.168.1.1
```
这个`192.168.1.1`就是运行`AndServer`的机子的ip。当然如果你在路由器做映射也可以。
