### ISSUE TITLE
请求返回值错误

### ISSUE THREAD

**Issue by zhanghengMX** [yanzhenjie/AndServer#190]
@Controller
public class SystemController {
    @GetMapping(path = "/system/login")
    public String login() {
        return "12345";
    }
}

请问这样写返回The resource [12345] is not found.是怎么回事呢，我是想作为API使用，

**Comment by yanzhenjie** [comment]
You should use `RestController` instead of `Controller`, please read the documentation carefully.

> Please try to communicate in English as much as possible.

**Comment by zhanghengMX** [comment]
抱歉，这个是我用错了，但是我使用了RestController任然存在此问题

![image](https://user-images.githubusercontent.com/21967161/59004655-fa50c480-884c-11e9-8be2-1751aa544bfd.png)

![image](https://user-images.githubusercontent.com/21967161/59004671-076db380-884d-11e9-97f2-01878927f59c.png)
