### ISSUE TITLE
接口返回值疑问

### ISSUE THREAD

**Issue by zhanghengMX** [yanzhenjie/AndServer#192]
抱歉，这个是我用错了，但是我使用了RestController任然存在此问题

![image](https://user-images.githubusercontent.com/21967161/59004655-fa50c480-884c-11e9-8be2-1751aa544bfd.png)

![image](https://user-images.githubusercontent.com/21967161/59004671-076db380-884d-11e9-97f2-01878927f59c.png)

_Originally posted by @zhanghengMX in https://github.com/yanzhenjie/AndServer/issues/190#issuecomment-499333168_

添加ResponseBody注解后返回正常
![image](https://user-images.githubusercontent.com/21967161/59004936-16a13100-884e-11e9-9553-1a59e9c06094.png)

**Comment by flowerandheart** [comment]
可以看一下restcontroller的实现..

**Comment by flowerandheart** [comment]
RestController和Controller的源码好像没啥区别啊

**Comment by flowerandheart** [comment]
> RestController和Controller的源码好像没啥区别啊

@yanzhenjie 大佬可以解答一下么，使用了RestController之后还是要配合使用@ResponseBody么？

**Comment by yanzhenjie** [comment]
This is a bug, please follow up #196 .
