### ISSUE TITLE
使用@RequestBody注解，无法获取到参数，客户端请求报RequestBody is Missing

### ISSUE THREAD

**Issue by gdongxie** [yanzhenjie/AndServer#194]
@PostMapping(path = "/pushUser")
    public void pushUser(@RequestBody User user) {
        Log.d("接收到的数据", new Gson().toJson(user));
    }

使用PostMan 测试 ，请求失败，报RequestBody is missing 。我明明在body中携带了数据

**Comment by gdongxie** [comment]
求大佬知道

**Comment by gdongxie** [comment]
求大佬指导

**Comment by TYUpya** [comment]
Has this problem been solved?

**Comment by yanzhenjie** [comment]
需要配置Converter，参考下：
```java
@Converter
public class AppMessageConverter implements MessageConverter {
```
