### ISSUE TITLE
@RequestMapping path问题

### ISSUE THREAD

**Issue by coderMyron** [yanzhenjie/AndServer#196]
有子path时，一定要写在@RequestMapping(path = "/user")上，然后再添加子path，如@PostMapping(path ="/aa", produces = MediaType.APPLICATION_JSON_UTF8_VALUE)，这样调用action才能成功；要是没写@RequestMapping(path = "/user")，直接写成@PostMapping(path ="/user/aa", produces = MediaType.APPLICATION_JSON_UTF8_VALUE)的话，调用会返回404，这个bug我调了半天。。。

**Comment by yanzhenjie** [comment]
Did not understand, please show your code.

**Comment by coderMyron** [comment]
package com.tg.andserverrk.controller;

import com.tg.andserverrk.util.Logger;
import com.yanzhenjie.andserver.annotation.PostMapping;
import com.yanzhenjie.andserver.annotation.RequestMapping;
import com.yanzhenjie.andserver.annotation.RequestParam;
import com.yanzhenjie.andserver.annotation.RestController;
import com.yanzhenjie.andserver.util.MediaType;


@RestController
@RequestMapping(path = "/user")
public class RKController {

    @PostMapping(path ="/aa", produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
    String aa( @RequestParam("account") String account,
                  @RequestParam("password") String password) {
        Logger.d("account:" + account);
        Logger.d("password:" + password);

        if("123".equals(account) && "123".equals(password)) {
            return "Login successful.";
        } else {
            return "Login failed.";
        }
    }

}
---------------------
上面代码是运行是正确的
下面代码运行是错误的，会返回404
---------------------
package com.tg.andserverrk.controller;


import com.tg.andserverrk.util.Logger;
import com.yanzhenjie.andserver.annotation.PostMapping;
import com.yanzhenjie.andserver.annotation.RequestMapping;
import com.yanzhenjie.andserver.annotation.RequestParam;
import com.yanzhenjie.andserver.annotation.RestController;
import com.yanzhenjie.andserver.util.MediaType;


@RestController
public class RKController {

    @PostMapping(path ="/user/aa", produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
    String aa( @RequestParam("account") String account,
                  @RequestParam("password") String password) {
        Logger.d("account:" + account);
        Logger.d("password:" + password);

        if("123".equals(account) && "123".equals(password)) {
            return "Login successful.";
        } else {
            return "Login failed.";
        }
    }

}
