### ISSUE TITLE
如何实现文件下载的功能？

### ISSUE THREAD

**Issue by junfengren** [yanzhenjie/AndServer#2]
请问AndServer可以当下载的服务器吗？

**Comment by yanzhenjie** [comment]
可以的，写一个我大致写一个Handler出来，像demo中一样注册即可：
```java
public class AndServerDownloadHandler implements AndServerRequestHandler {

    @Override
    public void handle(HttpRequest request, HttpResponse response, HttpContext context) throws HttpException, IOException {
        // 拿到客户端参数key-value。
        Map<String, String> params = HttpRequestParser.parse(request);

        // 假设客户端要下载的文件名是通过filename这个参数提交的。
        String filePath = params.get("filename");

        File file = new File(filePath);
        if(file.exists()) {
            response.setStatusCode(200);// 文件存在，返回成功。

            long contentLength = file.length();
            response.setHeader("ContentLength", Long.toString(contentLength));
            InputStream inputStream = new FileInputStream(file);
            HttpEntity httpEntity = new InputStreamEntity(inputStream, contentLength);
            response.setEntity(httpEntity);
        } else {
            // 文件不存在。
            response.setStatusCode(404);
        }
    }

}
```

**Comment by junfengren** [comment]
收到，谢谢

2017-01-04 

15221951775 



发件人：严振杰 <notifications@github.com>
发送时间：2016-12-14 14:27
主题：Re: [yanzhenjie/AndServer] 如何实现文件下载的功能？ (#2)
收件人："yanzhenjie/AndServer"<AndServer@noreply.github.com>
抄送："junfeng.ren"<15221951775@163.com>,"Author"<author@noreply.github.com>

可以的，写一个我大致写一个Handler出来，像demo中一样注册即可：
public class AndServerDownloadHandler implements AndServerRequestHandler {

    @Override
    public void handle(HttpRequest request, HttpResponse response, HttpContext context) throws HttpException, IOException {
        // 拿到客户端参数key-value。
        Map<String, String> params = HttpRequestParser.parse(request);

        // 假设客户端要下载的文件名是通过filename这个参数提交的。
        String filePath = params.get("filename");

        File file = new File(filePath);
        if(file.exists()) {
            response.setStatusCode(200);// 文件存在，返回成功。

            long contentLength = file.length();
            response.setHeader("ContentLength", Long.toString(contentLength));
            InputStream inputStream = new FileInputStream(file);
            HttpEntity httpEntity = new InputStreamEntity(inputStream, contentLength);
            response.setEntity(httpEntity);
        } else {
            // 文件不存在。
            response.setStatusCode(404);
        }
    }

}
