### ISSUE TITLE
关于使用StorageWebsite时遇到的问题

### ISSUE THREAD

**Issue by rhylme** [yanzhenjie/AndServer#20]
功能:开启的服务器,通过拍照保存得到的图片,使用ip:8080//storage/emulated/0/path/图片.png查看拍照得到的图片发现<该网站无法运行>,然后重启一次服务器,再打开同样的链接才能查看
请问:是不是不能获取到服务器启动后的新建的文件链接?

**Comment by liujunhongz** [comment]
代码上写的很清楚啊，每个文件在启动服务器时都映射到了一个path，服务器启动后，你得手动添加映射才行吧

**Comment by rhylme** [comment]
怎么手动添加映射?

**Comment by rhylme** [comment]
有没有例子?大神

**Comment by yanzhenjie** [comment]
AndServer目前还不能做到热插拔，所以你指定目录后启动服务器，这时候AndServer才会隐射所有的文件，启动后放到文件夹的文件，是不会被再次映射的，除非你重启服务器。  
另外你可以写一个Handler，客户端访问这个Handler时带上要参数，用参数来区别访问的文件，这样就可以做到访问新添加的文件了。

**Comment by rhylme** [comment]
现在我是通过自动生成一系列文件,才开始启动服务器,当有所更改时不断的替换之前生成的文件,才解决现在的问题

**Comment by yanzhenjie** [comment]
不知道你们具体需求是怎样的，但是你这个也是一种方法，你可以写成文章分享给大家！我也在尝试着做热插拔的支持。

**Comment by xuhaisong** [comment]
关于StorageWebsite热插拔的问题，有没有解决方案可以分享一下呢

**Comment by xuhaisong** [comment]
关于StorageWebsite热插拔的问题，项目中也遇到了这个问题，有没有解决方案可以分享一下呢

**Comment by Sogrey** [comment]
因为项目里涉及下载文件并可以访问下载的新文件，期待 热插拔 解决方案

**Comment by Sogrey** [comment]
热插拔来了，大赞

**Comment by yanzhenjie** [comment]
新版支持热插拔了，修复了大家说的几个问题。大家可以试试新版，新版特性：网站热插拔、文件浏览器、支持Http缓存、拦截器、过滤器等等。而且文档相对也完善了一些：[http://yanzhenjie.github.io/AndServer](http://yanzhenjie.github.io/AndServer)
