### ISSUE TITLE
我集成到我项目中后，发现在6.0系统上可以正常访问，在4.4系统上，The resource [/user] is not found.

### ISSUE THREAD

**Issue by cs1991** [yanzhenjie/AndServer#201]
我集成到我项目中后，发现在6.0系统上可以正常访问，在4.4系统上，The resource [/user] is not found.，怎么解决？

**Comment by yanzhenjie** [comment]
This should be caused by the 64k method limit.

**Comment by cs1991** [comment]
不能分包吗，但是方法数超过了64k，怎么处理呢？谢谢

**Comment by yanzhenjie** [comment]
https://developer.android.google.cn/studio/build/multidex?hl=en
