### ISSUE TITLE
使用4G网络，外网无法请求

### ISSUE THREAD

**Issue by huangliqiang** [yanzhenjie/AndServer#202]
手机用4G网络，获取的ip是10.XXX.XXX.XXX， 但是电脑用postman无法访问到手机的接口、

**Comment by yanzhenjie** [comment]
This is not a problem with this project.

**Comment by huangliqiang** [comment]
> This is not a problem with this project.
当前手机是使用4G网络注册webserver，代码：
 webServer = AndServer.serverBuilder()
                .inetAddress(NetUtil.getLocalIPAddress())
                .port(8080)
                .timeout(10, TimeUnit.SECONDS) //Socket超时时间
                .listener(new Server.ServerListener() {
｝
注册IP是10.3.19.232。

注册成功后无法请求通该服务提供的接口。

**Comment by huangliqiang** [comment]
> This is not a problem with this project.


当前手机是使用4G网络注册webserver，代码：
webServer = AndServer.serverBuilder()
.inetAddress(NetUtil.getLocalIPAddress())
.port(8080)
.timeout(10, TimeUnit.SECONDS) //Socket超时时间
.listener(new Server.ServerListener() {
｝
注册IP是10.3.19.232。
注册成功后无法请求通该服务提供的接口。

**Comment by zhuqichao** [comment]
> > This is not a problem with this project.
> 
> 当前手机是使用4G网络注册webserver，代码：
> webServer = AndServer.serverBuilder()
> .inetAddress(NetUtil.getLocalIPAddress())
> .port(8080)
> .timeout(10, TimeUnit.SECONDS) //Socket超时时间
> .listener(new Server.ServerListener() {
> ｝
> 注册IP是10.3.19.232。
> 注册成功后无法请求通该服务提供的接口。

只支持局域网，除非你的手机有公网IP
