### ISSUE TITLE
无法将类 InternalWebsite中的构造器 InternalWebsite应用到给定类型

### ISSUE THREAD

**Issue by haroel** [yanzhenjie/AndServer#204]
错误: 无法将类 InternalWebsite中的构造器 InternalWebsite应用到给定类型;

照gitbook做问题，改成下面，编译期就报错了，问下大佬，该怎么解决？
![image](https://user-images.githubusercontent.com/2418222/61425392-6a249580-a949-11e9-8c8b-7b4c8b009717.png)

Android studio 3.4.2

**Comment by yanzhenjie** [comment]
If you use the `@Website` annotation, both the`context` and the `path` need to be obtained using static methods.
You can use the `@Config` annotation, which can be easily learned and accepted. For details, see the demo.
