### ISSUE TITLE
PathVariable注解编译不通过

### ISSUE THREAD

**Issue by yinshengpan** [yanzhenjie/AndServer#207]
**code:**
```
@GetMapping("/read/query/mainPageData/ts-{time}")
String getDubHomePage(@PathVariable("time") String time) {}
```

**error:**
`The format of path [/read/query/mainPageData/ts-{time}] is wrong on`

**Comment by yanzhenjie** [comment]
This error is very obvious.

```java
@GetMapping("/read/query/mainPageData/{time}")
String getDubHomePage(@PathVariable("time") String time){}
```

**Comment by yinshengpan** [comment]
我知道这种方式能编译通过，我这边多渠道的形式要写一个离线版本，后台接口是/ts-{time}/的形式，所以想直接根据后台的样式写，但是这样的形式编译不通过。如果这样的形式不行的话就直接新写一个接口了。

**Comment by yanzhenjie** [comment]
You may not understand the path of the url.

![url](https://user-images.githubusercontent.com/13534988/61676649-5e611680-ad2f-11e9-8a98-f5214bd1e80f.png)

path:
```
/segment/segment/segment
```

variable of path:
```
/{Variable}/{Variable}/{Variable}
```

So PathVariable is just a segment in the path, not part of the segment.

**Comment by yinshengpan** [comment]
不过后台@Path是可以这样写的，不过也没事，感谢。
[http://ww3.sinaimg.cn/large/006tNc79gy1g59jt4s3rhj31ib0u0t9l.jpg](http://ww3.sinaimg.cn/large/006tNc79gy1g59jt4s3rhj31ib0u0t9l.jpg)

**Comment by yanzhenjie** [comment]
I understand that you are too polite, maybe I have a little difference with its thoughts, thank you for your feedback.

**Comment by yanzhenjie** [comment]
Oh, wait, I hope to use English to communicate in English projects, even if the author is a Chinese, which helps to build a community atmosphere.

**Comment by yinshengpan** [comment]
OK,Thank you for your answer.
