### ISSUE TITLE
MIME

### ISSUE THREAD

**Issue by yangzhengwen** [yanzhenjie/AndServer#213]
大佬，我这跑了个Angular2的项目，出现了这个错误
  **its MIME type ('application/octet-stream') is not executable.**
我看了源码，有定义这个类型的，不知道为什么还会出现这样的错误

**Comment by yanzhenjie** [comment]
This is a bug reported by the web, because the type of a file is unknown, please check according to this instruction.

**Comment by yangzhengwen** [comment]
> This is a bug reported by the web, because the type of a file is unknown, please check according to this instruction.

文件是  .js  文件，项目我用电脑跑起来是没问题的

**Comment by yangzhengwen** [comment]
> This is a bug reported by the web, because the type of a file is unknown, please check according to this instruction.

下午换个个设备测试，没有报错，可以正常加载，不知道大佬有没有做过机型的适配呢

**Comment by bytelurk** [comment]
同样的问题，求教怎么设置

**Comment by bytelurk** [comment]
@yangzhengwen  有解决方案吗

**Comment by yangzhengwen** [comment]
> @yangzhengwen 有解决方案吗

我把web项目所有的MIME都添加到代码里了，部分设备不报错，部分设备报错，暂无解决方案
