### ISSUE TITLE
如何实现soap

### ISSUE THREAD

**Issue by xmlhttp** [yanzhenjie/AndServer#215]
我想实现webservice服务，要怎么做？

**Comment by xmlhttp** [comment]
楼主，你好，我想这样实现webservice不知道可不可行
1、导入包 compile files('libs/android-ws-combine.jar')
2、新增个HelloController，代码如下：
`@RestController
@RequestMapping(path = "/hello")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@WebService
public class HelloController {

    @GetMapping(path = "/")

    public Endpoint index() {

        String address = "http://localhost:8086/hello";
        HelloController implementor = new HelloController();
        return Endpoint.publish(address, implementor);

    }

    @WebMethod(operationName = "hello")
    public String hello() {
        return "AAAAAAAAAAAAAAAAAAAAAAAA!";
    }

}`
不知道这样可不可行？访问提示Provider com.sun.xml.internal.ws.spi.ProviderImpl not found
请问有什么方法可以实现呢？

**Comment by yanzhenjie** [comment]
这个就说来话长了，自己查资料吧。

**Comment by wangpeng1** [comment]
@yanzhenjie  为啥回答的是自己查资料呢？ 不就是和json 一样吗，只是解析xml就行了？ 难道此库不支持xml数据传输吗？

**Comment by yanzhenjie** [comment]
> @yanzhenjie 为啥回答的是自己查资料呢？ 不就是和json 一样吗，只是解析xml就行了？ 难道此库不支持xml数据传输吗？

没错。支持。自己查资料确实更清楚。
