### ISSUE TITLE
监听端口被关闭

### ISSUE THREAD

**Issue by ldxk** [yanzhenjie/AndServer#216]
长时间运行应用,有时会出现监听的端口被关闭的情况.
通过adb shell dumpsys activity services [<packagename>] 查看正在运行的 Services时发现CoreService服务依旧存在,
但是通过adb shell netstat -ant 查看网络监听8080端口发现监听消失了.
不知道有没有遇到这种情况的

**Comment by vudiy** [comment]
@ldxk 你这种情况怎么解决的？
