### ISSUE TITLE
如何从sqlite读取图片而不保存到sdcard给前端显示

### ISSUE THREAD

**Issue by zhongshuiyuan** [yanzhenjie/AndServer#217]

**Comment by yanzhenjie** [comment]
Please do not mention issues that are not related to this project.

**Comment by zhongshuiyuan** [comment]
有关，有一个sqlite存储很多图片，我使用了andserver,我想写一个服务，这个服务从sqlite中读取图片例如：
byte[] getMap(HttpRequest request, HttpResponse response, @RequestParam(name = "level") String level, @RequestParam(name = "row") String row, @RequestParam(name = "col") String col) {
        try {
            response.setHeader("Content-Type", "image/png");
            Cursor imageCur = ConstantUtil.mapDb.rawQuery("SELECT tile_data FROM tiles WHERE zoom_level = " + level + " AND tile_column = " + col + " AND tile_row = " + row, null);
            if (imageCur.moveToFirst()) {
                byte[] btyImg = imageCur.getBlob(0);
                if(ConstantUtil.CacheCompact == true){
                    return CompressionUtil.decompress(btyImg);
                }
                return btyImg;
            }
            //imageCur.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return new byte[0];
    }

**Comment by yanzhenjie** [comment]
http://yanzhenjie.com/AndServer/class/ResponseBody.html

**Comment by zhongshuiyuan** [comment]
非常感谢，解决了
