### ISSUE TITLE
请问实现的RequestHandler为什么不回调？？使用您的登录，点击sign in 直接501

### ISSUE THREAD

**Issue by CoderYanKang** [yanzhenjie/AndServer#22]
========================================
 AndServer andServer = new AndServer.Build()
                .port(8080)
                .timeout(10 * 1000)
                .registerHandler("login", new RequestLoginHandler())
//                .registerHandler("download", new RequestFileHandler("Your file path"))
                .registerHandler("download", new RequestFileHandler(path))
                .registerHandler("upload", new RequestUploadHandler())
                .website(new AssetsWebsite(mAssetManager, "web"))
                .listener(mListener)
                .build();
==========================================
![image](https://user-images.githubusercontent.com/24955571/28065039-82e4490a-6669-11e7-8c5f-420691937003.png)
=============
index.html 
添加
<form id="form1" method="post" action="download">
        <button >下载</button>
</form>

点击下载 501
==========================================
![image](https://user-images.githubusercontent.com/24955571/28065074-a1456cf8-6669-11e7-82e6-70839a405808.png)

**Comment by weizai** [comment]
同样出现501错误，直接用的是sample项目

**Comment by weizai** [comment]
将login.html 中的action调整为<form id="form1" method="post" action="../login"> 就可以了

**Comment by weizai** [comment]
将login.html中的Form action调整为`<form id="form1" method="post" action="../login">`就可以了

**Comment by CoderYanKang** [comment]
谢谢 ， 是的 我也发现了 加了/  接口可以使用了。web知识比较缺乏

**Comment by yanzhenjie** [comment]
因为这半年工作比较忙，对Github的issue处理的很慢。特别谢谢大家在issue中互相回复解决了很多问题。

近期发布了新版本，大家可以试试新版本，新版特性：网站热插拔、文件浏览器、支持Http缓存、拦截器、过滤器等等。而且文档相对也完善了一些：[http://yanzhenjie.github.io/AndServer](http://yanzhenjie.github.io/AndServer)
