### ISSUE TITLE
net::ERR_CONNECTION_REFUSED after change phone`s font size

### ISSUE THREAD

**Issue by leege100** [yanzhenjie/AndServer#222]
在APP中开启服务，此时通过webview或者浏览器可以访问网页，但是当我进入系统设置页面更改了手机字体大小再访问时，就提示:位于 http://127.0.0.1:5001的网页无法加载，因为：net:ERR_CONNECTION_REFUSED。

**Comment by yanzhenjie** [comment]
重启服务器。
