### ISSUE TITLE
我得到IP不对啊,我得到的IP为192.168.43.1,但我实际IP为192.168.1.35,这是什么情况博主?

### ISSUE THREAD

**Issue by cfr999** [yanzhenjie/AndServer#23]
我得到IP不对啊,我得到的IP为192.168.43.1,但我实际IP为192.168.1.35,这是什么情况博主?

**Comment by cfr999** [comment]
我是下的Demo跑到啊

**Comment by yanzhenjie** [comment]
可能之前的Demo获取IP有问题，你可以自己获取本地IP看看。目前更新了新版本，新版特性：网站热插拔、文件浏览器、支持Http缓存、拦截器、过滤器等等。而且文档相对也完善了一些：[http://yanzhenjie.github.io/AndServer](http://yanzhenjie.github.io/AndServer)
