### ISSUE TITLE
使用中发现本地服务blob url 无法下载

### ISSUE THREAD

**Issue by kingiis** [yanzhenjie/AndServer#232]
服务是架在本地了
导出文件工能遇到了 一个blob:开头的url
浏览器里OK的
过Android webview时 发现了js解决方案
但是js方法执行时 一直走onerror下载不动
javascript:
                   var xhr = new XMLHttpRequest();
                   var util = window.WebUtils;" +
                    xhr.open('GET', \""+blobUrl+"\", true);
                    xhr.setRequestHeader('Content-type','application/pdf');
                    xhr.responseType = 'blob';
                    xhr.onload = function(e) {
                        if (this.status == 200) {
                            var blobPdf = this.response;
                            var reader = new FileReader();
                            reader.readAsDataURL(blobPdf);
                           reader.onloadend = function() {
                                base64data = reader.result;
                               util.getBase64FromBlobData(base64data);
                           }
                        }
                    };
                    xhr.onerror=function(data){alert(data)}
                   xhr.send();
苦恼 一直报 [object  ProgressEvent]

**Comment by yanzhenjie** [comment]
那不是http的url当然不能访问啦，不是AndServer提供的服务。
