### ISSUE TITLE
加载一个网页要两三分钟,为什么我的要这么久时间?

### ISSUE THREAD

**Issue by Primer1889** [yanzhenjie/AndServer#238]
![image](https://user-images.githubusercontent.com/41484434/70116064-9f354880-169c-11ea-88d0-314d2554b59f.png)

难道就是因为我的网页数据太多?

**Comment by Primer1889** [comment]
是不是要优化一下网页的渲染?

**Comment by yanzhenjie** [comment]
网页加载时间和内容大小、网络情况有关。
本库只是提供网络资源的传递，没有网页这个概念，网页渲染和本库无关。

**Comment by ag2s20150909** [comment]
尽量少在head里面引入较大的js库，这会阻塞WebView对body里面的DOM的解析。
