### ISSUE TITLE
提个小bug。

### ISSUE THREAD

**Issue by oksimple** [yanzhenjie/AndServer#24]
如果 我只需要 registerHandler 的时候 不给 Website 的话， CoreThread----registerRequestHandler方法里面的mWebDirectory 会报空，if (mWebDirectory != null){
            mWebDirectory.onRegister(websiteMap);
        }

**Comment by yanzhenjie** [comment]
我看了旧版本确实存在这个问题，已经修复了。

另外请试试新版本，新版特性：网站热插拔、文件浏览器、支持Http缓存、拦截器、过滤器等等。而且文档相对也完善了一些：[http://yanzhenjie.github.io/AndServer](http://yanzhenjie.github.io/AndServer)
