### ISSUE TITLE
离线引用对应的文件，版本为2.0.5会报错，

### ISSUE THREAD

**Issue by cjj-sal** [yanzhenjie/AndServer#241]
![image](https://user-images.githubusercontent.com/57379366/71465910-dbba1700-27f8-11ea-9cc2-2683eb768001.png)
![image](https://user-images.githubusercontent.com/57379366/71465937-f7252200-27f8-11ea-96cd-47be4579072a.png)

**Comment by yanzhenjie** [comment]
强烈建议用maven仓库url依赖，离线的话还需要手动添加其他包。
