### ISSUE TITLE
部署Vue网站

### ISSUE THREAD

**Issue by YannSuper** [yanzhenjie/AndServer#244]
vue 有前端路由，在后端能不能根据正则去匹配路由，把/xxxx/xxxx 这样的路由forward到index.html下面，把/api/xxxx这样的路由正常走controler,图片文件,css文件，js文件正常请求不进行拦截。

**Comment by yanzhenjie** [comment]
按照AndServer结构开发是不用做拦截的，具体可以看下文档。另外如果是已有网站，改结构比较麻烦的话，可以配置拦截器自己做转发试试。

**Comment by yanzhenjie** [comment]
无响应，关闭。
