### ISSUE TITLE
FileBrowser怎么用

### ISSUE THREAD

**Issue by wanglibocode** [yanzhenjie/AndServer#248]
您好！请问我先通过AndServer访问手机上的文件，请问是否使用FileBrowser就够了，如果够的话，我该怎么用呢？谢谢！

**Comment by yanzhenjie** [comment]
可以先看下demo和文档，如果还不会再来这里提问吧，这个issue我先保留不关闭，有问题再继续追问。

**Comment by 54wall** [comment]
最想版本的Website注解已经弃用了，先新建一个类SimpleBrowser 和文档一样，注意注解变成@Config
import android.os.Environment;
import android.util.Log;

import com.yanzhenjie.andserver.annotation.Config;
import com.yanzhenjie.andserver.framework.website.FileBrowser;

//import com.yanzhenjie.andserver.annotation.Website;//已弃用

/**
 * 指定目录作为本地存储文件夹
 */
@Config
public class SimpleBrowser extends FileBrowser {
    public SimpleBrowser() {
        super(Environment.getExternalStorageDirectory().getAbsolutePath() + "/AndServer");
        Log.e("PATH", Environment.getExternalStorageDirectory().getAbsolutePath());
    }
}

再在AppConfig 中添加delegate.addWebsite(new SimpleBrowser());
import com.yanzhenjie.andserver.annotation.Config;
import com.yanzhenjie.andserver.framework.config.Multipart;
import com.yanzhenjie.andserver.framework.config.WebConfig;
import com.yanzhenjie.andserver.framework.website.AssetsWebsite;

import java.io.File;

/**
 * Created by Zhenjie Yan on 2019-06-30.
 */
@Config
public class AppConfig implements WebConfig {

    @Override
    public void onConfig(Context context, Delegate delegate) {
        delegate.addWebsite(new AssetsWebsite(context, "/web"));
        delegate.addWebsite(new SimpleBrowser());
        delegate.setMultipart(Multipart.newBuilder()
                .allFileMaxSize(1024 * 1024 * 20) // 20M
                .fileMaxSize(1024 * 1024 * 5) // 5M
                .maxInMemorySize(1024 * 10) // 1024 * 10 bytes
                .uploadTempDir(new File(context.getCacheDir(), "_server_upload_cache_"))
                .build());
    }
}
之后你访问http://127.0.0.1:28088/就直接跳到android目录了

**Comment by zhuqichao** [comment]
按照上述方法使用后，访问提示The resource [/] is not found.是什么原因呢
