### ISSUE TITLE
关于ip地址固定

### ISSUE THREAD

**Issue by eevonlee** [yanzhenjie/AndServer#25]
android 源码中，对于热点的ip是固定的：
NetworkUtils.numericToInetAddress("192.168.43.1"), 24));
但是开启手机热点，运行AndServer中 String ip = NetUtil.getLocalIPAddress();
这个IP的格式是 10.xx.xxx.xx ,并且该ip会改变，请问如何做到固定ip？

**Comment by shenzhiguo** [comment]
切换WIFI、4G、无网络状态同样会出现这个问题，服务器的IP地址无法固定。

**Comment by yanzhenjie** [comment]
在旧版本中可以尝试固定手机IP。但是切换WIFI、4G这个就有点说不过去了。

现在发布了新版本，新版本可以指定服务器要监听的本地IP地址了。新版本特性如下：网站热插拔、文件浏览器、拦截器、过滤器、Http缓存。另外文档也相对更加完善了：[http://yanzhenjie.github.io/AndServer](http://yanzhenjie.github.io/AndServer)
