### ISSUE TITLE
@WebSite 找不到? 移除了吗？和文档对应不上

### ISSUE THREAD

**Issue by dtboy1995** [yanzhenjie/AndServer#256]
- AndServer 2.1.0
```grable
    implementation 'com.yanzhenjie.andserver:api:2.1.0'
    annotationProcessor 'com.yanzhenjie.andserver:processor:2.1.0'
```
- Android Studio 3.6.1
![image](https://user-images.githubusercontent.com/19227547/77825745-4a837500-7146-11ea-9a2c-4fb110fcedfa.png)

首先感谢大佬

我看您的提交是吧这块功能移除了 https://github.com/yanzhenjie/AndServer/commit/8dbb6cd192808af6a685404401716861100e116d
和文档中有出处，劳烦您标记一下，否则会浪费人的时间。谢谢了

**Comment by dtboy1995** [comment]
sample的Appconfig有相关配置

**Comment by Key-CN** [comment]
@yanzhenjie 是的，大佬。我看文档，找两个小时找来这边才发现移除了，更新下文档吧，就标记下就好
