### ISSUE TITLE
ajax跨域上传图片会报跨域的错但是我已经设置跨域了

### ISSUE THREAD

**Issue by tghjnjvg** [yanzhenjie/AndServer#261]
@RequestMapping(path = "/uploadp",method =  {RequestMethod.GET, RequestMethod.POST,RequestMethod.OPTIONS,RequestMethod.DELETE,RequestMethod.PUT} )
    String uploadp(@RequestParam("file") MultipartFile file, HttpRequest request, HttpResponse response) throws IOException {
        Log.e("asdasd", String.valueOf(request.getMethod().value()));
        Log.e("asdasd", String.valueOf(request.getMethod()));
        if( String.valueOf(request.getMethod()).equals("OPTIONS") ){
            response.addHeader("Access-Control-Allow-Origin","*");
            response.addHeader("Access-Control-Allow-Methods","POST,GET,OPTIONS,DELETE,PUT");
            return null;
        }
        response.addHeader("Access-Control-Allow-Origin","*");
        response.addHeader("Access-Control-Allow-Methods","POST,GET,OPTIONS,DELETE,PUT");
//        response.addHeader("Content-Type","application/json");
//        response.addHeader("Access-Control-Max-Age","3600");
        File localFile =new File("/sdcard/"+file.getFilename());
        file.transferTo(localFile); // Transfer the file to the target location.
        return localFile.getAbsolutePath();
    }
以上是我的代码

**Comment by tghjnjvg** [comment]
$("#uploadfile").click(function() {
            var formData = new FormData();
            formData.append("file", $("#uploadfoldermsg")[0].files[0]);
            $.ajax({
                url: address + '/uploadp',
                type: 'post',
                data: formData,
                cache: false,
                async: false,
                contentType: false,
                processData: false,
                xhr: function() { //这里我们先拿到jQuery产生的 XMLHttpRequest对象，为其增加 progress 事件绑定，然后再返回交给ajax使用
                    var myXhr = $.ajaxSettings.xhr();
                    //不知道为啥报错
                    myXhr.upload.addEventListener('progress', function(event) {
                            if (event.lengthComputable) {
                                var value = (event.loaded / event.total * 100 | 0);
                                lo("time:" + value);
                                //$("#progress_bar_top").css('width', (value + '%'));
                            }
                        }, false) //progress事件会在浏览器接收新数据期间周期性地触发。而onprogress事件处理程序会接收到一个event对象，其target属性是XHR对象，但包含着三个额外的属性：lengthComputable、loaded和total。其中，lengthComputable是一个表示进度信息是否可用的布尔值，loaded表示已经接收的字节数，loaded表示根据Content-Length响应头部确定的预期字节数。
                    return myXhr;
                },
                success: function(res) {
                    console.log(res.data);
                    if (res.data["code"] == "succ") {
                        alert('成功');
                    } else if (res.data["code"] == "err") {
                        alert('失败');
                    } else {
                        console.log(res);
                    }
                }
            })
        });

**Comment by tghjnjvg** [comment]
上面是AndServer代码下面是js的代码

**Comment by tghjnjvg** [comment]
浏览器报错信息
已拦截跨源请求：同源策略禁止读取位于 http://192.168.1.236:8080/uploadp 的远程资源。（原因：CORS 头缺少 'Access-Control-Allow-Origin'）。
已拦截跨源请求：同源策略禁止读取位于 http://192.168.1.236:8080/uploadp 的远程资源。（原因：CORS 请求未能成功）。

**Comment by tghjnjvg** [comment]
但是我js代码如果去掉以下代码就不会报错
 xhr: function() { //这里我们先拿到jQuery产生的 XMLHttpRequest对象，为其增加 progress 事件绑定，然后再返回交给ajax使用
                    var myXhr = $.ajaxSettings.xhr();
                    //不知道为啥报错
                    myXhr.upload.addEventListener('progress', function(event) {
                            if (event.lengthComputable) {
                                var value = (event.loaded / event.total * 100 | 0);
                                lo("time:" + value);
                                //$("#progress_bar_top").css('width', (value + '%'));
                            }
                        }, false) //progress事件会在浏览器接收新数据期间周期性地触发。而onprogress事件处理程序会接收到一个event对象，其target属性是XHR对象，但包含着三个额外的属性：lengthComputable、loaded和total。其中，lengthComputable是一个表示进度信息是否可用的布尔值，loaded表示已经接收的字节数，loaded表示根据Content-Length响应头部确定的预期字节数。
                    return myXhr;
                },

**Comment by tghjnjvg** [comment]
或者去掉这句 就是这句使他这个奇怪的错误

   myXhr.upload.addEventListener('progress', function(event) {
                            if (event.lengthComputable) {
                                var value = (event.loaded / event.total * 100 | 0);
                                lo("time:" + value);
                                //$("#progress_bar_top").css('width', (value + '%'));
                            }
                        }, false) //progress事件会在浏览器接收新数据期间周期性地触发。而onprogress事件

**Comment by tghjnjvg** [comment]
是我服务器写法的问题还是ajax读取进度条有问题，求解

**Comment by yanzhenjie** [comment]
先用postman测试一下，服务端接口响应是不是有问题，别着急这个要慢慢调试，应该是哪边的细节问题。

**Comment by tghjnjvg** [comment]
我初步排查问题应该是，ajax跨域上传文件，如果监听了progress事件，则变为预检请求，需要后端支持options请求才可以。具体要看你的错误信息是什么

**Comment by tghjnjvg** [comment]
我初步排查问题应该是，ajax跨域上传文件，如果监听了progress事件，则变为预检请求，需要后端支持options请求才可以。

**Comment by tghjnjvg** [comment]
我那个代码的话应该跨域是支持options请求了，不知道有没有写错

**Comment by tghjnjvg** [comment]
postman调试了 简单上传文件不会报错，ajax跨域上传也不会有错，但是前端的ajax如果监听了progress事件，则变为预检请求，需要后端支持options请求才可以。我这样写应该是支持了options了 但是这样报错却是options监听有问题

**Comment by tghjnjvg** [comment]
实际上是ajax预检请求 服务器无法处理 我蒙了
