### ISSUE TITLE
Controller中使用上下文对象context的问题

### ISSUE THREAD

**Issue by lujx1024** [yanzhenjie/AndServer#262]
作者大神，您好，请问如果需要在controller的业务逻辑中使用到安卓上下文对象context，如何进行注入？尝试过加入成员变量 Context,但是由于controller是插件管理的，context无法实例化。请教一下这种情况怎么处理，谢谢

**Comment by yanzhenjie** [comment]
两种方法，第一种是`Application`提供一个静态方法获取，第二种是`Controller`中的方法写一个Context参数：
```java
public void login(Context context, @RequestParam...) {
```

**Comment by lujx1024** [comment]
谢谢您的建议，已经通过第一种方法解决了；还想问一句，您在controller中的方法写入了Context参数，这个参数怎么传递进去呢？毕竟并没有直接调用，只是加了注解之后便可以拦截request，还请您解惑，谢谢

**Comment by alone-wolf** [comment]
2.1.1版本，第二种方法实现了andserver与androidx.room库配合使用
