### ISSUE TITLE
最新2.x版本不支持文件上传进度监听了吗

### ISSUE THREAD

**Issue by zhuqichao** [yanzhenjie/AndServer#263]
请教大神，我注意到1.x的文档是有文件上传进度监听的，但是2.x好像不支持文件上传进度监听了，而且必须先将文件写入缓存，再复制到目标文件，不支持直接流复制，这样导致速度慢了3倍

**Comment by liulin188** [comment]
有没有最新的jar包呢

**Comment by yanzhenjie** [comment]
@zhuqichao  可以先回复客户端响应，开线程执行文件复制操作，这样会加快响应速度

@liulin188  不支持jar包方式。
