### ISSUE TITLE
希望BasicServer里面的这些关于Socket的配置项可以开放出来

### ISSUE THREAD

**Issue by panyiho** [yanzhenjie/AndServer#264]
` mHttpServer = ServerBootstrap.bootstrap()
                    .setServerSocketFactory(mSocketFactory)
                    .setSocketConfig(
                        SocketConfig.custom()
                            .setSoKeepAlive(true)
                            .setSoReuseAddress(true)
                            .setTcpNoDelay(true)
                            .setSoTimeout(mTimeout)
                            .setBacklogSize(BUFFER)
                            .setRcvBufSize(BUFFER)
                            .setSndBufSize(BUFFER)
                            .setSoLinger(0)
                            .build()
                    )
                    .setLocalAddress(mInetAddress)
                    .setListenerPort(mPort)
                    .setSslContext(mSSLContext)
                    .setSslSetupHandler(new SSLSetup(mSSLSocketInitializer))
                    .setServerInfo(AndServer.INFO)
                    .registerHandler("*", requestHandler())
                    .setExceptionLogger(ExceptionLogger.NO_OP)
                    .create();`

希望BasicServer里面的这些配置项可以开放出来，很多时候需要设置socket的一些配置，例如buffer等

**Comment by yanzhenjie** [comment]
可以设置SocketFactory，SSLContext等。

**Comment by panyiho** [comment]
额，你只是开放了ServerSocketFactory出来而已吧，但是SocketConfig这个设置的是accept的socket，这个没有开放啊
