### ISSUE TITLE
RequestParam中使用int类型编译报错

### ISSUE THREAD

**Issue by coder-bihao** [yanzhenjie/AndServer#269]
您好：
请教个问题，在请求参数中使用Int类型会报错，请问是什么原因呢？
代码：
![image](https://user-images.githubusercontent.com/49231365/81293584-23eb1f00-90a0-11ea-8477-ceb265957f54.png)
错误：
![image](https://user-images.githubusercontent.com/49231365/81293611-2c435a00-90a0-11ea-8ee0-0a2e63f9bdd7.png)
![image](https://user-images.githubusercontent.com/49231365/81293636-35ccc200-90a0-11ea-996f-c336e091d818.png)

**Comment by coder-bihao** [comment]
如果去掉@RequestParam("test") long test 这一行，编译是没有问题的

**Comment by coder-bihao** [comment]
版本：2.0.5

**Comment by yanzhenjie** [comment]
版本是有点老了，可以升级一下，老版本我也没办法，只能升级了。
