### ISSUE TITLE
请求转向怎么弄

### ISSUE THREAD

**Issue by Dizner** [yanzhenjie/AndServer#27]

**Comment by yanzhenjie** [comment]
具体方法我也忘记了，原理是，设置响应码为302，然后Location头中写重定向地址。

response.setStatusCode(302);
response.setHeader("Location", "重定向地址")

**Comment by Dizner** [comment]
好的，谢谢

**Comment by yanzhenjie** [comment]
可以试试新版本，加了热插拔、拦截器、过滤器等不少新特性。新版本很方便重定向，详细请看看文档。
