### ISSUE TITLE
Android API29 无法正常启动AndServer.WebServer

### ISSUE THREAD

**Issue by 1418496327** [yanzhenjie/AndServer#271]
作者大神你好，我在使用AndServer时遇到了非常棘手的异常问题，异常信息为：
I/AndServer: VM with version 2.1.0 has Multidex support.
I/AndServer: InstantRun support was not found.
该异常导致AndServer一直处于未启动状态，之前看了一位朋友说用API（19-23）可以正常启动，我试过了，均不奏效，希望能够早日得到您的回答。

**Comment by 1418496327** [comment]
我的AndServer版本为2.1.1

**Comment by gebilaosiji** [comment]
这个是你项目的问题吧，吧项目的InstantRun关了试试

**Comment by yanzhenjie** [comment]
旧版本为了加载class是会判断multi dex和instant run的，虽然没有问题，但是不太安全的，新版本不采用这样的方式了，升级后就不会遇到这样的问题了。
