### ISSUE TITLE
注解不能自动生成

### ISSUE THREAD

**Issue by smallmouse2009** [yanzhenjie/AndServer#275]

**Comment by smallmouse2009** [comment]
apply plugin: 'com.yanzhenjie.andserver'    
classpath 'com.yanzhenjie.andserver:plugin:2.1.1'
api 'com.yanzhenjie.andserver:api:2.1.1'
annotationProcessor 'com.yanzhenjie.andserver:processor:2.1.1'
这些都配置了，AppConfig还有其他几个类的注解的类，没有自动生成build文件

**Comment by smallmouse2009** [comment]
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip
classpath 'com.android.tools.build:gradle:3.6.2'

**Comment by yanzhenjie** [comment]
试试demo.

**Comment by smallmouse2009** [comment]
demo可以，我引入aar和plugin不行，我把compent包下的几个类   按照apt里面的包名创建，也会被加载到内存中

**Comment by yanzhenjie** [comment]
按照demo和文档指示来。
