### ISSUE TITLE
bug- helpe me

### ISSUE THREAD

**Issue by guqh** [yanzhenjie/AndServer#277]
当 接口参数中 存在特殊字符 比如：“&”  “%” 会报错 500
![image](https://user-images.githubusercontent.com/17330238/85518376-c05a8800-b632-11ea-95ad-fbf60165c13b.png)

请问该怎么处理，要做怎么样的支持才行

**Comment by guqh** [comment]
@yanzhenjie @kong-jing @OddCN @hellofriday

**Comment by yanzhenjie** [comment]
错误发全一点，应该是尽量提供更多的信息方便别人判断问题，你这让别人怎么判断。

**Comment by guqh** [comment]
就是我在&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhenjie Yan"<notifications@github.com&gt;; 
发送时间: 2020年6月24日(星期三) 下午5:51
收件人: "yanzhenjie/AndServer"<AndServer@noreply.github.com&gt;; 
抄送: "______红仔"<970113287@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yanzhenjie/AndServer] bug- helpe me (#277)





 
错误发全一点，应该是尽量提供更多的信息方便别人判断问题，你这让别人怎么判断。

**Comment by guqh** [comment]
就是我在&nbsp;RequestParam  参数里面加入了  %  和 &amp; 字符 ，然后就直接 报错返回 500 了 




他这个提示&nbsp; 也是&nbsp; 说 参数里面包含了 % 字符&nbsp;







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zhenjie Yan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月24日(星期三) 下午5:51
收件人:&nbsp;"yanzhenjie/AndServer"<AndServer@noreply.github.com&gt;;
抄送:&nbsp;"______红仔"<970113287@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yanzhenjie/AndServer] bug- helpe me (#277)





 
错误发全一点，应该是尽量提供更多的信息方便别人判断问题，你这让别人怎么判断。

**Comment by guqh** [comment]
![image](https://user-images.githubusercontent.com/17330238/85534844-4206e180-b644-11ea-8953-fabca66e2dcb.png)

**Comment by guqh** [comment]
就是我在&nbsp;RequestParam  参数里面加入了  %  和 &amp; 字符 ，然后就直接 报错返回 500 了

他这个提示&nbsp; 也是&nbsp; 说 参数里面包含了 % 字符&nbsp;

没有别的过多的 信息 ，你试一下这两个字符 应该就能出现

**Comment by guqh** [comment]
服务端 定义一个接口，参数接收string 字符串（其实是个json 格式 字符串），然后客户端 请求该接口时，参数中带有 % & 这俩字符 就会出现该 问题。

**Comment by guqh** [comment]
@yanzhenjie

**Comment by guqh** [comment]
![image](https://user-images.githubusercontent.com/17330238/86903327-c461cc00-c141-11ea-8288-04a5943a0243.png)

用的AndServer Android 服务端  定义的 接口 
这个参数接收一个json 字符串 ，每当字符串中 存在 & % 这两个字符时 ，客户端就出现 以下问题。 其他字符串暂时还没碰到不知道有没有同样的问题。

https://user-images.githubusercontent.com/17330238/85534844-4206e180-b644-11ea-8953-fabca66e2dcb.png

**Comment by guqh** [comment]
![image](https://user-images.githubusercontent.com/17330238/86903570-1c003780-c142-11ea-9480-f6baa6b51e76.png)
用的AndServer Android 服务端 定义的 接口
这个参数接收一个json 字符串 ，每当字符串中 存在 & % 这两个字符时 ，客户端就出现 以下问题。 其他字符串暂时还没碰到不知道有没有同样的问题。
![image](https://user-images.githubusercontent.com/17330238/86903589-215d8200-c142-11ea-8376-cc89998b65c7.png)

**Comment by yanzhenjie** [comment]
客户端要URLEncode.
