### ISSUE TITLE
开启服务器后，再向里面写入文件，服务器会关闭，然后再手动关闭，重新开启时，会报端口占用

### ISSUE THREAD

**Issue by GentleLi** [yanzhenjie/AndServer#28]

**Comment by yanzhenjie** [comment]
抱歉我看不太明白，向哪里写入文件？手动关闭时，是否关闭了AndServer服务器？当然这只是些提问建议，尽量把问题描述清楚些。

另外你可以试试新版本啦，新版特性：网站热插拔、文件浏览器、支持Http缓存、拦截器、过滤器等等。而且文档相对也完善了一些：[http://yanzhenjie.github.io/AndServer](http://yanzhenjie.github.io/AndServer)
