### ISSUE TITLE
主机发射热点地址，另一个手机局域网播放mp4文件，需要加载完成才能播放

### ISSUE THREAD

**Issue by geshenjibi** [yanzhenjie/AndServer#280]
地址为：http://192.168.43.1:8080/xxx.mp4
请问，mp4文件如何制定MediaType和ResponseBody 才能返回正确的相应内容？或者头信息。

**Comment by yanzhenjie** [comment]
这个还没研究过，自己晚上搜索下相关资料吧，AndServer对这个没有限制哈。
