### ISSUE TITLE
找不到Website注解

### ISSUE THREAD

**Issue by 873764182** [yanzhenjie/AndServer#282]
我使用的Kotlin,按照文档做出了修改,但是没办法使用@website.
![image](https://user-images.githubusercontent.com/11207473/88249939-8e435100-ccd8-11ea-87f0-e2b123a71f40.png)
![image](https://user-images.githubusercontent.com/11207473/88249922-7a97ea80-ccd8-11ea-876e-f55165ed437d.png)
![image](https://user-images.githubusercontent.com/11207473/88249926-7e2b7180-ccd8-11ea-9516-07ae5fa29e42.png)

**Comment by 873764182** [comment]
能否给一个完整的基于kotlin开发的示例项目

**Comment by yanzhenjie** [comment]
`@Website`注解已弃用，Website可以使用`@Config`注解来注册，请参考demo和文档。
