### ISSUE TITLE
服务启动后，ip未变的情况下，断网重连后无法访问服务

### ISSUE THREAD

**Issue by ucssi-dongxd** [yanzhenjie/AndServer#284]
我使用设备的ip地址开启server后，通过ip加端口的方式能够正常访问服务，但是设备网络断开后，再重新连接后，无法访问。日志和debug模式插卡server都是运行状态。server.isRunning() 返回的是true。想问下有解决方案吗？

**Comment by yanzhenjie** [comment]
不要指定ip地址即可。

**Comment by ucssi-dongxd** [comment]
不指定ip的情况下，localhost/127.0.0.1 支持访问吗？之前我用的v2.0现在2.1.3支持吗？
