### ISSUE TITLE
使用webwfa 

### ISSUE THREAD

**Issue by ucssi-dongxd** [yanzhenjie/AndServer#285]
server = AndServer.webServer(this)
//                    .inetAddress(NetUtil.getLocalIPAddress())
                .port(8000)
                .timeout(10, TimeUnit.SECONDS)
                //服务器监听接口
                .listener(new Server.ServerListener() {
                    @Override
                    public void onStarted() {
                        if (server.getInetAddress() != null) {
                            String hostAddress = server.getInetAddress().getHostAddress();
                            Log.e(TAG, "onStarted : server ip "+hostAddress);
                        }else{
                            Log.e(TAG, "onStarted : server is null");
                        }
                    }

                    @Override
                    public void onStopped() {
                        Log.e(TAG, "onStopped : server has stopped");
                        ServerPresenter.serverStopped(ServerService.this);
                    }

                    @Override
                    public void onException(Exception e) {
                        Log.e(TAG, "onException : " + e.getMessage());
                        ServerPresenter.serverError(ServerService.this, e.getMessage());
                    }
                })
                .build();

使用AndServer.webServer启动服务后，在启动服务成功的回调中打印日志，中提示server的hostaddress为::  （如下图），是我设置有问题吗？android系统为8.0，使用的andserver版本为2.1.3

**Comment by ucssi-dongxd** [comment]
![image](https://user-images.githubusercontent.com/61998433/88516172-7133b880-d01f-11ea-89d7-dd99d36a3980.png)

打印的端口是正常的，是我设置的端口

**Comment by yanzhenjie** [comment]
这个方法是获取你设置的ip，而不是本机的ip，你可以自己写个方法来获取。

**Comment by ucssi-dongxd** [comment]
AndServer.webServer 是必须要设置一个ip是吗？不会默认为设备的本机ip吗？我现在的情况是不设置指定的ip 运行之后，通过设备的ip地址加端口无法成功访问
