### ISSUE TITLE
默认文件上传会有文件大小限制吗

### ISSUE THREAD

**Issue by lidongyue-Frank** [yanzhenjie/AndServer#287]
前端上传了个100M的文件，提示413错误，请求太长，这个是否和服务器有关，是否有可能服务器那边不支持接收太长的文件或需要在服务端设置最大支持的文件大小之类的
Failed to load resource: the server responded with a status of 413 (Request Too Long)
![image](https://user-images.githubusercontent.com/40556686/89142029-df74ff80-d578-11ea-8eb3-7629d3357f02.png)

**Comment by yanzhenjie** [comment]
有大小限制，可以使用@Config来设置，文档和Demo里有。
