### ISSUE TITLE
AppInfo就是为了传递一个packageName吗？

### ISSUE THREAD

**Issue by JuneLeo** [yanzhenjie/AndServer#289]
大佬我看了后很懵逼，想问一下ｐａｃｋａｇｅＮａｍｅ原本可以通过ａｐｔ 的方式传递给ａｂｓｔｒａｃｔｐｒｏｃｅｓｓｅｒ呀，为什么要废好大的劲儿往里面传递呀

**Comment by yanzhenjie** [comment]
是的，我感觉那样写不友好，因为规划中插件在未来是必须的，所以放在插件里面做。

2.1.5版本开始，插件已经是必须的了。
