### ISSUE TITLE
没有找到Website注解

### ISSUE THREAD

**Issue by xiexin52k** [yanzhenjie/AndServer#293]
如题, 最新版(2.1.3)不能使用Website注解. 是移除了吗?

**Comment by miaohengju** [comment]
同问，我也没找到

**Comment by hyy12345678** [comment]
这个issue可以关了。
2.1.x之后使用@Config注解，配合WebConfig集成，如下：
* <code>@Config</code>
 * public class AppConfig implements WebConfig {
 *
 *     <code>@Override</code>
 *     public void onConfig(Context context, Delegate delegate) {
 *         Website website = ...;
 *         delegate.addWebsite(website);
 *
 *         Multipart multipart = Multipart.newBuilder()...build();
 *         delegate.setMultipart(multipart);
 *     }
 * }
