### ISSUE TITLE
AndServer 挂后台，然后玩游戏，没过多久访问就会超时

### ISSUE THREAD

**Issue by PrintNow** [yanzhenjie/AndServer#298]
MIUI 12，已对应用开启 **后台无限制**，把它挂后台，然后前台运行游戏。
用电脑去访问手机启动的 WebServer 地址，每隔2s刷新下，没过多久（大概几十秒不到），访问就超时了，从此后面请求就是一直超时

请问有什么好的解决的方法吗（我是新手）

**Comment by yanzhenjie** [comment]
看起来应该是应用挂了，那就没什么好办法拉。

**Comment by ruanbaojun1105** [comment]
所以小米是假后台啊

**Comment by gongyu123** [comment]
把作者Demo里的CoreService换成前台Service，高版本的安卓系统会杀死在后台运行的普通的Service，前台Service启动后，在状态栏可以看到一个notification，这样就不会那么容易被干掉了。

**Comment by PrintNow** [comment]
> 把作者Demo里的CoreService换成前台Service，高版本的安卓系统会杀死在后台运行的普通的Service，前台Service启动后，在状态栏可以看到一个notification，这样就不会那么容易被干掉了。

@gongyu123 好的，谢谢你的建议 : )
