### ISSUE TITLE
请问作者这个框架是否有拦截器？

### ISSUE THREAD

**Issue by huweiko** [yanzhenjie/AndServer#301]
请问作者这个框架是否有拦截器？如何使用拦截器

**Comment by yanzhenjie** [comment]
有，请在项目主页看下文档和Demo。

**Comment by zhangpo** [comment]
你好，现在的框架能实现一条日志打印出接口的入参、出参、处理时间等相关的数据吗？如果用拦截器只能输出接口名，现在我只能在我的实现方法是用拦截器打印接口名，用转换器输出入参和出参，日志里面是多条记录，如果并发没办法分析出哪条请求。

**Comment by yanzhenjie** [comment]
@zhangpo  您好，目前确实没有这样的接口，我计划添加，麻烦您单独提一个issue，感谢！
