### ISSUE TITLE
注解方式的Controller是否支持依赖注入,如Dagger和Hilt

### ISSUE THREAD

**Issue by iarray** [yanzhenjie/AndServer#306]
目前项目用的是hilt框架实现的依赖注入, 底层还是基于dagger的. 如何在拦截器或者controller里面获取容器对象

**Comment by yanzhenjie** [comment]
`Controller`和`Interceptor`必须提供无参构造方法，且每个服务器启动时只会对当前服务器保持一个实例。因此建议在构造方法内，通过一些方式去获取已经存在的对象，比如通过`Application`桥接等。另外所有接口都是一个子线程，不要在接口内直接更新UI。
