### ISSUE TITLE
非必传 参数 long int 传递问题

### ISSUE THREAD

**Issue by keaitao0321** [yanzhenjie/AndServer#313]
String param0Str = request.getParameter("id");
    if (StringUtils.isEmpty(param0Str)) {
      throw param0Str  ="";
    }
    Long param0 = null;
    try {
      param0 = Long.valueOf(param0Str);
    } catch (Throwable e) {
      throw new ParamValidateException(e);
    }

这里如果没有设置默认值，给的是空串，会报错，大神解决下

**Comment by yanzhenjie** [comment]
在该参数的注解上增加一个`defaultValue`。
