### ISSUE TITLE
Interceptor 不起作用 - 跨域

### ISSUE THREAD

**Issue by xuncai-tech** [yanzhenjie/AndServer#315]
已下是写了一个全局的跨域拦截器。但是onIntercept方法不会被调用。
不太清楚是什么原因。

@Interceptor
public class OptionsInterceptor implements HandlerInterceptor {
    public static void allow(HttpResponse response, HttpMethod... methods) {
        String methodHeader = TextUtils.join(",", methods);
        response.setHeader("Access-Control-Allow-Origin", "*");
        response.setHeader("Access-Control-Allow-Methods", methodHeader);
        response.setHeader("Access-Control-Allow-Headers", "*");
        response.setHeader("Access-Control-Allow-Credentials", "true");
        response.setHeader("Access-Control-Max-Age", "3600");
        response.setHeader("Allow", methodHeader);
    }
    /**
     * Intercept the execution of a handler.
     *
     * @param request  current request.
     * @param response current response.
     * @param handler  the corresponding handler of the current request.
     * @return true if the interceptor has processed the request and responded.
     */
    @Override
    public boolean onIntercept(@NonNull HttpRequest request, @NonNull HttpResponse response, @NonNull RequestHandler handler) throws Exception {

        HttpMethod method = request.getMethod();
        Logger.w("OptionsInterceptor onIntercept: "+method);
        if (method == OPTIONS) {
            allow(response,HttpMethod.PUT, HttpMethod.OPTIONS);
            Logger.w("OptionsInterceptor onIntercept: allow ");
            return true;
        }
        return false;
    }
}

**Comment by yanzhenjie** [comment]
#305

**Comment by xuncai-tech** [comment]
这个问题主要是因为 系统会先发现OPTIONS不被支持，直接就会报错。此时系统还未调用拦截器，所有拦截器无法生效。
