### ISSUE TITLE
只增加了一行代码，这样的逻辑才正常。

### ISSUE THREAD

**Issue by ag2s20150909** [yanzhenjie/AndServer#32]
import android.text.TextUtils;

import com.yanzhenjie.andserver.RequestHandler;
import com.yanzhenjie.andserver.handler.StorageRequestHandler;
import com.yanzhenjie.andserver.util.StorageWrapper;

import java.io.File;
import java.util.List;
import java.util.Map;

public class NewStorageWebsite extends BasicWebsite {

    /**
     * StorageWrapper.
     */
    private StorageWrapper mStorageWrapper;

    /**
     * Site root directory.
     */
    private String mRootPath;

    /**
     * Storage Website.
     *
     * @param rootPath site root directory in assets, such as: {@code "/storage/sdcard/google/website"}.
     */
    public NewStorageWebsite(String rootPath) {
        super(rootPath);
        if (TextUtils.isEmpty(rootPath)) throw new NullPointerException("The RootPath can not be null.");
        this.mRootPath = trimSlash(rootPath);
        mStorageWrapper = new StorageWrapper();
    }

    @Override
    public void onRegister(Map<String, RequestHandler> handlerMap) {
        RequestHandler indexHandler = new StorageRequestHandler(INDEX_HTML);
        handlerMap.put("", indexHandler);
        handlerMap.put(mRootPath, indexHandler);
        handlerMap.put(mRootPath + File.separator, indexHandler);
        handlerMap.put(mRootPath + File.separator + INDEX_HTML, indexHandler);

        List<String> pathList = mStorageWrapper.scanFile(getHttpPath(mRootPath));
        for (String path : pathList) {
            RequestHandler requestHandler = new StorageRequestHandler(path);
	    path=path.substring(path.indexOf(mRootPath)+mRootPath.length(),path.length());
            handlerMap.put(path, requestHandler);
        }
    }

}

**Comment by yanzhenjie** [comment]
#15
