### ISSUE TITLE
本机不上网，没有被分配IP，开启server后，本机客户端如何访问本机Server

### ISSUE THREAD

**Issue by quzn** [yanzhenjie/AndServer#327]
客户端用localhost:端口号访问不到

**Comment by yanzhenjie** [comment]
启动server时不要指定监听的ip，server机器联网后客户端就用这个机器现在分配到的ip访问即可。

**Comment by quzn** [comment]
本机不联网的状态下，就无法访问了么？

**Comment by yanzhenjie** [comment]
本机访问本机的server，没有ip的时候用127.0.0.1，其他机器访问不到，除非在一个局域网内。

**Comment by quzn** [comment]
http://127.0.0.1:8080/ 访问不到
