### ISSUE TITLE
无法启动服务，地址已被使用

### ISSUE THREAD

**Issue by wbr0603** [yanzhenjie/AndServer#333]
堆栈：
11-19 10:41:46.775 I/ZSGT    ( 3652): server start
11-19 10:41:46.787 I/ZSGT    ( 3652): server onExceptionbind failed: EADDRINUSE (Address already in use)
11-19 10:41:46.788 W/System.err( 3652): java.net.BindException: bind failed: EADDRINUSE (Address already in use)
11-19 10:41:46.788 W/System.err( 3652): 	at libcore.io.IoBridge.bind(IoBridge.java:99)
11-19 10:41:46.789 W/System.err( 3652): 	at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:132)
11-19 10:41:46.789 W/System.err( 3652): 	at java.net.ServerSocket.bind(ServerSocket.java:336)
11-19 10:41:46.790 W/System.err( 3652): 	at org.apache.httpcore.impl.bootstrap.HttpServer.start(HttpServer.java:115)
11-19 10:41:46.790 W/System.err( 3652): 	at com.yanzhenjie.andserver.server.BasicServer$1.run(BasicServer.java:106)
11-19 10:41:46.790 W/System.err( 3652): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-19 10:41:46.791 W/System.err( 3652): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-19 10:41:46.791 W/System.err( 3652): 	at java.lang.Thread.run(Thread.java:818)
11-19 10:41:46.792 W/System.err( 3652): Caused by: android.system.ErrnoException: bind failed: EADDRINUSE (Address already in use)
11-19 10:41:46.792 W/System.err( 3652): 	at libcore.io.Posix.bind(Native Method)
11-19 10:41:46.792 W/System.err( 3652): 	at libcore.io.ForwardingOs.bind(ForwardingOs.java:56)
11-19 10:41:46.793 W/System.err( 3652): 	at libcore.io.IoBridge.bind(IoBridge.java:97)
11-19 10:41:46.793 W/System.err( 3652): 	... 7 more

代码：
public synchronized void startServer(){
        if(mServer == null || !mServer.isRunning()){
            mServer = AndServer.serverBuilder(g_appContext)
                    .port(8080)
                    .timeout(10, TimeUnit.SECONDS)
                    .listener(new Server.ServerListener() {
                        @Override
                        public void onStarted() {
                            Log.i("aaa", "server start");
                            InetAddress address = NetUtils.getLocalIPAddress();
                            if(address!=null && address.getHostAddress()!=null){
                                Log.d("aaa",address.getHostAddress());
                            }
                        }

                        @Override
                        public void onStopped() {
                            Log.i("aaa", "server stop");
                        }

                        @Override
                        public void onException(Exception e) {
                            Log.i("aaa", "server onException"+ e.getMessage());
                            e.printStackTrace();
                            if (mServer!=null){
                                mServer.shutdown();
                                mServer = null;
                            }
                        }
                    })
                    .build();
            mServer.startup();
        }
    }

**Comment by wbr0603** [comment]
ps:使用lsof和ps命令查看，设备端口没有被占用

**Comment by DevinCGB** [comment]
应该是andserver本身问题，我尝试切换端口重新运行，先提示运行成功，然后报错java.net.BindException: bind failed: EADDRINUSE (Address already in use)

**Comment by DevinCGB** [comment]
好像只能用8080端口
