### ISSUE TITLE
StorageWebsite  中文路径无法访问

### ISSUE THREAD

**Issue by leielyq** [yanzhenjie/AndServer#34]
中文路径如何启动服务器

**Comment by yanzhenjie** [comment]
不能访问是什么表现，有什么错误？

另外你可以试试新版，支持热插拔了，很多新特性。

**Comment by wenoptics** [comment]
中文路径的StorageWebsite会报404
如，能访问`http://172.20.10.8:8081/main.html`
但是`http://172.20.10.8:8081/相片/HEAH9945.JPG`则404:
> The resource [/%E7%9B%B8%E7%89%87/HEAH9945.JPG] does not exist.

使用的是v1.1.1

**Comment by leielyq** [comment]
我尝试将中文编码，依然无效  ，  只能加一个过滤中文以及空格的选项了。有空问问后台中文路径如何解决。
