### ISSUE TITLE
为什么运行成功后 点open browser 显示 The resource [/] is not found?

### ISSUE THREAD

**Issue by cxd1314** [yanzhenjie/AndServer#340]
运行后要做什么配置呢？

**Comment by cxd1314** [comment]
The resource [/] is not found 是哪里资源配置有问题吗？

**Comment by e3control-zhanglimin** [comment]
同样的问题，有什么解决办法吗

**Comment by andyxm** [comment]
参考#342

**Comment by yanzhenjie** [comment]
具体情况可以贴下代码，因为demo没问题，我也没法判断你的情况

**Comment by andyxm** [comment]
@yanzhenjie `    public void register(Register register, String group)
        throws InstantiationException, IllegalAccessException {
        AssetManager manager = mContext.getAssets();
        String[] pathList = null;
        try {
            pathList = manager.list("");
        } catch (IOException e) {
            e.printStackTrace();
        }
        if (pathList == null || pathList.length == 0) {
            return;
        }
        for (String path: pathList) {
            if (path.endsWith(ANDSERVER_REGISTER_SUFFIX)) {
                //String packageName = path.substring(0, path.indexOf(ANDSERVER_REGISTER_SUFFIX));
                String packageName = path.substring(0, path.lastIndexOf(ANDSERVER_REGISTER_SUFFIX));
                for (String clazz: REGISTER_LIST) {
                    String className = String.format("%s%s%s", packageName, PROCESSOR_PACKAGE, clazz);
                    registerClass(register, group, className);
                }
            }
        }
    }`

**Comment by andyxm** [comment]
@yanzhenjie 

    public void register(Register register, String group)
        throws InstantiationException, IllegalAccessException {
        AssetManager manager = mContext.getAssets();
        String[] pathList = null;
        try {
            pathList = manager.list("");
        } catch (IOException e) {
            e.printStackTrace();
        }

        if (pathList == null || pathList.length == 0) {
            return;
        }

        for (String path: pathList) {
            if (path.endsWith(ANDSERVER_REGISTER_SUFFIX)) {
                String packageName = path.substring(0, path.indexOf(ANDSERVER_REGISTER_SUFFIX));
                String packageName = path.substring(0, path.lastIndexOf(ANDSERVER_REGISTER_SUFFIX));
                for (String clazz: REGISTER_LIST) {
                    String className = String.format("%s%s%s", packageName, PROCESSOR_PACKAGE, clazz);
                    registerClass(register, group, className);
                }
            }
        }
    }

**Comment by andyxm** [comment]
public void register(Register register, String group)
        throws InstantiationException, IllegalAccessException {
        AssetManager manager = mContext.getAssets();
        String[] pathList = null;
        try {
            pathList = manager.list("");
        } catch (IOException e) {
            e.printStackTrace();
        }

        if (pathList == null || pathList.length == 0) {
            return;
        }

        for (String path: pathList) {
            if (path.endsWith(ANDSERVER_REGISTER_SUFFIX)) {
                //String packageName = path.substring(0, path.indexOf(ANDSERVER_REGISTER_SUFFIX));
                String packageName = path.substring(0, path.lastIndexOf(ANDSERVER_REGISTER_SUFFIX));
                for (String clazz: REGISTER_LIST) {
                    String className = String.format("%s%s%s", packageName, PROCESSOR_PACKAGE, clazz);
                    registerClass(register, group, className);
                }
            }
        }
    }

**Comment by andyxm** [comment]
@yanzhenjie 
ComponentRegister的register方法中将indexOf改成lastIndexOf
public void register(Register register, String group)
    throws InstantiationException, IllegalAccessException {
    AssetManager manager = mContext.getAssets();
    String[] pathList = null;
    try {
        pathList = manager.list("");
    } catch (IOException e) {
        e.printStackTrace();
    }

    if (pathList == null || pathList.length == 0) {
        return;
    }

    for (String path: pathList) {
        if (path.endsWith(ANDSERVER_REGISTER_SUFFIX)) {
            //String packageName = path.substring(0, path.indexOf(ANDSERVER_REGISTER_SUFFIX));
            String packageName = path.substring(0, path.lastIndexOf(ANDSERVER_REGISTER_SUFFIX));
            for (String clazz: REGISTER_LIST) {
                String className = String.format("%s%s%s", packageName, PROCESSOR_PACKAGE, clazz);
                registerClass(register, group, className);
            }
        }
    }
}

**Comment by yanzhenjie** [comment]
大家统一在 #342 跟进吧.
