### ISSUE TITLE
2.1.6升级到2.1.7出现the resource [xxx] is not found的问题

### ISSUE THREAD

**Issue by yfn020** [yanzhenjie/AndServer#342]
@RestController 注解的页面，在2.1.6没问题，升级到2.1.7出现找不到资源的问题，退回2.1.6问题解决。

**Comment by andyxm** [comment]
ComponentRegister中path.substring(0, path.indexOf(ANDSERVER_REGISTER_SUFFIX))改成path.substring(0, path.lastIndexOf(ANDSERVER_REGISTER_SUFFIX));

**Comment by yanzhenjie** [comment]
@yfn020  解决了吗？下次提问可以贴下代码，本身沟通就比较低效

**Comment by andyxm** [comment]
@yanzhenjie 有没有一个交流的群呢,这样交流感觉效率很低

**Comment by lancewoo** [comment]
> 
> 
> @yfn020 解决了吗？下次提问可以贴下代码，本身沟通就比较低效

这个说的是直接在浏览器里打开的情况，2.1.7的示例代码确实有这情况。

**Comment by singlemdd** [comment]
就是包名 的问题 ComponentRegister类中private static final String ANDSERVER_REGISTER_SUFFIX = ".andserver";  
 String packageName = path.substring(0, path.indexOf(ANDSERVER_REGISTER_SUFFIX));
sample实例中包名中也含有.andserver，改一下包名不要出现.andserver就行了，
com.yanzhenjie.andserver.sample
