### ISSUE TITLE
如何配置域名？

### ISSUE THREAD

**Issue by huangdali** [yanzhenjie/AndServer#344]
我们的应用场景：android作为服务器，并且安卓设备会开启热点，其他手机通过热点连接与其通讯，服务器的地址就是固定的：http://192.168.43.1:port，不用192.168.43.1来访问，如何设置域名呢？这种应用场景android本身就是网关了，设置域名应该只能从服务器本身设置了吧？

**Comment by HuRuWo** [comment]
没有公网ip无法配置域名 只能做内网穿透 或者 映射到公网上去

**Comment by HuRuWo** [comment]
加一层代理就行

**Comment by huangdali** [comment]
@HuRuWo 请问一下怎么加?我试了下面配置也不行哦

```java
Server server = AndServer.proxyServer()
    .addProxy("192.168.43.1", "http://www.refueller.com")
    .port(80)
    .timeout(10, TimeUnit.SECONDS)
    .build();
```

**Comment by HuRuWo** [comment]
> @HuRuWo 请问一下怎么加?我试了下面配置也不行哦
> 
> ```java
> Server server = AndServer.proxyServer()
>     .addProxy("192.168.43.1", "http://www.refueller.com")
>     .port(80)
>     .timeout(10, TimeUnit.SECONDS)
>     .build();
> ```

我说的代理不是这种代理 域名要与公网ip绑定才能访问，你要做内网穿透。让公网上也能访问到你的域名，首先租个公网服务器

再用工具

类似的工具有很多 frp ngrok 或者直接付费的花生壳(免服务器的)

**Comment by HuRuWo** [comment]
如果你只是想在内网通过域名访问 倒不用这么麻烦 直接在要访问的机子里加一行dns解析记录即可。

**Comment by yanzhenjie** [comment]
本机或者局域网路由器加个域名解析，映射到这个服务端手机ip就可以，或者直接外网买个域名，并解析到这个ip也可以访问；
