### ISSUE TITLE
访问本地的一个文件流给应用,期望返回的是206,但是放回的是200

### ISSUE THREAD

**Issue by andyxm** [yanzhenjie/AndServer#346]
代码如下:
@RestController
public class FileController {
    @GetMapping(path = "/")
    ResponseBody decodeVideo(@QueryParam("site") String site,@QueryParam("type") String type) throws FileNotFoundException {
        Log.e("FileController", "site: "+site +",type="+type);
        if (!TextUtils.equals(type,"file")){
            return null;
        }
        File file = new File(site);
        if (!file.exists()){
            return null;
        }
        FileDecodeStreamBody fileBody = null;
        if (file.exists()) {
            fileBody = new FileDecodeStreamBody(new FileInputStream(file),file.length());
        }
        ResponseBody responseBody = fileBody;
        return responseBody;
    }
-------------------------------------------------------------------------------------
public class FileDecodeStreamBody implements ResponseBody {

    private InputStream mStream;
    private long mLength;
    private MediaType mMediaType;

    public FileDecodeStreamBody(InputStream stream) {
        this(stream, MediaType.APPLICATION_OCTET_STREAM);
    }

    public FileDecodeStreamBody(InputStream stream, long length) {
        this(stream, length, MediaType.APPLICATION_OCTET_STREAM);
    }

    public FileDecodeStreamBody(InputStream stream, MediaType mediaType) {
        this(stream, 0, mediaType);
    }

    public FileDecodeStreamBody(InputStream stream, long length, MediaType mediaType) {
        this.mStream = stream;
        this.mLength = length;
        this.mMediaType = mediaType;
    }

    @Override
    public boolean isRepeatable() {
        return false;
    }

    @Override
    public long contentLength() {
        if (mLength == 0 && mStream instanceof FileInputStream) {
            try {
                mLength = ((FileInputStream) mStream).getChannel().size();
                return mLength;
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        return mLength;
    }

    @Nullable
    @Override
    public MediaType contentType() {
        return mMediaType;
    }

    @Override
    public void writeTo(@NonNull OutputStream output) throws IOException {
        Log.e("FileDecodeBody", "writeTo: 11111");
        long position=0;
        int len;
        byte[] buffer = new byte[4096];
        while ((len = mStream.read(buffer)) != -1) {
            VideoDecodeControl.TransData(position, buffer, len);
            output.write(buffer, 0, len);
            output.flush();
            position+=len;
        }
        IOUtils.closeQuietly(mStream);
        Log.e("FileDecodeBody", "writeTo: 222222");
    }
}

服务接收一个访问视频的地址,期望返回的是206而不是200,如何改进能实现此功能

**Comment by yanzhenjie** [comment]
在别的问题中看到你已解决；
