### ISSUE TITLE
API 19以下不能运行

### ISSUE THREAD

**Issue by Jackky-Hou** [yanzhenjie/AndServer#347]
NoClassDefFoundError: java.nio.charset.StandardCharsets

**Comment by yanzhenjie** [comment]
AndServer中没有使用这个类，应该是你自己的代码；你下次描述问题可以详细点，让人不知道怎么排查；

**Comment by Jackky-Hou** [comment]
不好意思，我之前也没有定位到问题，所以没说清楚。
StringBody类里面，有Charsets.UTF_8，这个值引用了java.nio.charset.StandardCharsets，改成Charset.forName("UTF-8")就可以了！
