### ISSUE TITLE
Execution failed for task ':app:compileDebugJavaWithJavac'. > javax/activation/MimeTypeParseException

### ISSUE THREAD

**Issue by ychong996** [yanzhenjie/AndServer#349]
Execution failed for task ':app:compileDebugJavaWithJavac'.
> javax/activation/MimeTypeParseException

当前项目：

 compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

classpath 'com.android.tools.build:gradle:3.4.3'

distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-bin.zip

**Comment by yanzhenjie** [comment]
AndServer api、plugin、annotation、processor的版本都要统一；

**Comment by 360060316** [comment]
我也出现这个问题了而且版本统一了
