### ISSUE TITLE
如果需要在 RequestHandler 里的handler 回调里面调用其他的异步任务，结束后再返回结果怎么处理，谢谢

### ISSUE THREAD

**Issue by zxq9133** [yanzhenjie/AndServer#35]
目前我测试的是 handle 同步执行完后就直接结束了，再调用 response.setEntity 方法无效。我目前是采用阻塞的方式，不让handler提前执行结束，问下还有没有其他方法，谢谢

**Comment by yanzhenjie** [comment]
提醒一下：`RequestHandler`本身就是在子线程中执行的。  

当然我只是提醒，题主可能是需要用户确认之类的，所以需要异步，你可以采用线程阻塞的方式来做，没有问题的。
