### ISSUE TITLE
访问:http://127.0.0.1:8080/test.mp4,让其可以返回206

### ISSUE THREAD

**Issue by andyxm** [yanzhenjie/AndServer#353]
有这样一个功能
1 由于视频文件是加密的
2 所以打算使用模拟http请求方式去在服务端对视频进行解密(因此打算本地搭建一个http服务对视频解密)
3 解密后在使用安卓进行播放
目前遇到的难点
1 每次请求数据直接返回200而不是206的方式
2 如何处理这种大一些的视频文件,让其返回206

**Comment by Lushiju** [comment]
可以参考这个问题回答https://github.com/yanzhenjie/AndServer/issues/78

**Comment by yanzhenjie** [comment]
@Lushiju 正解；

不过你这个功能可以不用AndServer啊，正常客户端请求这个地址解密播放就好了，干嘛还得让AndServer去转发一下请求呢；

**Comment by andyxm** [comment]
刚才借鉴了下#84用的就是直接请求的地址,解密视频的&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhenjie Yan"<notifications@github.com&gt;; 
发送时间: 2021年1月18日(星期一) 下午5:07
收件人: "yanzhenjie/AndServer"<AndServer@noreply.github.com&gt;; 
抄送: "『燭火夜光』"<407311996@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yanzhenjie/AndServer] 访问:http://127.0.0.1:8080/test.mp4,让其可以返回206 (#353)





 
@Lushiju 正解；
 
不过你这个功能可以不用AndServer啊，正常客户端请求这个地址解密播放就好了，干嘛还得让AndServer去转发一下请求呢；

**Comment by yanzhenjie** [comment]
好的

**Comment by andyxm** [comment]
@yanzhenjie 我这用转发可以播放,但是直接客户端请求没有反应
这是拦截的代码
![image](https://user-images.githubusercontent.com/12179898/104900895-9ba37480-59b7-11eb-91d1-f8a70e4082ef.png)
这是请求的代码(实际是一样的)
![image](https://user-images.githubusercontent.com/12179898/104900955-b544bc00-59b7-11eb-8304-7bd55b38bdf9.png)

**Comment by andyxm** [comment]
@Lushiju  而且还有一个问题,我这个加密的文件不是.mp4结尾的,是一个以.szem结尾的视频,无法播放

**Comment by andyxm** [comment]
已解决这个问题,需要处理一个类似position的一个偏移量问题

**Comment by AzAdkins** [comment]
@andyxm 最终怎么解决的？我也需要视频支持边下边播，但实际请求都是200，无法206
