### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by Angels-group** [yanzhenjie/AndServer#356]
Good day!
Tell me how I can add a site to CORS exceptions or disable it completely?

`Access to XMLHttpRequest at 'http://192.168.1.1:8080/myMethod' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by Angels-group** [comment]
@CrossOrigin solve my problem 
(2.7.1)

**Comment by JoeyJCB** [comment]
could u tell me how to solve this problem?

**Comment by JoeyJCB** [comment]
@Angels-group
