### ISSUE TITLE
Mapping 如何使用通配符？

### ISSUE THREAD

**Issue by Ernest-su** [yanzhenjie/AndServer#358]
如 @PostMapping("/card/detail/*")

**Comment by yanzhenjie** [comment]
```java
    @PostMapping(path = "/get/{userId}")
    public String info(@PathVariable(name = "userId") String userId) {
        return userId;
    }
```

**Comment by Ernest-su** [comment]
可能我表达得不够清楚，我想要的是detail/后面接任意字符串，@PostMapping(path = "/get/{userId}") 这种方式限定了userId是某一个字符串了

**Comment by yanzhenjie** [comment]
就是符合path规则的任意字符串，如果想扩大字符范围，就用query。

**Comment by Ernest-su** [comment]
我的场景不是query的场景。设想一下：
客户端请求有可能是detail/a，detail/b，detail/1234，detail/xxx，
我不能提前预知他会传什么字符串，但是我想统一返回一个mock的结果。

**Comment by yanzhenjie** [comment]
我想上面的回复已经很清楚了，能完全满足的你需求。
