### ISSUE TITLE
我想要把文件跟参数跟表单一起提交，但是失败了？

### ISSUE THREAD

**Issue by 1321365765** [yanzhenjie/AndServer#36]
@yanzhenjie 
我在 RequestUploadHandler  
方法
public void handle(HttpRequest request, HttpResponse response, HttpContext context) throws HttpException
执行 Map<String, String> params = HttpRequestParser.parse(request);
程序直接崩溃了，并且没有看到错误日志

**Comment by nantofu** [comment]
应该是多次读取 HTTPContent 导致的，我的解决方案是通过 header 传递参数。就是不知道有没有更好的方案。

**Comment by yanzhenjie** [comment]
既然是上传文件，肯定不能用题主的方法解析了，Demo中是有上传文件时拿到其它参数的例子的。

**Comment by 1321365765** [comment]
List<FileItem> fileItems = fileUpload.parseRequest(new HttpUploadContext((HttpEntityEnclosingRequest) request));
 if (!fileItem.isFormField()) {
fileItem.getString();
}
