### ISSUE TITLE
局域网内，手机搭建服务器，浏览器下载很慢

### ISSUE THREAD

**Issue by showwaychen** [yanzhenjie/AndServer#363]
非常感谢大佬开源如此优秀的项目。
     但使用的时候发现搭建的服务器，浏览器下载很慢，只有1M左右，请问如何去提升这个速度，
   谢谢。

**Comment by yanzhenjie** [comment]
目前我能想到的，框架上做不了什么了，我猜测是不是局域网网络有什么设置？或者局域网本身的传输速度有限制？从这方面查一下。
另外非常重要的一点，和手机性能有关系，和手机IO的速度有关系，和手机的网络传输速度有关系。

可以换个性能好一点的手机试试，也可以换个网络环境试试（局域网）。

**Comment by showwaychen** [comment]
> 目前我能想到的，框架上做不了什么了，我猜测是不是局域网网络有什么设置？或者局域网本身的传输速度有限制？从这方面查一下。
> 另外非常重要的一点，和手机性能有关系，和手机IO的速度有关系，和手机的网络传输速度有关系。
> 
> 可以换个性能好一点的手机试试，也可以换个网络环境试试（局域网）。

好的，我研究研究。
