### ISSUE TITLE
使用NewStorageWebsite无法正常下载视频@yanzhenjie @ag2s20150909

### ISSUE THREAD

**Issue by OnlyYouMyLove** [yanzhenjie/AndServer#37]
使用StorageWebsite的时候，HTML是这样的http://172.12.123.23:8000/www/1/2/a/index.html，使用NewStorageWebsite之后，HTML是这样的http://172.12.123.23:8000/index.html，而且可以接收到SD下的存储路径下的视频文件的信息，但是使用StorageWebsite，视频可以正常下载，使用NewStorageWebsite无法正常下载。@yanzhenjie @ag2s20150909 
       ` `  String path = SD卡的目录;
        AndServer andServer = new AndServer.Build()
                .port(8080)
                .timeout(10 * 1000)
                .registerHandler("login", new RequestLoginHandler(mData))
                .website(new NewStorageWebsite(path))
                .build();
        mServer = andServer.createServer();   ` ` 

网站的信息，我在assets下有，而且copy到了sd卡，可以使用StorageWebsite，并且使用http://172.12.123.23:8000/www/1/2/a/index.html访问到SD卡里面的视频文件，下载也正常，但是访问index.html的地址太长了！想缩短，用了NewStorageWebsite，但是不能让sd下的视频正常下载，求解，非常感谢！

我的微信fkq339 随时可以联系我。

**Comment by yanzhenjie** [comment]
之前忘记回复了，你提了这个问题之后五天就发布了新版本，新版本应该会给你惊喜，你可以试试。
