### ISSUE TITLE
集成到项目中后直接运行没问题，打包后会出现NoClassDefFoundError

### ISSUE THREAD

**Issue by jxxfli** [yanzhenjie/AndServer#373]
经过测试，添加完整的依赖或者只添加   classpath 'com.yanzhenjie.andserver:plugin:2.1.9' 再打包apk，安装运行直接崩溃,提示NoClassDefFoundError，报错的内容是其他第三方的架包内的R文件资源引用，把上面的依赖注释掉重新打包安装运行就没事。开启分包与关闭分包都会有这个问题，是不是和我项目的其他第三方依赖配置有冲突。

**Comment by yanzhenjie** [comment]
方法数超限了，只是刚好引入本项目后超限，本质上和本项目无关。
