### ISSUE TITLE
如何在网页中加载sdcard中的图片？

### ISSUE THREAD

**Issue by kong-jing** [yanzhenjie/AndServer#38]
想要保存图片到sdcard中，在网页中加载这个图片。

**Comment by weituotian** [comment]
怎么搞呢？

**Comment by kong-jing** [comment]
[here](https://github.com/yanzhenjie/AndServer/blob/master/sample/src/main/java/com/yanzhenjie/andserver/sample/handler/ImageHandler.java#L66)

可以获取到bitmap，把整个工程放到sdcard中试试
