### ISSUE TITLE
如何使用443端口？

### ISSUE THREAD

**Issue by 6YingJie** [yanzhenjie/AndServer#380]
现在设置443端口会报java.net.BindException: Permission denied。查了下是root用户才能使用1024以下端口号，请问这个有处理方法吗？

**Comment by yanzhenjie** [comment]
使用什么端口AndServer没有限制，只要系统允许的都可以；443端口是用于SSL的，也就是说需要启动HTTPS，在AndServer启动的时候可以调用`sslContext(SSLContext)`和`sslSocketInitializer(SSLSocketInitializer)`去初始化HTTPS，SSLContext是Java通用接口，网上资料非常多，具体题主可以自行研究下。
