### ISSUE TITLE
如何在Controller层引入Android的上下文对象呢？

### ISSUE THREAD

**Issue by wqtang2017** [yanzhenjie/AndServer#381]
举个栗子：我想在login方法里 用到context咋整呢？

@RestController
public class UserController {

    @PostMapping("/login")
    public String login(@RequestParam("account") String account,
        @RequestParam("password") String password) {

        if(...) {
            return "Successful";
        }
        return "Failed";
    }
}

**Comment by yanzhenjie** [comment]
sample里面有，文档里面也有，下次先看下文档再提问。
```java
@RestController
public class UserController {

    @PostMapping("/login")
    public String login(Context context,
                        @RequestParam("account") String account,
                        @RequestParam("password") String password) {

        if(...) {
            return "Successful";
        }
        return "Failed";
    }
}
```
