### ISSUE TITLE
作者能不能给个请求示例

### ISSUE THREAD

**Issue by donghegit** [yanzhenjie/AndServer#382]
谢谢🙏

**Comment by wqtang2017** [comment]
下载源码跑一下，一大堆示例

**Comment by donghegit** [comment]
好的我谢谢 我问的是网络请求 client的端的示例



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wqtang2017 ***@***.***&gt;
发送时间: 2021年5月13日 12:23
收件人: yanzhenjie/AndServer ***@***.***&gt;
抄送: donghegit ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[yanzhenjie/AndServer] 作者能不能给个请求示例 (#382)
