### ISSUE TITLE
The resource xxx is not found

### ISSUE THREAD

**Issue by yourback** [yanzhenjie/AndServer#384]
Android Studio 4.2.1

Gradle Plugin version 4.1.2
Gradle verion 6.5

`@RestController
class UserController {

    @PostMapping("/user/login")
    fun login(
        @RequestParam("account") account: String,
        @RequestParam("password") password: String
    ): String {`

`@RestController
@RequestMapping(path = ["/user"])
class UserController {

    @PostMapping("/login")
    fun login(
        @RequestParam("account") account: String,
        @RequestParam("password") password: String
    ): String {`

上面两种都不可以用，
浏览器访问都是
The resource xxx is not found

库版本是最新的2.1.9

**Comment by yanzhenjie** [comment]
运行下demo看是不是正常的，如果正常检查下你访问的路径对不对，还查不出的话，把访问路径贴一下我看看。

**Comment by yourback** [comment]
我下载了咱们的demo   导入错误 
import javax.activation.MimeType;
import javax.activation.MimeTypeParseException;

在simple build.gradle 中添加了下面的库一样编译不过
implementation 'javax.activation:javax.activation-api:1.2.0'


所以新建了个项目集成了以下，环境和上面说的一致


> override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        binding = ActivityMainBinding.inflate(layoutInflater)

        setContentView(binding.root)


        val server = AndServer.webServer(this)
            .port(8080)
            .timeout(10, TimeUnit.SECONDS)
            .listener(object : Server.ServerListener {
                override fun onException(e: Exception?) {
                    Log.d(TAG, "onException: 服务器启动失败，出错了")
                    e?.printStackTrace()
                }

                override fun onStarted() {
                    Log.d(TAG, "onStarted: 服务器启动成功，正在运行")
                }

                override fun onStopped() {
                    Log.d(TAG, "onStopped: 服务器停止成功")
                }

            })
            .build()


        binding.button.apply {
            text = "启动服务"
        }.setOnClickListener {
            Log.d(TAG, "onCreate: 启动服务")
            server.startup()
        }

        binding.button2.apply {
            text = "关闭服务"
        }.setOnClickListener {
            Log.d(TAG, "onCreate: 关闭服务")
            server.shutdown()
        }
}
    

> `@RestController
@RequestMapping(path = ["/user"])
class UserServer {

    @PostMapping("/aa")
    fun aa(): String {
        Log.d(TAG, "aa: 服务器收到消息")
        return "aa"
    }
}`

我用虚拟器和真机都跑了一遍
虚拟机Android 10  真机Android 11
启动和关闭都没有问题，

用浏览器输入的地址是：
127.0.0.1:8080/user/aa

如果启动成功后  显示
The resource xxx is not found

关闭后显示
拒绝访问，这个没有问题

**Comment by wl-go** [comment]
![bug](https://user-images.githubusercontent.com/58496952/119750963-e89ad880-becc-11eb-9604-020c248a1e5f.png)

不要使用Android studio 自带的jdk，自带的里面注解不全，配置自己下载的jdk

**Comment by yourback** [comment]
> ![bug](https://user-images.githubusercontent.com/58496952/119750963-e89ad880-becc-11eb-9604-020c248a1e5f.png)
> 
> 不要使用Android studio 自带的jdk，自带的里面注解不全，配置自己下载的jdk

我下载了JDK8后自己配置之后编译不过报错，然后下载了JDK11和15，问题一样的没有解决。。

JDK11路径是这个   F:\software\OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9\jdk-11.0.11+9

**Comment by wl-go** [comment]
> > ![bug](https://user-images.githubusercontent.com/58496952/119750963-e89ad880-becc-11eb-9604-020c248a1e5f.png)
> > 不要使用Android studio 自带的jdk，自带的里面注解不全，配置自己下载的jdk
> 
> 我下载了JDK8后自己配置之后编译不过报错，然后下载了JDK11和15，问题一样的没有解决。。
> 
> JDK11路径是这个 F:\software\OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9\jdk-11.0.11+9

可以检测一下这个，我昨天就是，启动成功后 显示The resource xxx is not found，原因就是注解的controller没有被识别出来，就是jdk里面少了这些
![Uploading  bug.png…]()

**Comment by yourback** [comment]
> 不要使用Android studio 自带的jdk，自带的里面注解不全，配置自己下载的jdk
> 
> 我下载了JDK8后自己配置之后编译不过报错，然后下载了JDK11和15，问题一样的没有解决。。
> 
> JDK11路径是这个 F:\software\OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9\jdk-11.0.11+9
> 
> 可以检测一下这个，我昨天就是，启动成功后 显示The resource xxx is not found，原因就是注解的controller没有被识别出来，就是jdk里面少了这些

下面的图片没显示出来，老哥你用的是JDK哪个版本？
是从清华镜像下载的么？

**Comment by wl-go** [comment]
> > 不要使用Android studio 自带的jdk，自带的里面注解不全，配置自己下载的jdk
> > 我下载了JDK8后自己配置之后编译不过报错，然后下载了JDK11和15，问题一样的没有解决。。
> > JDK11路径是这个 F:\software\OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9\jdk-11.0.11+9
> > 可以检测一下这个，我昨天就是，启动成功后 显示The resource xxx is not found，原因就是注解的controller没有被识别出来，就是jdk里面少了这些
> 
> 下面的图片没显示出来，老哥你用的是JDK哪个版本？
> 是从清华镜像下载的么？

我用的openJDK 1.8
你看看你的jdk 全不全？
![ bug](https://user-images.githubusercontent.com/58496952/119786098-688f6580-bf02-11eb-9ebd-0fcc05d661eb.png)

**Comment by yourback** [comment]
> > > 不要使用Android studio 自带的jdk，自带的里面注解不全，配置自己下载的jdk
> > > 我下载了JDK8后自己配置之后编译不过报错，然后下载了JDK11和15，问题一样的没有解决。。
> > > JDK11路径是这个 F:\software\OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9\jdk-11.0.11+9
> > > 可以检测一下这个，我昨天就是，启动成功后 显示The resource xxx is not found，原因就是注解的controller没有被识别出来，就是jdk里面少了这些
> > 
> > 
> > 下面的图片没显示出来，老哥你用的是JDK哪个版本？
> > 是从清华镜像下载的么？
> 
> 我用的openJDK 1.8
> 你看看你的jdk 全不全？
> ![ bug](https://user-images.githubusercontent.com/58496952/119786098-688f6580-bf02-11eb-9ebd-0fcc05d661eb.png)

我去官网下载了JDK，然后把版本改成2。1。1，就好了。
感谢大哥热心回答，感觉应该就是注释的问题，没有被识别到。
