### ISSUE TITLE
AndServer 下载服务器

### ISSUE THREAD

**Issue by xiaoqiang008** [yanzhenjie/AndServer#390]
只看到上传服务，请问怎么搭建文件服务器呢？

**Comment by yanzhenjie** [comment]
可以认真看下demo和文档；方式1. 每个api都可以理解为一个文件，这里面操作空间很大，方式2. website，这里有现成的服务，文档里有说明的

**Comment by xiaoqiang008** [comment]
你好！可以帮忙指一下demo哪里么，我在demo里没有找到，谢谢！

**Comment by xiaoqiang008** [comment]
不用了，我找到了，谢谢！
