### ISSUE TITLE
MultipartFile接收的文件找不到

### ISSUE THREAD

**Issue by EastwoodLeon** [yanzhenjie/AndServer#393]
Config中配置了uploadTempDir，调用上传接口后，在uploadTempDir中找不到上传的文件，文件夹是空的，是怎么回事？

**Comment by yanzhenjie** [comment]
你只说有问题，别人怎么帮你排查问题是什么呢，最少也得贴个代码什么的吧

**Comment by EastwoodLeon** [comment]
下面是配置
`@Config
public class AppConfig implements WebConfig {
    @Override
    public void onConfig(Context context, Delegate delegate) {
        // 自定义配置表单请求和文件上传的条件
        delegate.setMultipart(
                Multipart.newBuilder()
                .allFileMaxSize(1024 * 1024 * 100) // 单个请求上传文件总大小
                .fileMaxSize(1024 * 1024 * 100) // 单个文件的最大大小
                .maxInMemorySize(1024 * 10) // 保存上传文件时buffer大小
                .uploadTempDir(new File(context.getCacheDir(), "_server_upload_cache_")) // 文件保存目录
                .build()
        );
    }
}`


下面是接口
@PostMapping(path = "/upload", produces = "application/json;charset=utf-8")
    public synchronized String upload(
            @RequestParam("image") MultipartFile file
    ) {

        BaseResponse<String> response = new BaseResponse<>();

        response.setSuccessful("接收成功");

        return GsonUtils.toJson(response);
    }

但是这里new File(context.getCacheDir(), "_server_upload_cache_")的内容是空的，没有文件

**Comment by EastwoodLeon** [comment]
下面是配置
@Config
public class AppConfig implements WebConfig {
    @Override
    public void onConfig(Context context, Delegate delegate) {
        // 自定义配置表单请求和文件上传的条件
        delegate.setMultipart(
                Multipart.newBuilder()
                .allFileMaxSize(1024 * 1024 * 100) // 单个请求上传文件总大小
                .fileMaxSize(1024 * 1024 * 100) // 单个文件的最大大小
                .maxInMemorySize(1024 * 10) // 保存上传文件时buffer大小
                .uploadTempDir(new File(context.getCacheDir(), "_server_upload_cache_")) // 文件保存目录
                .build()
        );
    }
}

下面是接口@PostMapping(path = "/upload", produces = "application/json;charset=utf-8")
public synchronized String upload(
@RequestParam("image") MultipartFile file
) {

    BaseResponse<String> response = new BaseResponse<>();

    response.setSuccessful("接收成功");

    return GsonUtils.toJson(response);
}

但是这里new File(context.getCacheDir(), "server_upload_cache")的内容是空的，没有文件

**Comment by yanzhenjie** [comment]
前面是_server_upload_cache_，后面是server_upload_cache，这里是不是写错了；另外可以用as的file explorer查看下有没有文件，这样能更快速的定位问题。

**Comment by EastwoodLeon** [comment]
1 目录没写错，只是我往这里写的时候随意了。
2 用as的file explorer看了，确实是空的
3 我在接收的时候，调用transferTo()，在新的目录里能找到文件
