### ISSUE TITLE
集成andServer无法运行

### ISSUE THREAD

**Issue by hj850113** [yanzhenjie/AndServer#394]
Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.IllegalArgumentException: couldn't make a guess for com.hik.netsdk.SimpleDemo.controller.LoginControllerAdapter

下面是LoginController类，麻烦问下这个是什么问题哈？谢谢

package com.hik.netsdk.SimpleDemo.controller;

import com.yanzhenjie.andserver.annotation.GetMapping;
import com.yanzhenjie.andserver.annotation.RequestMapping;
import com.yanzhenjie.andserver.annotation.RequestParam;
import com.yanzhenjie.andserver.annotation.RestController;

@RestController
@RequestMapping(path = "/user")
public class LoginController {

    @GetMapping("/login")
    String login(@RequestParam("account") String account,
                 @RequestParam("password") String password) {
        if("123".equals(account) && "123".equals(password)) {
            return "Login successful.";
        } else {
            return "Login failed.";
        }
    }
}

**Comment by hj850113** [comment]
已解决，抱歉，打扰了。

**Comment by ChangeStrong** [comment]
怎么解决的呀
