### ISSUE TITLE
org.apache.commons.fileupload.httpserv.HttpServFileUpload这个包为何在commons-fileupload-1.3.2.jar中找不到？

### ISSUE THREAD

**Issue by daojj** [yanzhenjie/AndServer#4]
org.apache.commons.fileupload.httpserv.HttpServFileUpload这个包为何在commons-fileupload-1.3.2.jar中找不到？

**Comment by rendcloud** [comment]
试试在项目依赖中添加上compile 'commons-io:commons-io:1.4',并且去掉'commons-fileupload-1.3.2'

**Comment by daojj** [comment]
在Demo的commons-fileupload.jar里找到了
