### ISSUE TITLE
com.yanzhenjie.andserver.view.View的名字有误导性, 能否重构成另一名字?

### ISSUE THREAD

**Issue by songzhw** [yanzhenjie/AndServer#40]
主要是和Android中的View易混淆. 可否换成ResponseDelegate, 或ResponseStub?

如果库主觉得OK, 我创建了一个PR :　https://github.com/yanzhenjie/AndServer/pull/41

**Comment by yanzhenjie** [comment]
我认为存在你说的问题，但是问题不大哦。可能对于纯`Android`开发者或者说设计模式了解少的同学是有点误导，但是仅仅在`Android`开发中来说，同名的类也是相当多。这也是为了框架的设计定义，以后可能会出现`Controller`和`Modle`望理解。
