### ISSUE TITLE
AppConfig-StorageWebsite

### ISSUE THREAD

**Issue by yalamo** [yanzhenjie/AndServer#402]
我在适配安卓10 的时候发现 context.getExternalFilesDir(null) 无法访问该文件夹下的html文件
用Environment.getExternalStorageDirectory()  在根目录创建的时候是可以访问的，请问andserver在高版本文件访问这块是否适配了？

**Comment by yanzhenjie** [comment]
你好，你提的这个点和AndServer没关系吧，AndServer哪个位置需要适配你说的这个点呢？

**Comment by yalamo** [comment]
AppConfig里面
delegate.addWebsite(new StorageWebsite(StorageUtils.getExternalDir(null) + "/AndServer/"));
//        delegate.addWebsite(new StorageWebsite(Environment.getExternalStorageDirectory() + "/Download/AndServer/"));

这么两句话 第一句运行无效。 找不到文件

**Comment by yalamo** [comment]
一个路径是/data/user/0/com.vishee.vsccrtpatient/files/AndServer/  一个是 storage开头的...

**Comment by yanzhenjie** [comment]
> AppConfig里面
> delegate.addWebsite(new StorageWebsite(StorageUtils.getExternalDir(null) + "/AndServer/"));
> // delegate.addWebsite(new StorageWebsite(Environment.getExternalStorageDirectory() + "/Download/AndServer/"));
> 
> 这么两句话 第一句运行无效。 找不到文件

这不是AndServer内部的代码，这是你创建Website入参，你改成没问题的方式就好了。

**Comment by yalamo** [comment]
是的，不是内部代码。  但是只支持 Environment.getExternalStorageDirectory()  这个api是逐步被废弃的。 所以想请教下这块怎么处理

**Comment by yanzhenjie** [comment]
> 是的，不是内部代码。 但是只支持 Environment.getExternalStorageDirectory() 这个api是逐步被废弃的。 所以想请教下这块怎么处理

看下官网文档：https://developer.android.com/training/data-storage
例如可以试试：`getExternalFilesDir()`，如果实在不能解决，就把文件放在内部吧，例如使用`getFilesDir()`，只是个文件路径而已，问题不大。

**Comment by yalamo** [comment]
旧存储模型是支持andserver.  但是新的存储模型（29+）只能访问外部数据（app包目录下的）  这种情况下给StorageWebsite提供的文件路径无效。  谢谢了， 我再思考下怎么处理

**Comment by yalamo** [comment]
-~-------context.getExternalFilesDir(null) + "/AndServer/"  我晕了。 这个换台机器又可以了。。 耽误您时间了
