### ISSUE TITLE
registerHandler的path能不能用正则表达式？

### ISSUE THREAD

**Issue by Choogle-Ma** [yanzhenjie/AndServer#42]
需要匹配一批URL或者干脆对全部访问的URL进行重定向处理，按我的理解，现在这个没法解决，只能列出有限个registerHandler。

另外完全自定义网站我看官方文档和源码，那个似乎也是继承自registerHandler，似乎也没法解决这一问题。

**Comment by yanzhenjie** [comment]
第一个问题：用拦截器，可以拦截所有`path`，加上自定义注解可以拦截你指定的`path`。  

第二个问题：网站是`Website`，只是有一个方法和`RequestHandler`一样，所以继承。

第一个问题拓展：也可以把你要拦截的`path`写到拦截器中的一个`List`中，匹配需要拦截的`path`，甚至可以正则表达式模糊匹配你要拦截的有规则的那些`path`。

**Comment by Choogle-Ma** [comment]
我试了一下，拦截之后有没有办法直接返回重定向Response？

**Comment by yanzhenjie** [comment]
第一种：
```java
return Redirect("你的重定向path");
```
拦截器可能没有接受`View`回参的方法，你可以参考`SimpleRequestHandler`自己稍微封装一下。

第二种：
```java
response.setStatusCode(302);
response.setHeader("Location", "你的重定向path");
```

----
推荐用第一种。

**Comment by Choogle-Ma** [comment]
第一种，似乎Interceptor这类的onBeforeExecute和onAfterExecute两个方法没法接受View回参。我不是很明白如果封装的话是什么思路？

**Comment by yanzhenjie** [comment]
上有说哦，参考`SimpleRequestHandler`类。

你可以自己写一个`AbstractInterceptor`，封装成可以接受`View`回参的。

**Comment by Choogle-Ma** [comment]
`open class SimpleInterceptor : Interceptor {

    @Throws(HttpException::class, IOException::class)
    override fun onBeforeExecute(request: HttpRequest?, response: HttpResponse?, context: HttpContext?): Boolean {
        return false
    }


    @Throws(HttpException::class, IOException::class)
    protected fun onBeforeExecute(request: HttpRequest?, response: HttpResponse?, context: HttpContext?): View {
        val view = View(301)
        view.setHeader("Location", "http://192.168.43.1:7777/index.html")
        return view
    }

    @Throws(HttpException::class, IOException::class)
    override fun onAfterExecute(request: HttpRequest?, response: HttpResponse?, context: HttpContext?) {
        return
    }

}`

类似这样IDE报错，出错在onBeforeExecute那个方法不能向handle一样写两个同名的方法。
请问这是个什么问题？

**Comment by yanzhenjie** [comment]
方法重载是不能完全相同，要不方法名不同，要不参数个数/类型不同。
