### ISSUE TITLE
各位大佬谁知道有可以替代andserver的工具吗？

### ISSUE THREAD

**Issue by 1499320204** [yanzhenjie/AndServer#424]
首先感谢严大佬的免费分享，现在这么多人等更新，严大佬11月底某一天说今天就更新，结果现在都1月了还没有更新，如果忙的话跟我们打个招呼，我现在天天上来看一下更新了没有，快疯了， 就差这个插件andstudio更新不了，项目无法运行，真是太着急了，大佬尽快更新吧，或者有别的替代的插件也欢迎大家能分享一下，冒犯之处请海涵。哭😭

**Comment by wheatma38** [comment]
同问。

**Comment by yanzhenjie** [comment]
实在不好意思，工作太忙了没有和大家沟通好。之前其实是发布了2.1.10-SNAPSHOT的，有人也在用，但是我没在GitHub通知。现在2.1.10正式版本发布了，大家可以升级一下了。

**Comment by 360060316** [comment]
> 实在不好意思，工作太忙了没有和大家沟通好。之前其实是发布了2.1.10-SNAPSHOT的，有人也在用，但是我没在GitHub通知。现在2.1.10正式版本发布了，大家可以升级一下了。

要命插件不能下载
Could not find com.yanzhenjie.andserver:plugin:2.1.10.

**Comment by yanzhenjie** [comment]
不好意思我又错了，之前发布好忘记在snatype release了，现在已经操作好了，我这边使用已经OK了，大家用起来。

https://repo1.maven.org/maven2/com/yanzhenjie/andserver/api/2.1.10/

----

It is released central repositories:
```
release: https://oss.sonatype.org/content/repositories/releases/
snapshot: https://oss.sonatype.org/content/repositories/snapshots/
```
