### ISSUE TITLE
单个文件是传入File，那如果是多个文件应该如何操作呢？

### ISSUE THREAD

**Issue by OnlyYouMyLove** [yanzhenjie/AndServer#43]
大牛：很抱歉，我试了好多种办法都没有弄出来。谢谢大牛们指点： @yanzhenjie

**Comment by yanzhenjie** [comment]
多个文件可以用网站注册，或者注册多个`RequestHandler`，或者一个`RequestHandler`用参数区分请求哪个文件。

**Comment by OnlyYouMyLove** [comment]
您好严大哥：用网站注册是什么意思？如何注册多个RequestHandler呢，那个参数在哪里啊？我web基础不是很好，抱歉打扰您了。是否可以再详细一点点

**Comment by yanzhenjie** [comment]
文档中有很详细的教程。Demo中有详细的例子如何注册`RequestHandler`.

**Comment by OnlyYouMyLove** [comment]
我先说下现在我是如何实现的多文件下载，代码如何下：
`
//      path = SD卡下一个文件夹的路径
//        AndServer andServer = new AndServer.Build()
//                .port(8080)
//                .timeout(10 * 1000)
//                .registerHandler(path + "/login", new RequestLoginHandler(mData))
//                .website(new StorageWebsite(path))
//                .build();
//        mServer = andServer.createServer();`
`
public class RequestLoginHandler implements RequestHandler {

    private String mContent;

    public RequestLoginHandler(String content) {
        mContent = content;
    }

    @Override
    public void handle(HttpRequest request, HttpResponse response, HttpContext context) throws HttpException, IOException {

        StringEntity stringEntity = new StringEntity(mContent, "utf-8");
        response.setEntity(stringEntity);

    }

}
`
同时我copy assets下的文件到sd卡，然后前端就可以拿到我的login的json文件，可以通过sd卡下的的html路径访问，然后下载文件，这就导致了路径太长。当然这是老版本。
如果新的版本，我如何改造才能把json文件传输过去，并且又以很短的html地址访问得到并且可以下载sd卡下的文件呢？
之前的方式，我都不是很明白，因为我的文件是动态的，不是静态的，所以注册RequestHandler那不知道如何下手，RequestHandler带参数也不是很明白。。。。
sorry，我比较愚钝，希望不要打扰你工作。

**Comment by yanzhenjie** [comment]
* 首先注册一个`RequestHandler`用来支持登录，不管你的是不是固定的，都可以用这个`RequestHandler`返回。

```
...
  .registerHandler("/login", new LoginHandler())
...
```
如上所示代码，你的登陆接口地址就是：`http://ip:port/login`。

* 注册网站支持访问SD卡文件
```
...
  .registerHandler("/login", new LoginHandler())
  .website(new StorageWebsite(SDCardPath))
...
```
如上所示代码，假如`SDCardPath`下有一个`index.png`，那么访问它的地址是：`http://ip:port/index.png`；假如`SDCardPath`下有一个`user`目录，该目录下有一个`avatar.png`，那么访问`user.png`的地址是：`http://ip:port/user/avatar.png`。

**重要提示**：登录完成后最好给登录的那个请求设置`Cookie`标记用户是登录的，然后需要使用`AndServer`提供的过滤器过滤未登录的请求获取，防止未登录的用户访问SD卡的网站内容。过滤器用法看文档，正好有这个例子：[http://www.yanzhenjie.com/AndServer/](http://www.yanzhenjie.com/AndServer/)。

----

* 如何一个`RequestHandler` + Http请求参数支持下载不同的文件
首先注册下载的`RequestHandler`：
```
...
  .registerHandler("/download", new DownloadHandler())
...
```

在`DownloadHandler`中判断客户端提交的参数，例如你们可以约定在参数中指定下载的文件：
```
http://ip:port/download?filename=user.png
```
此时你可以在`DownloadHandler`中拿到`filename`参数，然后找到参数指定的文件返回给客户端。

**Comment by OnlyYouMyLove** [comment]
严大哥您好：

`如上所示代码，假如SDCardPath下有一个index.png，那么访问它的地址是：http://ip:port/index.png；假如SDCardPath下有一个user目录，该目录下有一个avatar.png，那么访问user.png的地址是：http://ip:port/user/avatar.png。`

以上这个对我非常有用，我改造了下网页中访问的文件地址”。

但是有两个问题：
1. 我用storageWebsite的时候，我必须在sd下面copy一份assets的代码，就是html文件加js等；
2.我用debug安装应用以后发现，我能用了，但是我跳出页面执行了stopService以后，再打开四五次才能再电脑中正常访问网页。
3.跳出页面执行了stopService以后，应用会出现ANR。

严大哥：第一个问题中copy是必须的吗？否则会报 The resource "/" not exist.第二个问题：我也不知道为什么会这个样子，另外我打过log，执行完mServer.startup()以后，mServer.isRunning()并不是为true，

谢谢严大哥的指点，辛苦了，新年快乐，这是我一天测试的结果，测试了不至于50次了。

核心代码：
        String path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DCIM)
                .getAbsolutePath() ;
        Log.e("path", "onCreate:path " + path);
        mServer = AndServer.serverBuilder()
                .port(8080)
                .timeout(10 * 1000, TimeUnit.SECONDS)
                .registerHandler("/login", new LoginHandler(mData))
                .website(new StorageWebsite(path))
                .build();
另外补充下：前端那边从login接口那里拿的json数据。

**Comment by yanzhenjie** [comment]
不copy你就直接加载`assets`就好了，但是你是需要热插拔的就得SD卡了，所以拷贝是必须的。你应该在子线程中拷贝完成以后回调到主线程，然后再启动服务器（否则服务器启动了，资源可能还不存在）。

**Comment by OnlyYouMyLove** [comment]
1. copy到SD卡确定了 。
2. copy到SD卡后，我发现我debug运行的第一次，然后注销copy的动作，发现OK，很正常，再stopService再开几次才行，我想问下严大哥，只要copy一次就Ok，也就是sd卡有这个html就Ok是吗？不用每次都copy吧。
3. 另外我这个hmtl地址太长（输入的是sd卡的路径），是否可以用重定向来写：比如我输入ip+端口就可以跳转到我那个很长很长的地址。

**Comment by yanzhenjie** [comment]
* 如果文件不变化，不用每次copy，只要文件存在即可。
* 你注册网站的时候，注册路径指向到你文件所在的文件夹，仔细看看上面写的例子和文档。

**Comment by OnlyYouMyLove** [comment]
非常感谢严大哥这么长时间对我的支持和指点，我已经实现了多下载功能，并且解决了地址长的问题，谢谢新版本，谢谢下班以后仍然更新版本，维护项目，真是辛苦了。
估计是最后问的问题了：
就是关闭页面停止Service后，Service执行了onDestory方法，方法中Server执行了shutdown方法，但是页面出现了ANR，请问严大哥这是因为什么呢？试验了多次，如果关闭Service，不调用shutdown，并不会出现这个问题。
具体操作描述如下：
1. 先打开页面，同时开启了服务器。
2. PC端请求ip+端口（前端拿的是login端口我传过去的数据）
3. 关闭页面，同时关闭了Service，同时Server执行了shutdown方法
此时APP会出现3或者4秒的无响应，所以想问下严大哥，出题到底是出在哪里呢？

**Comment by yanzhenjie** [comment]
这个应该是我疏忽了，应该放到子线程中关闭，你可以在Service中先放到子线程中关闭。过几天我会更新库，在底层放到子线程中执行关闭。

**Comment by OnlyYouMyLove** [comment]
嗯，放在子线程的确解决了这个问题。经过我的反复测试，发现了一个新问题（不是故意的，我强迫症吧，想把这个东西搞好，毕竟是我的工作）：
1.打开页面，开启服务，开启Server。
2.PC打开页面
3.关闭页面，关闭服务，关闭Server（子线程执行了shutdown）
4.在PC“原来的”页面上刷新，出现一个空页面的数据，html还可以访问到，再刷新，显示连接不上服务。
5.打开页面，开启服务，开启Server。
这个时候发现服务不能正常开启，PC不能正常访问页面，差不多等个半分钟，再请求页面就能访问了。

注意是页面关闭的情况下：PC 在"原来的页面不断去刷新“会出现页面请求不到也就是服务不能的情况。严大哥，问题出在哪里啊？

辛苦了严大哥！

**Comment by OnlyYouMyLove** [comment]
说白了，就是开启，请求页面，关闭；再开启，请求页面，再关闭；再开启，请求页面，再关闭；再开启，请求页面，再关闭；这样重复之后，再开启，请求页面会出现请不到服务器的情况，需要等20-30秒再重启服务器，再请求页面，这个时候页面才会正常相应，需要一个等待的空档期。

谢谢严大哥！
