### ISSUE TITLE
使用最新的Gradle 7.1.2 KTS模版，加载不了Plugin

### ISSUE THREAD

**Issue by D10NGYANG** [yanzhenjie/AndServer#431]
Plugin [id: 'com.yanzhenjie.andserver', version: '2.1.9', apply: false] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.yanzhenjie.andserver:com.yanzhenjie.andserver.gradle.plugin:2.1.9')
  Searched in the following repositories:
    Gradle Central Plugin Repository
    Google
    MavenRepo

**Comment by D10NGYANG** [comment]
已解决。[https://docs.gradle.org/current/userguide/plugins.html#sec:types_of_plugins](https://docs.gradle.org/current/userguide/plugins.html#sec:types_of_plugins)

**Comment by southbaird** [comment]
请问怎么解决的 是该回以前一样吗

**Comment by D10NGYANG** [comment]
> 请问怎么解决的 是该回以前一样吗

看这里，我写了个博客去描述：
[https://blog.csdn.net/sinat_38184748/article/details/123549148?spm=1001.2014.3001.5501](https://blog.csdn.net/sinat_38184748/article/details/123549148?spm=1001.2014.3001.5501)

**Comment by southbaird** [comment]
@D10NGYANG 谢谢
