### ISSUE TITLE
Could not find com.yanzhenjie.andserver:plugin:2.1.10.

### ISSUE THREAD

**Issue by 360060316** [yanzhenjie/AndServer#434]
更新一下啊，等着用

**Comment by KostyaSha** [comment]
Maven central is missing 2.1.10 https://mvnrepository.com/artifact/com.yanzhenjie.andserver/api

**Comment by yanzhenjie** [comment]
Sorry, I forgot to release it, now it's done.

https://repo1.maven.org/maven2/com/yanzhenjie/andserver/api/2.1.10/

----

It is released central repositories:
```
release: https://oss.sonatype.org/content/repositories/releases/
snapshot: https://oss.sonatype.org/content/repositories/snapshots/
```
