### ISSUE TITLE
request中无法获得参数

### ISSUE THREAD

**Issue by BranZhang** [yanzhenjie/AndServer#44]
uri中是有参数信息的。如图：
/font?f=abc&r=123

但是params中为空。

![image](https://user-images.githubusercontent.com/10242480/34708999-5d1a2caa-f550-11e7-9d7b-249b69cbf6dd.png)

**Comment by yanzhenjie** [comment]
我都看到了在requestLine中，获取参数请参考文档和Demo。  
* Demo中可以参考：`LoginHandler.java`
* 文档可以参考：`扩展#Request解析`
