### ISSUE TITLE
onError:bind failed: EADDRINUSE (Address already in use)   版本 ：1.1.0

### ISSUE THREAD

**Issue by cai784921129** [yanzhenjie/AndServer#45]
开启Server失败，回调了onError方法
@Override
        public void onError(Exception e) {
   }
  
是在重启应用的时候出现的，重启好几次应用一直回调onError（），退出应用的时候，已经调用了mServer.shutdown()

**Comment by cai784921129** [comment]
实在重启应用的时候出现的，重启好几次应用一直回调onError（）

**Comment by kong-jing** [comment]
me too

**Comment by yanzhenjie** [comment]
你们可以试试demo，我用demo试了很多次，都没出现这个问题，可能是退出时关闭服务器的问题。如果服务器是启动的，那么重复启动会有这个提示。

**Comment by cai784921129** [comment]
退出时，已经调用了 mServer.shutdown()了啊

**Comment by yanzhenjie** [comment]
要等到`listener`通知服务器停止了，才表明退出完成。

**Comment by cai784921129** [comment]
我是在Activity的 onDestory（）里直接调用的，请问该如何真正的退出server

**Comment by yanzhenjie** [comment]
这个可以直接照抄`sample`中的代码，`server`必须放到`Service`中。

**Comment by cai784921129** [comment]
大佬，我用sample测试也出现了这种情况，出现场景（进入应用，按返回键，这个时候Server还没退出，网址依然可以打开，此时我后台清除应用，再打开应用就出现了）

![image](https://user-images.githubusercontent.com/20353284/36640260-156eadc4-1a56-11e8-860e-2d59ed64c7e4.png)

log：
02-25 18:01:05.919 29202-29596/com.yanzhenjie.andserver.sample W/System.err: java.net.SocketException: Socket closed
02-25 18:01:05.922 29202-29596/com.yanzhenjie.andserver.sample W/System.err:     at libcore.io.Posix.accept(Native Method)
02-25 18:01:05.922 29202-29596/com.yanzhenjie.andserver.sample W/System.err:     at libcore.io.BlockGuardOs.accept(BlockGuardOs.java:63)
02-25 18:01:05.922 29202-29596/com.yanzhenjie.andserver.sample W/System.err:     at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:89)
02-25 18:01:05.922 29202-29596/com.yanzhenjie.andserver.sample W/System.err:     at java.net.ServerSocket.implAccept(ServerSocket.java:229)
02-25 18:01:05.922 29202-29596/com.yanzhenjie.andserver.sample W/System.err:     at java.net.ServerSocket.accept(ServerSocket.java:147)
02-25 18:01:05.922 29202-29596/com.yanzhenjie.andserver.sample W/System.err:     at org.apache.httpcore.impl.bootstrap.RequestListener.run(RequestListener.java:74)
02-25 18:01:05.922 29202-29596/com.yanzhenjie.andserver.sample W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
02-25 18:01:05.922 29202-29596/com.yanzhenjie.andserver.sample W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
02-25 18:01:05.922 29202-29596/com.yanzhenjie.andserver.sample W/System.err:     at java.lang.Thread.run(Thread.java:833)
02-25 18:01:07.528 29202-29202/com.yanzhenjie.andserver.sample E/CoreService: onStopped
02-25 18:01:07.529 29202-29202/com.yanzhenjie.andserver.sample I/SendBroadcastPermission: action:com.yanzhenjie.andserver.receiver, mPermissionType:0
02-25 18:01:13.688 29202-29202/com.yanzhenjie.andserver.sample D/HwCust: Create obj success use class android.app.HwCustHwWallpaperManagerImpl
02-25 18:01:13.692 29202-29202/com.yanzhenjie.andserver.sample V/ActivityThread: ActivityThread,callActivityOnCreate
02-25 18:01:13.777 29202-29358/com.yanzhenjie.andserver.sample D/mali_winsys: new_window_surface returns 0x3000
02-25 18:01:13.810 29202-29358/com.yanzhenjie.andserver.sample D/mali_winsys: new_window_surface returns 0x3000
02-25 18:01:13.847 29202-29202/com.yanzhenjie.andserver.sample E/CoreService: bind failed: EADDRINUSE (Address already in use)
02-25 18:01:13.848 29202-29202/com.yanzhenjie.andserver.sample I/SendBroadcastPermission: action:com.yanzhenjie.andserver.receiver, mPermissionType:0

**Comment by yanzhenjie** [comment]
@cai784921129 我刚才测试了一下，用小米4C和原生模拟器，结果如下：
1. 小米4C清除任务后，service被杀死，重新打开App后，因为service都被杀死了，这个service启动的server的线程肯定也被杀死了（不是service的死引起server的死，而是进程引起的）。
2. 原生模拟器清除任务后，service还是活着的，重新打开App后，activity重新启动service，service中的server还是活着的，所以没有去启动server，而是直接回调告诉activity，服务器已经启动。

问题诊断：你可能运行的不是当时最新的代码，最开始发布的那一版的sample，service中没有判断server是否是活着的，而直接去启动了server，就会报你图中的错，新版sample中已经修复这个示例bug。

注：等下我还push一个新版本，修复一个中文路径的问题，你可以下载1.1.1版本的sample或者等下我push的新版本再次测试。

**Comment by yanzhenjie** [comment]
已经发布的1.1.4修复了这个问题， #73。
