### ISSUE TITLE
下载和上传速度比较慢

### ISSUE THREAD

**Issue by gaozhongkui** [yanzhenjie/AndServer#46]
我使用华为手机下载或者上传基本上也就500kb/s，怎么才能提高速度呢？

**Comment by yanzhenjie** [comment]
客户端多线程下载，比如使用迅雷这样的工具。当然还需要服务器这边做断点续传的支持，不过`AndServer`目前内部没有对文件传输做断点续传的支持，需要开发者自行实现，之前我没考虑到这一点（内部实现非常棒的点子，如果有人早点提就好了），下个版本我会把这个功能加上。感谢反馈。

开发者自行实现思路：  
使用过滤器，同内部的缓存过滤器一样的实现思路。

**Comment by yanzhenjie** [comment]
Not responsed close.
