### ISSUE TITLE
element-ui不显示

### ISSUE THREAD

**Issue by chenqian19911214** [yanzhenjie/AndServer#468]
前端h5使用element-ui框架。经过andServer 部署后在前端网页element里的UI不能显示。请求怎么解决

**Comment by yanzhenjie** [comment]
提供的信息不足够判断问题，没用过element-ui。AndServer本质就是个服务器，负责响应客户端的请求，向客户端写出请求的资源，要具体看看前端错误是什么，是服务端响应错误了还是前端哪里配置不对。
