### ISSUE TITLE
HttpRequest.getBody().string() can only be read once?

### ISSUE THREAD

**Issue by lancewoo** [yanzhenjie/AndServer#469]
My code is like:
```Java
    @PostMapping(path = "/heartbeat", consumes = "application/json")
    public String heartbeatPush(HttpRequest request) {
        HeartbeatPush heartbeatPush = null;
        try {
            KLog.i("json orig :" + request.getBody().string() + ", len:" + request.getBody().string().length());
            String json = request.getBody().string();
            KLog.i("HeartbeatPush Request:" + json);

```

And I got the output like:
```
2022-10-26 13:47:55.428 18881-18968 I/#ST2303_Sonar#: [(TerminalController.java:65)#heartbeatPush] json orig :{"dev_name": "Sonar", "dev_type":"XXXX", "dev_version":"1.0.0","message_type":"heart_beat_message", "sys_time_str":"2022-10-25_11-25-50","sys_time":111111111111 }, len:0
2022-10-26 13:47:55.430 18881-18968 I/#ST2303_Sonar#: [(TerminalController.java:67)#heartbeatPush] HeartbeatPush Request:
```

Apparently, HttpRequest.getBody().string() can only be read once, is this a bug?

**Comment by mtjsoft** [comment]
> My code is like:
> 
> ```java
>     @PostMapping(path = "/heartbeat", consumes = "application/json")
>     public String heartbeatPush(HttpRequest request) {
>         HeartbeatPush heartbeatPush = null;
>         try {
>             KLog.i("json orig :" + request.getBody().string() + ", len:" + request.getBody().string().length());
>             String json = request.getBody().string();
>             KLog.i("HeartbeatPush Request:" + json);
> ```
> 
> And I got the output like:
> 
> ```
> 2022-10-26 13:47:55.428 18881-18968 I/#ST2303_Sonar#: [(TerminalController.java:65)#heartbeatPush] json orig :{"dev_name": "Sonar", "dev_type":"XXXX", "dev_version":"1.0.0","message_type":"heart_beat_message", "sys_time_str":"2022-10-25_11-25-50","sys_time":111111111111 }, len:0
> 2022-10-26 13:47:55.430 18881-18968 I/#ST2303_Sonar#: [(TerminalController.java:67)#heartbeatPush] HeartbeatPush Request:
> ```
> 
> Apparently, HttpRequest.getBody().string() can only be read once, is this a bug?

String json = request.getBody().string();
KLog.i("json orig :" + json + ", len:" + json.length());
KLog.i("HeartbeatPush Request:" + json);
