### ISSUE TITLE
如何使用通配符例如 /api/**

### ISSUE THREAD

**Issue by mxlt02** [yanzhenjie/AndServer#470]
现在我使用的是 /api/{uri}
他可以匹配 /api/任意字符串, 但无法匹配 /api/任意字符串/任意字符串 or  /api/任意字符串/任意字符串/任意字符串 ......

如何实现类似效果 @RequestMapping("/api/**") 来接管 /api下的任意层级请求

**Comment by yanzhenjie** [comment]
好的，我看你在另一个问下也回复了，我们在那个问题下跟进。#455
