### ISSUE TITLE
最新版返回值为null

### ISSUE THREAD

**Issue by xmhwws** [yanzhenjie/AndServer#471]
版本：2.1.10

代码如下：

![image](https://user-images.githubusercontent.com/42903751/204806373-e0e2dd6e-fbfb-4d80-a9d3-60ec4f454c99.png)
![image](https://user-images.githubusercontent.com/42903751/204806649-fbac0b96-cff3-49f4-b45f-bff81cf616c0.png)

访问http://192.168.0.108:8005/info?sign=%E6%88%91%E6%98%AF%E6%B5%8B%E8%AF%95
会返回：
`Server internal error, The return value of [null] is not supported.`

通过日志可以知道返回值是有的，但AndServer一直返回null，不理解

**Comment by fismas** [comment]
我也遇到同样问题，不知道是不是哪里配置不对，我也是提示这个
Server internal error, The return value of [null] is not supported.

**Comment by yanzhenjie** [comment]
类的注解不对，要用`@RestController`。

**Comment by jykun** [comment]
最新demo 中用的是 @Controller 不是@RestController
