### ISSUE TITLE
服务器频繁断开

### ISSUE THREAD

**Issue by weijielv** [yanzhenjie/AndServer#480]
集成并启动服务后，服务器会频繁断开（大概5到10分钟）。手机wifi 状态下，ip没有变化，app 也没有被系统杀掉。不知道是哪里的问题。有人遇到过吗？

**Comment by yanzhenjie** [comment]
没遇到过。但是压后台后系统会禁用网络，必须保持前台。

**Comment by wang-neng** [comment]
这个现象和Linux系统的网络策略有关，Android系统只会在java层或framework层做一些简单调度

**Comment by WangManAndroid** [comment]
注册广播监听一下，服务挂了就再次拉起一下。

**Comment by WangManAndroid** [comment]
> 集成并启动服务后，服务器会频繁断开（大概5到10分钟）。手机wifi 状态下，ip没有变化，app 也没有被系统杀掉。不知道是哪里的问题。有人遇到过吗？

在服务中调用    startForeground(1, createNotification());

**Comment by FaceAISDK** [comment]
Android 系统的网络活动策略限制，本质是为了防止App 在后台偷偷传数据之类耗电耗性能。
