### ISSUE TITLE
数据返回出现这个，帮忙看看，syntax error,expect start with { or [,but actually start with error

### ISSUE THREAD

**Issue by SmallRedSister** [yanzhenjie/AndServer#484]
代码
```java
    @PostMapping("/check")
    public void startCheck(RequestBody body, HttpResponse response) throws IOException {
        Log.e("TAG-check", "body: " + body.toString());
        CheckBean checkBean = JSON.parseObject(body.toString(), CheckBean.class);
        Log.e("TAG-check", "CheckBean: " + checkBean.getCheck());
        List<String> lists = new ArrayList<>();
        lists.add("E0040150ACC87858");
        lists.add("E0040150ACC942F1");
        lists.add("E0040150ACC945AB");
        ModelCheck modelCheck = new ModelCheck(/*200, "ok", lists*/);
        modelCheck.code = 200;
        modelCheck.msg = "ok";
        modelCheck.list = lists;
        Log.e(TAG, "ModelCheck: " + modelCheck.getMsg());
        //返回码code200
//        response.setBody(new JsonBody(new Gson().toJson(modelCheck)));
        response.setBody(new JsonBody(JSON.toJSONString(modelCheck)));
    }
```
调用返回
 I  retrofitBack = --> POST http://192.168.4.27:8080/check
  I  retrofitBack = Content-Type: application/json; charset=UTF-8
 I  retrofitBack = Content-Length: 47
 I  retrofitBack =  
I  retrofitBack = {"brand":"汉堂","frequency":"HF","check":"2"}
 I  retrofitBack = --> END POST (47-byte body)
I  retrofitBack = <-- 500 Internal Server Error http://192.168.4.27:8080/check (52ms)
 I  retrofitBack = Date: Mon, 06 Mar 2023 06:25:42 GMT+00:00
I  retrofitBack = Server: AndServer/2.1.11
I  retrofitBack = Content-Length: 67
  I  retrofitBack = Content-Type: text/plain;charset=UTF-8
  I  retrofitBack = Connection: Keep-Alive
  I  retrofitBack = 
  I  retrofitBack = syntax error,expect start with { or [,but actually start with error
   I  retrofitBack = <-- END HTTP (67-byte body)

懵了，使用get请求，浏览器可以看到返回的数据，{"code":200,"list":["E0040150ACC87858","E0040150ACC942F1","E0040150ACC945AB"],"msg":"ok"}，post请求就没了

帮忙看看，搞了两天，没出来，晕~

不知道是那一步出错，

**Comment by yanzhenjie** [comment]
代码中`body.toString()`目前不支持重复调用，因为不知道request的内容是什么，所以底层是stream，stream重复toString就拿不到内容了，可能报错了这里。

另外，接受参数一般不用直接拿ReuqestBody，返回数据也不用直接从HttpResponse设置，多看看Demo和文档，都是中文的很方便。然后你可以使用`MessageConverter`、`ExceptionResolver`等配合做封装，也很方便发现全局发生的异常。

**Comment by SmallRedSister** [comment]
呜呜呜~
我是搞Android开发的，现在这个有点像后台，不太熟悉这块操作，
这样的话，startCheck方法的接收客户端的body数据注解不对，返回JSON数据的注解也不对，好吧！那从新来写一个。其他简单的接口，写的倒是没问题。

还有一个问题
/**
     * Android WebServer API 文档说明
     *
     * @return
     */
    @GetMapping("/api")
    public String api() {
        return "redirect:/api.html";
    }

这个接口，浏览器收到的是redirect:/api.html ，而不是直接打开这个页面，

**Comment by SmallRedSister** [comment]
@yanzhenjie 之前下了个别人的demo学习，学错了，刚刚纠正过来，欧了~
/**
     * 正确的样子，收到数据
     */
    @ResponseBody
    @PostMapping("/check")
    public String startCheck(@RequestBody String body)  {
        Log.e("TAG-check", "body: " + body);
        CheckBean checkBean = JSON.parseObject(body, CheckBean.class);
        Log.e("TAG-check", "CheckBean: " + checkBean.getCheck());
        List<String> lists = new ArrayList<>();
        lists.add("E0040150ACC87858");
        lists.add("E0040150ACC942F1");
        lists.add("E0040150ACC945AB");
        ModelCheck modelCheck = new ModelCheck(/*200, "ok", lists*/);
        modelCheck.code = 200;
        modelCheck.msg = "ok";
        modelCheck.list = lists;
        Log.e(TAG, "ModelCheck: " + modelCheck.getMsg());
        return JSON.toJSONString(modelCheck);
    }

放在这里做个记录，方便后面的同学学习。
