### ISSUE TITLE
本地服务失败导致，在WebView获取得 error: -6 desc: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by Coding4Me** [yanzhenjie/AndServer#494]
复现步骤：
1. 连接WIFI，开启本地服务；
2. 部署的服务后，在客户端打开网页；
3. 切换WIFI或者连接手机网络

**Comment by clever--code** [comment]
Did you change ip internal  ?

**Comment by Coding4Me** [comment]
> Did you change ip internal ?

Yes, ip is changed;
But the server is 127.0.0.1

**Comment by yanzhenjie** [comment]
你服务器的ip变了，网页要换新的ip去访问。如果启动server时指定了ip，那么不要指定。

**Comment by Coding4Me** [comment]
@yanzhenjie 感谢反馈
