### ISSUE TITLE
前端路由如何如何像通配符一样匹配路由？

### ISSUE THREAD

**Issue by kaiaiz** [yanzhenjie/AndServer#496]
如何能不需要一个一个写前端路由的控制函数？涉及到权限问题，如何能像vue那样使用通配符去匹配路由，以'/api'开头的就是接口（只需匹配接口控制函数就行）？

**Comment by yanzhenjie** [comment]
没理解你的意思，麻烦举个具体点的例子。

**Comment by kaiaiz** [comment]
`@Controller
public class PageController {

    @GetMapping(path = "/")
    public String index() {
        // Equivalent to [return "/index"].
        return "forward:/index.html";
    }
    @GetMapping(path = "/login")
    public String login() {
        // Equivalent to [return "/index"].
        return "forward:/index.html";
    }
}`
比如定义一个'/login'的页面需要写这样一个控制函数，如果不加的话直接访问'/login'是无法显示页面的，因为我用的vue，没有'/login'这个页面，所有的页面访问都要交给'index.html'去判断。
我的意思是如何不用这样一个个定义控制函数，而直接解析到'index.html'?

**Comment by yanzhenjie** [comment]
如果是静态资源，不是Controller转发的，直接访问就行了，看Sample中有例子。

Controller只是用来做转发的，比如原来你的首页index.html就是登录页，但是后来你逻辑变了，需要重定向到login.html，那么再Controoler中处理，这个时候才可能用到Controller。

如果是写接口，使用RestController，请参考文档。

**Comment by kaiaiz** [comment]
我不知道我有没有表达清楚，因为使用的vue打包完没有login.html这个文件，如果不定义上面代码这个login函数，浏览器一刷新login页面就没了，可能我有很多web页面，我想无需写这么多路由控制函数的情况下都让浏览器去找'index.html'这个资源文件，让它解析路由。
我看到上面的回答，按我的理解是只能定义静态的路由函数，定义才能访问这个路由，也就是无法达到我上面要的这个效果，对吗？

**Comment by yanzhenjie** [comment]
理解了，应该是能支持的。vue的项目会产生一些不存在的path，这个path需要服务器来拦截并转发到对应的资源上，如果每个path都这么去匹配你需要写很多api。

我不太了解vue，它访问的不存在path指向的资源是什么，它是如何通过不存在的path描述出自己想要访问的资源是什么。也就是说，只要你清楚，它输入的是什么，实际想要得到的是什么，就可以做了。

具体的做法，我只能举个例子，1种是通过RestController模糊匹配path，一种是用拦截器去转发，但是要实际了解vue这套逻辑和AndServer的转发规则（基本和SpringMVC一致，或者和Sevelet一致）。

**Comment by kaiaiz** [comment]
我解释一下题主对于vue的困惑，vue把逻辑都放在index.html这个入口文件里，浏览器地址路由跳转由内部实现，所以比如'/login'，这个浏览器地址它是没有相应文件，如果浏览器直接访问'/login'，服务器直接返回对应位置的资源（也就是login.html）会报404，我之前用nginx的方式是'try_file'指令，把所有访问的路径指到index.html中。
不知道我有没有解释清楚。

**Comment by luseweixiao** [comment]
可以将vue-router 的history 模式配置成Hash模式，login页面的格式是这样的：`http://ip:port/xxx/index.html#/login`。这样就不需要服务器端的配置了，前端的路由匹配都由前端js代码完成。
参考：[不同的历史模式](https://router.vuejs.org/zh/guide/essentials/history-mode.html)

**Comment by ZyElite** [comment]
> 可以将vue-router 的history 模式配置成Hash模式，login页面的格式是这样的：`http://ip:port/xxx/index.html#/login`。这样就不需要服务器端的配置了，前端的路由匹配都由前端js代码完成。 参考：[不同的历史模式](https://router.vuejs.org/zh/guide/essentials/history-mode.html)



> 如何能不需要一个一个写前端路由的控制函数？涉及到权限问题，如何能像vue那样使用通配符去匹配路由，以'/api'开头的就是接口（只需匹配接口控制函数就行）？

你好，遇到同样问题，是如何解决的？可以给个思路方法吗。
