### ISSUE TITLE
AndServer程序崩溃，请教是什么原因？

### ISSUE THREAD

**Issue by daojj** [yanzhenjie/AndServer#5]
我把AndServer移到我的Launcher程序里，参考Demo的MainActivity, 在RemoteInstallActivity里启动AndServer, 然后客户端浏览器运行 http://x.x.x.x:8000/test, 这是程序崩溃，Log如下：
--------- beginning of crash
02-27 01:53:44.551 E/AndroidRuntime( 5017): FATAL EXCEPTION: pool-1-thread-1
02-27 01:53:44.551 E/AndroidRuntime( 5017): Process: com.droidlogic.mboxlauncher, PID: 5017
02-27 01:53:44.551 E/AndroidRuntime( 5017): java.lang.AbstractMethodError: abstract method "void org.apache.http.protocol.HttpRequestHandler.handle(org.apache.http.HttpRequest, org.apache.http.HttpResponse, org.apache.http.protocol.HttpContext)"
02-27 01:53:44.551 E/AndroidRuntime( 5017): 	at org.apache.http.protocol.HttpService.doService(HttpService.java:248)
02-27 01:53:44.551 E/AndroidRuntime( 5017): 	at org.apache.http.protocol.HttpService.handleRequest(HttpService.java:192)
02-27 01:53:44.551 E/AndroidRuntime( 5017): 	at com.droidlogic.mboxlauncher.remoteserver.RequestHandleTask.run(RequestHandleTask.java:29)
02-27 01:53:44.551 E/AndroidRuntime( 5017): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
02-27 01:53:44.551 E/AndroidRuntime( 5017): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
02-27 01:53:44.551 E/AndroidRuntime( 5017): 	at java.lang.Thread.run(Thread.java:818)
02-27 01:53:44.578 W/ActivityManager( 4051):   Force finishing activity com.droidlogic.mboxlauncher/.settings.RemoteInstallActivity

请教，从Log上看是HttpRequestHandler.handle导致程序崩溃吗？这里的handler就是AndServer的AndServerTestHandler, 我无法确定是什么原因导致？请教这会是什么原因，或者有什么方法来确定原因？

**Comment by yanzhenjie** [comment]
注册的`handler`发生异常，在在里面打印断点查看即可。
