### ISSUE TITLE
2.1.12下载失败

### ISSUE THREAD

**Issue by wtl568594290** [yanzhenjie/AndServer#502]
2.1.12版本报错
A problem occurred configuring root project 'Mo'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.yanzhenjie.andserver:plugin:2.1.12.
     Searched in the following locations:
       - https://maven.aliyun.com/repository/google/com/yanzhenjie/andserver/plugin/2.1.12/plugin-2.1.12.pom
       - https://maven.aliyun.com/repository/public/com/yanzhenjie/andserver/plugin/2.1.12/plugin-2.1.12.pom
       - https://maven.aliyun.com/repository/jcenter/com/yanzhenjie/andserver/plugin/2.1.12/plugin-2.1.12.pom
       - https://dl.google.com/dl/android/maven2/com/yanzhenjie/andserver/plugin/2.1.12/plugin-2.1.12.pom
       - https://repo.maven.apache.org/maven2/com/yanzhenjie/andserver/plugin/2.1.12/plugin-2.1.12.pom
       - https://plugins.gradle.org/m2/com/yanzhenjie/andserver/plugin/2.1.12/plugin-2.1.12.pom
     Required by:
         project :

以下是我的配置
``` gradle
project build.gradle
buildscript {
    dependencies {
        classpath 'com.yanzhenjie.andserver:plugin:2.1.12'
    }
}
plugins {
    id 'com.android.application' version '8.0.2' apply false
    id 'com.android.library' version '8.0.2' apply false
    id 'org.jetbrains.kotlin.android' version '1.7.20' apply false
    id 'com.google.dagger.hilt.android' version '2.44' apply false
    id 'com.google.devtools.ksp' version '1.8.20-1.0.11' apply false
}

app build.gradle
...
apply plugin: 'com.yanzhenjie.andserver'
...
dependencies {
    ...
    def version = '2.1.12'
    implementation "com.yanzhenjie.andserver:api:$version"
    kapt "com.yanzhenjie.andserver:processor:$version"
}
```
使用2.1.11是正常的,试过去掉阿里云镜像也是报这个错误

**Comment by Reginer** [comment]
没上传
