### ISSUE TITLE
上传一个1.3G大小的文件，耗时大概3到4分钟，如何监听上传进度呢？

### ISSUE THREAD

**Issue by DHGHH** [yanzhenjie/AndServer#506]
我需要监听进度，然后返回进度给前端。谢谢

**Comment by yanzhenjie** [comment]
你啥都不用做，前端那边本身就能拿到进度。

**Comment by DHGHH** [comment]
感谢大佬。确实可以。
`
export default function HomePage() {

  function handleChangeFile(event) {
    const file = event.target.files[0];
    let formData = new FormData();
    formData.append('file', file);
    formData.append('md5', "abhnfjmavgsb")
    formData.append('version', "123455432")
    axios.post('/api/v1/ota/api/v1/ota', formData, {
      onUploadProgress: progressEvent => {
        const progress = Math.round(progressEvent.loaded / progressEvent.total * 100)
        console.log('上传进度：' + progress + '%')
      }
    }).then(res => {
      console.log('上传成功', res)
    })
  }


  return (
    <>
      <div>
       <form>
       <input type="file" onChange={handleChangeFile} />
        </form>
      </div>
    </>
  );
}
`
