### ISSUE TITLE
请问一下大佬啥时候支持Kotlin

### ISSUE THREAD

**Issue by tony901** [yanzhenjie/AndServer#510]
这边用2.12版本用Kotlin写接口总是无法找到资源，有解决的办法吗

**Comment by HenryGaoGH** [comment]
me too! 
看来是 注解类 无法自动加载

**Comment by jxxfli** [comment]
项目中是不是用了kapt，如果加了apply plugin: 'kotlin-kapt'，就把annotationProcessor 'com.yanzhenjie.andserver:processor:2.1.12'改成kapt 'com.yanzhenjie.andserver:processor:2.1.12'试试看

**Comment by yanzhenjie** [comment]
应该默认就是支持的，我不打算转kotlin。
