### ISSUE TITLE
本身有一个普通的应用，现在想在应用里面启动一个web服务，让用户通过web界面配置一些该应用的参数，是不是用这个库很合适？

### ISSUE THREAD

**Issue by lh8986** [yanzhenjie/AndServer#512]
本身有一个普通的应用，用来控制硬件的开关的，以前应用里的参数是通过接口返回来的，调试的时候不好调试，现在想让用户 通过web配置一些参数，直接访问应用进行调试

**Comment by yanzhenjie** [comment]
非常合适，就是个本地server，用前端开发页面。
