### ISSUE TITLE
ResponseBody类的使用方法示例代码报错

### ISSUE THREAD

**Issue by qiubin2016** [yanzhenjie/AndServer#513]
文档地址：https://yanzhenjie.com/AndServer/class/ResponseBody.html

@Controller
public class ProjectController {

    @GetMapping("/project/info")
    public void info(HttpResponse response) {
        String content = ...;
        RequestBody body = new StringBody(content);
        response.setBody(body);
    }
}
客户端请求/project/info报异常：com.yanzhenjie.andserver.error.ServerInternalException: Server internal error, The return value of [null] is not supported.

**Comment by koro-1** [comment]
RequestBody  改成 ResponseBody

**Comment by yanzhenjie** [comment]
普通的Controller不能直接操作HttpResponse，看起来你应该需要使用RestController。
