### ISSUE TITLE
前端请求跨域问题

### ISSUE THREAD

**Issue by liuwenzhi1** [yanzhenjie/AndServer#516]
![03270b67498b57b2e7d651fdfa6fce0](https://github.com/yanzhenjie/AndServer/assets/12248315/f66d319b-ee64-4a13-9df1-785907058004)
您好，我已经增加了@CrossOrigin 但是前端数据请求的时候还是提示 has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. 版本号为2.1.12，有空能帮忙看下吗

**Comment by liuwenzhi1** [comment]
在postman上请求是正常的

**Comment by Shaooooo** [comment]
@liuwenzhi1 同样情况 ，如何解决的？
