### ISSUE TITLE
新版build.gralde如何导入plugin ？

### ISSUE THREAD

**Issue by shaojiankui** [yanzhenjie/AndServer#517]
gradle在7.0后，把依赖方式进行了修改。

旧版：
buildscript {
    ...
    dependencies {
        ...
        classpath 'com.yanzhenjie.andserver:plugin:2.1.12'
    }
}

新版：
plugins {
    id 'com.android.application' version '7.3.0' apply false
    id 'com.android.library' version '7.3.0' apply false
    id 'com.yanzhenjie.andserver' version '2.1.12' apply false
}

提示：
Plugin [id: 'com.yanzhenjie.andserver', version: '2.1.12', apply: false] was not found in any of the following sources:

查看pom文件：https://repo1.maven.org/maven2/com/yanzhenjie/andserver/plugin/2.1.12/plugin-2.1.12.pom

谁知道咋解决？在新版build.gradle引用这插件。

**Comment by shaojiankui** [comment]
`// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath 'com.yanzhenjie.andserver:plugin:2.1.12'
    }
}
plugins {
    id 'com.android.application' version '7.3.0' apply false
    id 'com.android.library' version '7.3.0' apply false
}
`

这样写就可以了。。。

**Comment by shaojiankui** [comment]
//// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        jcenter()
        maven { url "https://maven.google.com"}
        maven { url "https://dl.google.com/dl/android/maven2/"}
    }

    dependencies {
        classpath 'com.yanzhenjie.andserver:plugin:2.1.12'
        classpath "com.android.tools.build:gradle:4.2.2"
    }
}
plugins {
    id 'com.android.application' version '7.3.0' apply false
    id 'com.android.library' version '7.3.0' apply false
}


这样好像可以了。。。

**Comment by yanzhenjie** [comment]
指定项目主页给的仓库url即可。

**Comment by dongweiq** [comment]
最新版本gradle8.1.3如下，在最外层的build.gradle.kts中
`

buildscript{
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("com.yanzhenjie.andserver:plugin:2.1.12")
    }
}
plugins {
    id("com.android.application") version "8.1.3" apply false
    id("org.jetbrains.kotlin.android") version "1.8.10" apply false
}

`
