### ISSUE TITLE
IP地址有时候会为0.0.0.0

### ISSUE THREAD

**Issue by KingOfSu** [yanzhenjie/AndServer#52]
额,严大大就是我使用过程中有时候IP地址会变成0.0.0.0,然而实际的情况并不是这个数值,所以后面我是使用的判断wifi是否开启的广播,然后再开启服务,但是也是会偶尔发生这个问题,请问这个是什么原因呢?不能能否有方法将IP地址变成固定的域名或是固定ip,那个 InetAddress 类好像只能获取,求严大大教导一波!!

**Comment by KingOfSu** [comment]
还有就是严大大这个会报错  
java.lang.RuntimeException: Unable to start service  : android.os.NetworkOnMainThreadException

请问网络请求是在主线程吗？能否有进一步优化？

**Comment by yanzhenjie** [comment]
第一个问题：启动服务器时就需要你绑定`InetAddress`，这个类就是要你指定要绑定的IP的。  
第二个问题：AndServer的网络操作都是在子线程中的，包括`RequestHandler`、`WebSite`的回调方法。

**Comment by KingOfSu** [comment]
额，严大大我就是用您的Demo来进行项目的，刚刚看了一下您的确写了
     mServer = AndServer.serverBuilder()
                .inetAddress(NetUtils.getLocalIPAddress()) // Bind IP address.
                 这个来绑定IP地址，所以说哪个项目里面的
                hostAddress = mServer.getInetAddress().getHostAddress();
             其实作用不大的吗，真实的hostAddress应该是NetUtils.getLocalIPAddress() 对吗？

**Comment by yanzhenjie** [comment]
`NetUtils.getLocalIPAddress()`这是我demo中的一个工具方法，不一定要用这个。  
目前的版本中必须要绑定IP地址，后面我会优化一下如果没绑定就使用默认地址。

**Comment by KingOfSu** [comment]
好的，谢谢严大大，:P
