### ISSUE TITLE
多AndServer下，一个module使用MessageConverter，会转换另外一个module的请求。

### ISSUE THREAD

**Issue by zhanlan123** [yanzhenjie/AndServer#521]
两个module，都集成各自的AndServer，端口不一样。但是请求的时候，一个module使用MessageConverter，会转换另外一个module的请求。

**Comment by yanzhenjie** [comment]
不同的Converter是同一个组吗？是同一个组就是会转换的，你需要设置不同的组。

代码都是会打包到apk中的，和module没关系，和AndServer的分组有关系，如果你使用了2个server，那么你要对AndServer的这些注解组件做分组，启动的时候使用分组名去启动对应组的组件。

**Comment by zhanlan123** [comment]
哦，好的。了解了。

**Comment by zhanlan123** [comment]
我研究研究

**Comment by zhanlan123** [comment]
@Converter 这个注解需要给与一个值，这样写@Converter("moduleOne")，我理解应该没有错吧。

**Comment by zhanlan123** [comment]
谢谢严老大
