### ISSUE TITLE
Controller中接收到请求后需要做异步数据处理的怎么办？

### ISSUE THREAD

**Issue by crocrobo** [yanzhenjie/AndServer#522]
前端发送请求后， 我在Controller中处理请求，但是数据不是直接查询数据得来的， 而是需要我下发指令到一个模块，模块返回给我数据后再传给前端。

**Comment by yanzhenjie** [comment]
那你这个不叫异步，就是同步，你直接发指令到下一个模块，拿到数据再返回就行了。如果你的调用是瞬间的，那么直接在接口里面不同调用另一个模块就行，如果你的调用是长时间的，那么不合适通过接口请求&响应，因为客户端长时间收不到服务端响应，是可能会超时的，你要设计一个业务流程来完成这件事。如果你的调用受代码设计限制是异步且瞬间的，那么你使用Object.wait()和Object.notify()来完成这个工作。

这不是属于AndServer或者服务器或者Web框架的工作，而是一个业务流程问题。

**Comment by crocrobo** [comment]
是的，我想复杂了，直接使用就行。本地测试没问题，感谢您的回复。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yanzhenjie/AndServer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月2日(星期六) 下午2:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yanzhenjie/AndServer] Controller中接收到请求后需要做异步数据处理的怎么办？ (Issue #522)





 
那你这个不叫异步，就是同步，你直接发指令到下一个模块，拿到数据再返回就行了。如果你的调用是瞬间的，那么直接在接口里面不同调用另一个模块就行，如果你的调用是长时间的，那么不合适通过接口请求&amp;响应，因为客户端长时间收不到服务端响应，是可能会超时的，你要设计一个业务流程来完成这件事。如果你的调用受代码设计限制是异步且瞬间的，那么你使用Object.wait()和Object.notify()来完成这个工作。
 
这不是属于AndServer或者服务器或者Web框架的工作，而是一个业务流程问题。
