### ISSUE TITLE
上架Google 提示需要加密。请问是否有考虑加入https

### ISSUE THREAD

**Issue by southbaird** [yanzhenjie/AndServer#526]
针对所有网域允许传输明文流量
您的应用的网络安全配置针对所有网域允许传输明文流量。窃密者可以利用这一点拦截您的应用所发送的数据。如果这些数据是敏感数据或可用于识别用户身份，则可能会对用户的隐私带来不利影响。

建议您将 cleartextTrafficPermitted 标记设置为 false，或者为特定网域添加加密政策，从而仅允许传输加密流量。

**Comment by yanzhenjie** [comment]
AndServer是支持https的，需要你自己设置证书。另外你的问题，应该和AndServer无关，是Android的一个特性，你可以查一下官网资料。
