### ISSUE TITLE
网站部署在SD卡访问不了,求大神指点

### ISSUE THREAD

**Issue by cfr999** [yanzhenjie/AndServer#53]
整个web文件夹复制到/storage/emulated/0/  下面:
File file = new File(Environment.getExternalStorageDirectory(), "web");
        String websiteDirectory = file.getAbsolutePath();
  StorageWebsite sn = new StorageWebsite(websiteDirectory);
        AndServer andServer = new AndServer.Build()
                .port(8080)
                .timeout(10 * 1000)
                .registerHandler("login", new RequestLoginHandler())
                // .registerHandler("download", new RequestFileHandler("Your file path"))
                .registerHandler("upload", new RequestUploadHandler())
//               .website(new AssetsWebsite(mAssetManager, "web"))   //网站部署在assets
                .website(sn)                //网站部署在外部存储卡
                .listener(mListener)
                .build();
        mServer = andServer.createServer();
一直访问不了,有什么设置我没改到的吗?我只改这里,跑的是Demo的代码.
我加了这些权限:
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS"/>

**Comment by cfr999** [comment]
<uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS"/>

**Comment by yanzhenjie** [comment]
mServer.startup();

**Comment by cfr999** [comment]
http://192.168.1.123:8080/  就这个可以,其他比如这样
http://192.168.1.123:8080/web/image/image.jpg   就不行了

**Comment by yanzhenjie** [comment]
没有web，具体规则请看文档，这种文档上写的问题就别提了。
