### ISSUE TITLE
post请求携带form-data数据时，文件和文本参数一定要分开吗，可以支持不分开吗

### ISSUE THREAD

**Issue by threepeples** [yanzhenjie/AndServer#530]
现在有个需求是上传form-data参数，执行一系列操作，有的需要上传文件，有的是文本参数，要按顺序操作。但是现在把文件和文本的参数分开了，原有顺序就不知道了

**Comment by yanzhenjie** [comment]
http协议就是这样规定的，无法合并，一个form已经是一起提交了，form本身就是无序的。你按照名称取对应参数即可。
