### ISSUE TITLE
您好，请问1.1.1版本如何加快传输速度

### ISSUE THREAD

**Issue by leielyq** [yanzhenjie/AndServer#54]
感觉现在比以前的传输速度慢很多啊，比以前慢上一倍了。我将这个项目用在局域网文件传输上了，现在速度成了一个大问题啊。
下面是我开启服务的代码，请教如何加快传输速度：
mAndServer = AndServer.serverBuilder()
                .port(8087)
                .website(mWebSite)
                .listener(mListener)
                .build();

**Comment by leielyq** [comment]
也有可能是老家的路由器比较差

**Comment by yanzhenjie** [comment]
传输这一块应该和之前没区别的，你在之前的环境中做个测试看看。

**Comment by leielyq** [comment]
嗯啊  路由器是制约传输速度上限的主要原因
