### ISSUE TITLE
这说明文档是闹着玩的吧，错漏摆出

### ISSUE THREAD

**Issue by CronZhu** [yanzhenjie/AndServer#541]
问题当且仅针对2.1.12
（1）、ResponseBody部分，说明文档“RequestBody body = new JsonBody(jsonObj);”，返回的是ResponseBody怎么写成RequestBody 了
（2）、void类型函数中，response.setBody()设置无效，无效！！！！个人解决方法：只能通过返回new ResponseBody()的方式解决。

**Comment by yanzhenjie** [comment]
先回答问题。

1. 确实写错了。
<img width="797" alt="image" src="https://github.com/yanzhenjie/AndServer/assets/13534988/b13f718c-9aef-4e54-ab88-f800bc92634a">

2. `HttpResponse#setBody(ResponseBody)`只支持`@Controller`注解，`@RestController`会被覆盖，请正确使用。

**Comment by FunkyYang** [comment]
https://github.com/yanzhenjie/AndServer/issues/541 前后矛盾
