### ISSUE TITLE
请问这个只适用于局域网吗？公网可以吗？

### ISSUE THREAD

**Issue by lexluthors** [yanzhenjie/AndServer#55]
请问这个只适用于局域网吗？公网可以吗？

**Comment by yanzhenjie** [comment]
可以，这只是一个服务器软件+服务端开发框架，并不限制你的部署环境。

**Comment by lexluthors** [comment]
@yanzhenjie 嗯嗯，我是小白，不是很懂别见怪啊。请问如何实现公网访问哈？

**Comment by yanzhenjie** [comment]
你只需要部署在公网环境就可以了，这个项目做不了什么的，细节你可以咨询一下做服务器开发的同事或者朋友。

**Comment by lexluthors** [comment]
@yanzhenjie 嗯嗯，谢谢哈
