### ISSUE TITLE
可以通过url访问到安卓设备中sdcard路径下的内容吗

### ISSUE THREAD

**Issue by Shaooooo** [yanzhenjie/AndServer#559]
可以通过url访问到安卓设备中sdcard路径下的内容吗

**Comment by shouhulife** [comment]
@Config
public class AppConfig implements WebConfig {

    @Override
    public void onConfig(Context context, Delegate delegate) {
        // 增加一个位于assets的web目录的网站
        delegate.addWebsite(new AssetsWebsite(context, "/web/"));

        // 增加一个位于/sdcard/Download/AndServer/目录的网站
        delegate.addWebsite(new StorageWebsite(context, "/sdcard/Download/AndServer/"));
    }
}

**Comment by Shaooooo** [comment]
> @config public class AppConfig implements WebConfig {
> 
> ```
> @Override
> public void onConfig(Context context, Delegate delegate) {
>     // 增加一个位于assets的web目录的网站
>     delegate.addWebsite(new AssetsWebsite(context, "/web/"));
> 
>     // 增加一个位于/sdcard/Download/AndServer/目录的网站
>     delegate.addWebsite(new StorageWebsite(context, "/sdcard/Download/AndServer/"));
> }
> ```
> 
> }

好的 感谢！
