### ISSUE TITLE
服务器能否使用如127.0.0.1这种指定的IP地址

### ISSUE THREAD

**Issue by huxiaoxi1992** [yanzhenjie/AndServer#56]
有个项目需要启动一个本地服务器作为web Server，网络正常时使用无问题，但是在断网状态下无法获取IP地址，能不能启动一个固定IP地址的服务只需要让当前设备在离线时能够使用。

mServer = AndServer.serverBuilder()
                .inetAddress(NetUtils.getLocalIPAddress()) // Bind IP address.
                .port(8080)
                .timeout(10, TimeUnit.SECONDS)
                .website(new AssetsWebsite(getAssets(), "www"))
                .filter(new HttpCacheFilter())
                .listener(mListener)
                .build();
        mServer.startup();
当前获取本地IP作为服务器的IP地址，我需要启动一个固定IP下的服务，需要怎么去做？

**Comment by yanzhenjie** [comment]
你应该在你的硬件环境下手，AndServer做不了什么，绑定IP的Api已经提供给你了。
