### ISSUE TITLE
定义接口之后无法访问The resource [//login] does not exist.

### ISSUE THREAD

**Issue by jasonhantao** [yanzhenjie/AndServer#59]
andServer = (Server) AndServer.serverBuilder()
                .inetAddress(NetUtils.getLocalIPAddress())
                .port(8848)
                .timeout(10, TimeUnit.SECONDS)
                .listener(mListener)
                .registerHandler("/login",new LoginHandler())
                .build();

        InetAddress address = NetUtils.getLocalIPAddress();
        address.getHostAddress();
        andServer.startup();

启动服务没问题但是访问接口会返回的是
The resource [//login] does not exist.

**Comment by yanzhenjie** [comment]
#58
