### ISSUE TITLE
onError:bind failed: EADDRINUSE (Address already in use) 版本 ：1.1.3

### ISSUE THREAD

**Issue by tony8110** [yanzhenjie/AndServer#62]
完全按照sample的用法调用shutdown，然后收到server stop回调后再调用start接口，偶现onError:bind failed: EADDRINUSE (Address already in use)，概率还不算小，基本每天都会碰到。

**Comment by yanzhenjie** [comment]
不是必现吧？我们做测试时用原生模拟器、小米4C，魅族和华为`stop->start`很多次都没有出现这个问题，不过我们是在Demo上手动点击的，不是`onStop()`后自动start()`，我猜测可能是自动`start()`时太快（当前`stop()`的这个调用栈没释放掉），底层还没真正释放这个地址，如果我的猜测是真的，这个是`AndServer`的问题。
你可以试试`onStop()`完了后，停顿250ms以上，然后再调用`start()`，看看能不能最快的解决你的问题，我们会尽快排查问题并发布新版本。

**Comment by tony8110** [comment]
不是必现 概率性的 延时我们已经加上了 而且远远超过250ms 但是还是会偶现这个问题

**Comment by tony8110** [comment]
提供一个线索 我们在stop的时候 一般都有客户端正在访问服务器 不知道和这个有没有关系 供参考

**Comment by tony8110** [comment]
我们做了一个测试，没有任何客户端连接的时候，不停地stop后start循环，一个小时也没有出现那个错误；然后打开几个客户端同时访问服务器，十分钟之内就出现那个错误，供参考！

**Comment by yanzhenjie** [comment]
收到，非常感谢。我会尽快安排更新计划。

**Comment by tony8110** [comment]
不客气

**Comment by tony8110** [comment]
我们又做了多次测试，从现象上看，基本可以判定就是因为stop的时候，如果有（多个）客户端正在和服务器交互，就会出现这个bug，烦请尽快解决，谢谢！

**Comment by yanzhenjie** [comment]
感谢帮忙一起测试，我也测试了能确定是这个问题。我正在研究解决方案，但是工作比较忙所以不能太及时，望理解，但是一定会在这两天内尽快解决。

**Comment by tony8110** [comment]
好的 辛苦了 朋友！

**Comment by q979713444** [comment]
请问大神是否已经解决了这个问题

**Comment by tony8110** [comment]
@yanzhenjie 请问一下 这个问题解决了么？

**Comment by yanzhenjie** [comment]
已经发布的1.1.4中修复了这个问题，#73。
