### ISSUE TITLE
我把视频放在服务器目录下，http去请求视频地址，不能在线播放，只能下载

### ISSUE THREAD

**Issue by cai784921129** [yanzhenjie/AndServer#79]
这个服务器不支持边下载边播放吗？视频很大的情况下，要下载完才能播放，是要等很久的

**Comment by yanzhenjie** [comment]
服务端只是负责输出这个文件，客户端似乎可以边下边播的，是不是是客户端问题？使用的video标签还是浏览器？浏览器可能会直接下载。

**Comment by cai784921129** [comment]
用的video标签，我认为可能与视频格式有关系，有的视频支持边下边播，有的不能。所以我就把不支持的视频放在另个（php搭建的服务器上），又是可以边下边播的。
所以我认为可能跟服务器也有关系

**Comment by Nelson-KK** [comment]
我也想问一下，我有一个视频文件的流，怎么实现在 AndroidApp（第三方）  上面在线播放

**Comment by yanzhenjie** [comment]
这种一般都是和http头有关，例如Content-Disposition，我没纠察过具体是哪个头影响了，你们可以对比一下。
