### ISSUE TITLE
请问有什么方便的方式实现Session和Cookie呢？

### ISSUE THREAD

**Issue by StephenLeo** [yanzhenjie/AndServer#80]

**Comment by yanzhenjie** [comment]
目前没有太好的方式，后面会封装起来。

**Comment by yanzhenjie** [comment]
@StephenLeo 你好，这个功能已经实现了，请查看dev分支。

在dev分支发布了2.0.0，可以像SpringMVC一样开发，非常方便。因为文档没写完，所以还在dev分支，熟悉SpringMVC的话可以先使用了。
