### ISSUE TITLE
更换ip 重启服务就没用了啊

### ISSUE THREAD

**Issue by ailiboy520** [yanzhenjie/AndServer#82]
当前网络ip  手动更换 后就不能启动服务了，
bind failed: EADDRNOTAVAIL (Cannot assign requested address)

**Comment by yanzhenjie** [comment]
是否没有更新AndServer的ip，你要重新获取新的本地ip，然后重新给AndServer绑定你的新ip。

**Comment by ailiboy520** [comment]
这样的 本地ip没有变 ，手动更换ip后 再 停止服务，再重启服务，就提示这个了

**Comment by ailiboy520** [comment]
项目中更换ip的功能

**Comment by yanzhenjie** [comment]
本地ip没变，你更换的ip是什么ip？

**Comment by ailiboy520** [comment]
比如  自动获取到的ip 是192.168.1.108     修改为192.168.1.109后  就不能启动了

**Comment by yanzhenjie** [comment]
你是修改了机器的ip吗？还说获取到的是192.168.1.108，你传给AndServer的是192.168.1.109？

**Comment by ailiboy520** [comment]
直接在传给AndServer的是192.168.1.109

**Comment by ailiboy520** [comment]
public void onCreate() {
        ActivityHolder.getInstance().addService(this);
       try {
           // More usage documentation: http://yanzhenjie.github.io/AndServer
           String ip = SharedpreferencesUtil.getString(getApplicationContext(),Constant.User.IP);
           InetAddress inetAddress = null;
           if (TextUtils.isEmpty(ip)){
               inetAddress = InetAddress.getByName(CommonUtil.getIPAddress(getApplicationContext()));
           }else {
               inetAddress = InetAddress.getByName(ip);
           }
           mServer = AndServer.serverBuilder()
                   .inetAddress(inetAddress) // Bind IP address.
                   .port(9090)
                   .timeout(30, TimeUnit.SECONDS)
                   .website(new AssetsWebsite(getAssets(), "web"))
                   .registerHandler("/download", new FileHandler())
                   .registerHandler("/login", new LoginHandler())
                   .registerHandler("/upload", new UploadHandler())
                   .registerHandler("/image", new ImageHandler())
                   .filter(new HttpCacheFilter())
                   .listener(mListener)
                   .build();
       }catch (Exception e){
           e.printStackTrace();
       }
    }

**Comment by ailiboy520** [comment]
上面的代码是你coreservice中执行的    我是更换ip后停止socket  停止service 然后 再startService 启动出现的

**Comment by yanzhenjie** [comment]
您好，我必须要说几点。跟您沟通了三天时间，每次我都很及时的回复您的问题，但是我至今还不是很清楚问题是什么。
我只能告诉您，一个原则是必须传入本机的真实本地ip地址，如果您要固定设备的ip地址，请从设备着手，本库只能做`Server + WebFramework`的工作，如果您明白了问题的原理，麻烦您关闭这个issue。

**Comment by yanzhenjie** [comment]
抱歉，发布上一条评论时，我只看到了这句`直接在传给AndServer的是192.168.1.109`，没看到您回复后面的评论，无论如何还是只能回复您上面的那个评论中的内容，望您能理解，谢谢您。

**Comment by ailiboy520** [comment]
好的，我以为这个库支持ip更换的
