### ISSUE TITLE
AndServer.serverBuilder().timeout()设置超时无效

### ISSUE THREAD

**Issue by zhengguirong** [yanzhenjie/AndServer#83]
当AndServer.serverBuilder的构建放在子线程中执行时，超时不起作用
 mExecutorService.execute(() -> {
            try {
                Looper.prepare();
                mServer = AndServer.serverBuilder()
                        .inetAddress(NetUtil.getLocalIPAddress()) // Bind IP address.
                        .port(8080)
                        .timeout(30, TimeUnit.SECONDS)
                        .registerHandler("/request1", new Requeset1())
                        .registerHandler("/request2", new Request2())
                        .filter(new HttpCacheFilter())
                        .listener(mListener)
                        .build();

                startServer();
            } catch (Exception e) {
                e.printStackTrace();
            }
        });

**Comment by yanzhenjie** [comment]
你好，server的构建不分主线程和子线程。服务器启动也不区分主线程和子线程，但是建议放在主线程。
超时是直接设置在ServerSocket上的，可能和你理解的不一样。

你可以看一下这个回答：[https://www.zhihu.com/question/21609463/answer/160100810](https://www.zhihu.com/question/21609463/answer/160100810)

这个回答中的原理，同样的适用于ServerSocket。

**Comment by zhengguirong** [comment]
可能是我程序的问题，我在请求的RequestHandler另外用了CountdownTimer去计算处理超时，但是我在构建时调了Looper.prepare()，由于CountdownTimer底层是handler写的，这可能造成了冲突导致程序异常，表现为请求发起后永不超时
