### ISSUE TITLE
将安卓设备移动热点打开作为路由

### ISSUE THREAD

**Issue by darkSuperman** [yanzhenjie/AndServer#88]
作者你好:
  就是将一台安卓设备打开移动热点作为路由，然后别的手机用wifi连上这个设备热点后,手机的所有的http请求都可以截获，也可以将请求进行重定向。请问可以通过改造你这个项目实现吗？

**Comment by yanzhenjie** [comment]
可以，这个项目起一个本地server，相当于nginx + tomcat，本项目起的server相当于tomcat，做转发的那个function相当于nginx。
