### ISSUE TITLE
How does AndServer do foreigner access?

### ISSUE THREAD

**Issue by TaroXin** [yanzhenjie/AndServer#9]
I would like to ask, how can we not in the same wifi under the two devices through AndServer visit, do you have ideas, thank you very much

**Comment by yanzhenjie** [comment]
We must know, whether it is http, or socket, as long as it involves communication, one of the devices must be a server, under normal circumstances, the two mobile phone communications will rely on an intermediate server or in the same router, if your phone has a unique IP, then the phone can be used as a server, then you can use `AndServer` to achieve communication, of course, this is not necessary.

**Comment by TaroXin** [comment]
Thank you for your answer, I think I should consider the Android network penetration
