### ISSUE TITLE
响应的数据量大了，频繁请求后，必现500。是否有办法优化

### ISSUE THREAD

**Issue by luoshiduan** [yanzhenjie/AndServer#91]
07-26 09:05:52.516 W/System.err( 2706): java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
07-26 09:05:52.517 W/System.err( 2706): java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
07-26 09:05:52.519 W/System.err( 2706): 	at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:545)
07-26 09:05:52.519 W/System.err( 2706): 	at libcore.io.IoBridge.recvfrom(IoBridge.java:509)
07-26 09:05:52.519 W/System.err( 2706): 	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
07-26 09:05:52.519 W/System.err( 2706): 	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
07-26 09:05:52.519 W/System.err( 2706): 	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
07-26 09:05:52.520 W/System.err( 2706): 	at 	at org.apache.httpcore.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
07-26 09:05:52.520 W/System.err( 2706): 	at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:545)
07-26 09:05:52.520 W/System.err( 2706): 	at org.apache.httpcore.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)libcore.io.IoBridge.recvfrom(IoBridge.java:509)
07-26 09:05:52.520 W/System.err( 2706): 	at 
07-26 09:05:52.520 W/System.err( 2706): 	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)org.apache.httpcore.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
07-26 09:05:52.520 W/System.err( 2706): 	at 
07-26 09:05:52.520 W/System.err( 2706): 	at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:130)
07-26 09:05:52.521 W/System.err( 2706): 	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:54)
07-26 09:05:52.521 W/System.err( 2706): 	at 
07-26 09:05:52.521 W/System.err( 2706): 	at org.apache.httpcore.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
07-26 09:05:52.521 W/System.err( 2706): 	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)org.apache.httpcore.impl.DefaultBHttpServerConnection.receiveRequestHeader(DefaultBHttpServerConnection.java:130)
07-26 09:05:52.521 W/System.err( 2706): 	at 
07-26 09:05:52.521 W/System.err( 2706): 	at org.apache.httpcore.protocol.HttpService.handleRequest(HttpService.java:308)
07-26 09:05:52.522 W/System.err( 2706): 	at org.apache.httpcore.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
07-26 09:05:52.522 W/System.err( 2706): 	at org.apache.httpcore.impl.bootstrap.Worker.run(Worker.java:66)
07-26 09:05:52.522 W/System.err( 2706): 	at org.apache.httpcore.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
07-26 09:05:52.522 W/System.err( 2706): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
07-26 09:05:52.522 W/System.err( 2706): org.apache.httpcore.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
07-26 09:05:52.522 W/System.err( 2706): 	at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:130)
07-26 09:05:52.523 W/System.err( 2706): 	at 	at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:54)
07-26 09:05:52.523 W/System.err( 2706): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
07-26 09:05:52.523 W/System.err( 2706): 	at java.lang.Thread.run(Thread.java:841)
07-26 09:05:52.523 W/System.err( 2706): org.apache.httpcore.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
07-26 09:05:52.523 W/System.err( 2706): 	at Caused by: org.apache.httpcore.impl.DefaultBHttpServerConnection.receiveRequestHeader(DefaultBHttpServerConnection.java:130)
07-26 09:05:52.523 W/System.err( 2706): 	at libcore.io.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
07-26 09:05:52.524 W/System.err( 2706): org.apache.httpcore.protocol.HttpService.handleRequest(HttpService.java:308)
07-26 09:05:52.524 W/System.err( 2706): 	at org.apache.httpcore.impl.bootstrap.Worker.run(Worker.java:66)
07-26 09:05:52.524 W/System.err( 2706): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
07-26 09:05:52.524 W/System.err( 2706): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
07-26 09:05:52.525 W/System.err( 2706): 	at 	at libcore.io.Posix.recvfromBytes(Native Method)
07-26 09:05:52.525 W/System.err( 2706): 	at java.lang.Thread.run(Thread.java:841)
07-26 09:05:52.525 W/System.err( 2706): Caused by: libcore.io.Posix.recvfrom(Posix.java:141)
07-26 09:05:52.525 W/System.err( 2706): 	at libcore.io.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
07-26 09:05:52.526 W/System.err( 2706): libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:164)
07-26 09:05:52.526 W/System.err( 2706): 	at libcore.io.IoBridge.recvfrom(IoBridge.java:506)
07-26 09:05:52.526 W/System.err( 2706): 	... 15 more
07-26 09:05:52.526 W/System.err( 2706): 	at libcore.io.Posix.recvfromBytes(Native Method)
07-26 09:05:52.527 W/System.err( 2706): 	at libcore.io.Posix.recvfrom(Posix.java:141)
07-26 09:05:52.527 W/System.err( 2706): 	at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:164)
07-26 09:05:52.527 W/System.err( 2706): 	at libcore.io.IoBridge.recvfrom(IoBridge.java:506)

===========================================================
07-26 09:05:57.176 W/System.err( 2706): org.apache.httpcore.ConnectionClosedException: Client closed connection
07-26 09:05:57.176 W/System.err( 2706): org.apache.httpcore.ConnectionClosedException: Client closed connection
07-26 09:05:57.177 W/System.err( 2706): 	at 	at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:132)
07-26 09:05:57.177 W/System.err( 2706): 	at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:54)
07-26 09:05:57.178 W/System.err( 2706): 	at org.apache.httpcore.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
07-26 09:05:57.178 W/System.err( 2706): 	at org.apache.httpcore.impl.DefaultBHttpServerConnection.receiveRequestHeader(DefaultBHttpServerConnection.java:130)
07-26 09:05:57.178 W/System.err( 2706): 	at org.apache.httpcore.protocol.HttpService.handleRequest(HttpService.java:308)
07-26 09:05:57.178 W/System.err( 2706): 	at org.apache.httpcore.impl.bootstrap.Worker.run(Worker.java:66)
07-26 09:05:57.178 W/System.err( 2706): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
07-26 09:05:57.179 W/System.err( 2706): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
07-26 09:05:57.179 W/System.err( 2706): 	at java.lang.Thread.run(Thread.java:841)
07-26 09:05:57.180 W/System.err( 2706): org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:132)
07-26 09:05:57.180 W/System.err( 2706): 	at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:54)
07-26 09:05:57.180 W/System.err( 2706): 	at org.apache.httpcore.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
07-26 09:05:57.180 W/System.err( 2706): 	at org.apache.httpcore.impl.DefaultBHttpServerConnection.receiveRequestHeader(DefaultBHttpServerConnection.java:130)
07-26 09:05:57.180 W/System.err( 2706): 	at org.apache.httpcore.protocol.HttpService.handleRequest(HttpService.java:308)
07-26 09:05:57.180 W/System.err( 2706): 	at org.apache.httpcore.impl.bootstrap.Worker.run(Worker.java:66)
07-26 09:05:57.181 W/System.err( 2706): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
07-26 09:05:57.181 W/System.err( 2706): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
07-26 09:05:57.181 W/System.err( 2706): 	at java.lang.Thread.run(Thread.java:841)
07-26 09:05:57.266 D/dalvikvm( 2207): GC_FOR_ALLOC freed 263K, 5% free 71524K/74692K, paused 103ms, total 103ms
07-26 09:05:57.486 I/MxService( 2207): [2207/1]<278/733/95>[run/handleCallback/dispatchMessage]: keep.alive:16890
07-26 09:05:57.548 I/ResumableUploadUtil( 2207): [2207/265]<331/326/349>[onProgress/onProgress/onProgressCallback]: ResumableUploadUtil 	currentSize: 1572864 totalSize: 4437604
07-26 09:05:57.577 I/ResumableUploadUtil( 2207): [2207/268]<331/326/349>[onProgress/onProgress/onProgressCallback]: ResumableUploadUtil 	currentSize: 1835008 totalSize: 4437604
07-26 09:05:57.683 D/dalvikvm( 2207): GC_FOR_ALLOC freed 1300K, 5% free 71336K/74692K, paused 106ms, total 106ms
07-26 09:05:57.686 W/System.err( 2207): java.net.SocketException: sendto failed: ECONNRESET (Connection reset by peer)
07-26 09:05:57.688 W/System.err( 2207): 	at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:499)
07-26 09:05:57.689 W/System.err( 2207): 	at libcore.io.IoBridge.sendto(IoBridge.java:468)
07-26 09:05:57.690 W/System.err( 2207): 	at java.net.PlainSocketImpl.write(PlainSocketImpl.java:507)
07-26 09:05:57.690 W/System.err( 2207): 	at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:46)
07-26 09:05:57.690 W/System.err( 2207): 	at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:269)
07-26 09:05:57.691 W/System.err( 2207): 	at okio.Okio$1.write(Okio.java:78)
07-26 09:05:57.691 W/System.err( 2207): 	at okio.AsyncTimeout$1.write(AsyncTimeout.java:179)
07-26 09:05:57.692 W/System.err( 2207): 	at okio.RealBufferedSink.flush(RealBufferedSink.java:216)
07-26 09:05:57.692 W/System.err( 2207): 	at okhttp3.internal.http1.Http1Codec$FixedLengthSink.flush(Http1Codec.java:293)
07-26 09:05:57.692 W/System.err( 2207): 	at okio.RealBufferedSink.flush(RealBufferedSink.java:218)
07-26 09:05:57.693 W/System.err( 2207): 	at com.alibaba.sdk.android.oss.network.ProgressTouchableRequestBody.writeTo(ProgressTouchableRequestBody.java:62)
07-26 09:05:57.693 W/System.err( 2207): 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:48)
07-26 09:05:57.693 W/System.err( 2207): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
07-26 09:05:57.694 W/System.err( 2207): 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
07-26 09:05:57.694 W/System.err( 2207): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
07-26 09:05:57.695 W/System.err( 2207): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
07-26 09:05:57.695 I/ResumableUploadUtil( 2207): [2207/266]<331/326/349>[onProgress/onProgress/onProgressCallback]: ResumableUploadUtil 	currentSize: 2097152 totalSize: 4437604
07-26 09:05:57.695 W/System.err( 2207): 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
07-26 09:05:57.695 W/System.err( 2207): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
07-26 09:05:57.696 I/ResumableUploadUtil( 2207): [2207/267]<331/326/349>[onProgress/onProgress/onProgressCallback]: ResumableUploadUtil 	currentSize: 2359296 totalSize: 4437604
07-26 09:05:57.796 D/dalvikvm( 2207): GC_FOR_ALLOC freed 636K, 5% free 71338K/74692K, paused 100ms, total 100ms
07-26 09:05:57.797 W/System.err( 2207): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
07-26 09:05:57.797 W/System.err( 2207): 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
07-26 09:05:57.798 W/System.err( 2207): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
07-26 09:05:57.798 W/System.err( 2207): 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
07-26 09:05:57.798 W/System.err( 2207): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
07-26 09:05:57.799 W/System.err( 2207): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
07-26 09:05:57.799 W/System.err( 2207): 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
07-26 09:05:57.799 W/System.err( 2207): 	at okhttp3.RealCall.execute(RealCall.java:63)
07-26 09:05:57.800 W/System.err( 2207): 	at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:174)
07-26 09:05:57.800 W/System.err( 2207): 	at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:44)
07-26 09:05:57.800 W/System.err( 2207): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-26 09:05:57.801 W/System.err( 2207): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
07-26 09:05:57.801 W/System.err( 2207): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
07-26 09:05:57.801 W/System.err( 2207): 	at java.lang.Thread.run(Thread.java:841)
07-26 09:05:57.802 W/System.err( 2207): Caused by: libcore.io.ErrnoException: sendto failed: ECONNRESET (Connection reset by peer)
07-26 09:05:57.808 W/System.err( 2207): 	at libcore.io.Posix.sendtoBytes(Native Method)
07-26 09:05:57.808 W/System.err( 2207): 	at libcore.io.Posix.sendto(Posix.java:156)
07-26 09:05:57.808 W/System.err( 2207): 	at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:177)
07-26 09:05:57.808 W/System.err( 2207): 	at libcore.io.IoBridge.sendto(IoBridge.java:466)
07-26 09:05:57.808 W/System.err( 2207): 	... 30 more

**Comment by luoshiduan** [comment]
嗯嗯。就是这个打印和我描述的服务器500，没有必然关系是吧。
测试的时候会出现500，502，503，504，都有出现。作者您有没有遇到过或者其他人反馈过，或者优化策略？

**Comment by yanzhenjie** [comment]
502表示服务器从上游服务器收到一个无效的响应。
503表示服务器临时过载或当机。
504网关超时。
503可能会出现，但是客户端连接不多时应该也不会出现，504是网关超时，就是服务器中间有一步可能做了耗时操作超时了，这个可以自行优化。

另外在dev分支发布了2.0.0，可以像SpringMVC一样开发，非常方便。因为文档没写完，所以还在dev分支，熟悉SpringMVC的人可以先使用了。
