### ISSUE TITLE
json参数接收

### ISSUE THREAD

**Issue by jhd900518** [yanzhenjie/AndServer#93]
能否设置application/json，客户端传递json数据，服务端在body中接收json数据

**Comment by zxf527** [comment]
HttpRequestParser.getContentFromBody(request);

**Comment by jhd900518** [comment]
后来看了框架解决了，谢谢了

**Comment by yanzhenjie** [comment]
在dev分支发布了2.0.0，可以像SpringMVC一样开发，非常方便。因为文档没写完，所以还在dev分支，熟悉SpringMVC的人可以先使用了。
