### ISSUE TITLE
关于注册接口

### ISSUE THREAD

**Issue by Nelson-KK** [yanzhenjie/AndServer#98]
.registerHandler("file", new FileHelpHandler())
http://192.168.33.41:8080/file?username=123
我在浏览器输入连接地址，为下面提示，是为什么

The resource [/file] does not exist.

**Comment by yanzhenjie** [comment]
`.registerHandler(String, HelpHandler)`的第一个参数是path，须符合path规则。

我想讲一些真话，望你莫生气，真的是想真正帮助到你。
你的问题质量很低，例如下午的前两个问题就是开发环境的问题，这是基础。当前问题就算你不了解path，demo和文档中写的清清楚楚的，说明你连demo和文档都没看就来提问了。遇到问题首先要自己找答案，而不是直接拋给别人，尤其是使用开源项目，
